// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Rest
{
    /// <summary>
    /// 클라이언트가 구현하는 HTTP 경계. JSON POST, api-secret-key 공급, session 요청의 uid/user-session-key 공급을 소유한다.
    /// Headers의 필수 조건을 전송 전에 검사한다. RequestId는 같은 논리 요청의 재시도에서 유지하며 자동 재시도하지 않는다.
    /// HTTP status와 code를 먼저 검사한다. code != SUCCESS이면 ApiErrorBody와 HTTP status를 보존한 예외를 전달한다.
    /// SUCCESS일 때만 CommonBody&lt;TRes&gt;로 역직렬화한다. 취소·네트워크 오류를 성공/빈 응답으로 바꾸지 않는다.
    /// </summary>
    public interface IRestClient
    {
        Cysharp.Threading.Tasks.UniTask<CommonBody<TRes>> PostAsync<TReq, TRes>(RestEndpoint endpoint, TReq request, RestRequestOptions options, System.Threading.CancellationToken cancellationToken);
    }
    public sealed class RestEndpoint
    {
        public string Path { get; }
        public bool RequiresSession { get; }
        public bool RequiresApiKey => true;
        public IReadOnlyList<RestHeaderRequirement> Headers { get; }
        public RestEndpoint(string path, bool requiresSession, RestHeaderRequirement[] headers)
        { Path = path; RequiresSession = requiresSession; Headers = Array.AsReadOnly(headers); }
    }
    public sealed class RestHeaderRequirement
    {
        public string Name { get; }
        public bool Required { get; }
        public RestHeaderRequirement(string name, bool required) { Name = name; Required = required; }
    }
    /// <summary>호출 시점의 헤더 값. 인증 상태는 IRestClient 구현에서 공급한다.</summary>
    public sealed class RestRequestOptions
    {
        public string? ClientVersion { get; set; }
        public string? RequestId { get; set; }
        public string? TableVersion { get; set; }
    }
}
