// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Rest
{
    public sealed class RestPublicService : Services.IPublicService
    {
        private readonly IRestClient _client;
        public RestPublicService(IRestClient client) { _client = client ?? throw new ArgumentNullException(nameof(client)); }
        /// <summary>
        /// 로그인
        /// Firebase 익명·소셜 로그인 (ID token 검증 → 동일 Firebase UID의 게임 계정 조회/자동 가입)
        /// </summary>
        public Cysharp.Threading.Tasks.UniTask<CommonBody<LoginRes>> LoginAsync(LoginReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default)
        {
            return _client.PostAsync<LoginReq, LoginRes>(new Rest.RestEndpoint("/client/public/login", false, new Rest.RestHeaderRequirement[] { new Rest.RestHeaderRequirement("client-version", false) }), request, options, cancellationToken);
        }
    }
}
