// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Rest
{
    public sealed class RestCurrencyService : Services.ICurrencyService
    {
        private readonly IRestClient _client;
        public RestCurrencyService(IRestClient client) { _client = client ?? throw new ArgumentNullException(nameof(client)); }
        /// <summary>
        /// 재화 조회
        /// 자동 충전 정산 없이 현재 asset의 revision·rice·free_gold·paid_gold·time_stone 스냅샷을 조회한다.
        /// </summary>
        public Cysharp.Threading.Tasks.UniTask<CommonBody<AssetDto>> InfoAsync(EmptyRes request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default)
        {
            return _client.PostAsync<EmptyRes, AssetDto>(new Rest.RestEndpoint("/client/private/currency/info", true, new Rest.RestHeaderRequirement[] {  }), request, options, cancellationToken);
        }
        /// <summary>
        /// 군량 충전 타이머
        /// 경과 시간을 서버 시각으로 정산해 군량을 갱신하고 다음 충전까지 남은 시간·상한·주기를 반환한다.
        /// </summary>
        public Cysharp.Threading.Tasks.UniTask<CommonBody<RiceTimerRes>> RiceTimerAsync(EmptyRes request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default)
        {
            return _client.PostAsync<EmptyRes, RiceTimerRes>(new Rest.RestEndpoint("/client/private/currency/rice/timer", true, new Rest.RestHeaderRequirement[] {  }), request, options, cancellationToken);
        }
    }
}
