// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Rest
{
    public sealed class RestRaidService : Services.IRaidService
    {
        private readonly IRestClient _client;
        public RestRaidService(IRestClient client) { _client = client ?? throw new ArgumentNullException(nameof(client)); }
        /// <summary>
        /// 레이드 현재 상태
        /// 서버 공용 회차·HP·시각과 본인의 누적 피해·시즌 포인트를 조회한다.
        /// </summary>
        public Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.RaidStateRes>> StateAsync(global::ThreeKingdoms.Shared.Types.RaidStateReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default)
        {
            return _client.PostAsync<global::ThreeKingdoms.Shared.Types.RaidStateReq, global::ThreeKingdoms.Shared.Types.RaidStateRes>(new Rest.RestEndpoint("/client/private/raid/state", true, new Rest.RestHeaderRequirement[] {  }), request, options, cancellationToken);
        }
        /// <summary>
        /// 레이드 참가와 재접속
        /// 기본 단계 참가 마감 전 신규 참가하고, 기존 참가자는 진 단계에서도 같은 참가 상태를 복원한다.
        /// </summary>
        public Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.RaidStateRes>> JoinAsync(global::ThreeKingdoms.Shared.Types.RaidJoinReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default)
        {
            return _client.PostAsync<global::ThreeKingdoms.Shared.Types.RaidJoinReq, global::ThreeKingdoms.Shared.Types.RaidStateRes>(new Rest.RestEndpoint("/client/private/raid/join", true, new Rest.RestHeaderRequirement[] {  }), request, options, cancellationToken);
        }
        /// <summary>
        /// 레이드 피해 랭킹
        /// 지정 회차의 TOP100·본인 주변 5명·본인 순위를 동일 공동 순위 규칙으로 반환한다.
        /// </summary>
        public Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.RaidRankRes>> RankAsync(global::ThreeKingdoms.Shared.Types.RaidRankReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default)
        {
            return _client.PostAsync<global::ThreeKingdoms.Shared.Types.RaidRankReq, global::ThreeKingdoms.Shared.Types.RaidRankRes>(new Rest.RestEndpoint("/client/private/raid/rank", true, new Rest.RestHeaderRequirement[] {  }), request, options, cancellationToken);
        }
        /// <summary>
        /// 레이드 결과 수령 확인
        /// 스케줄러가 한 번 지급한 시즌 포인트를 확인한다. 재호출로 포인트를 다시 지급하지 않는다.
        /// </summary>
        public Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.RaidClaimRes>> ClaimAsync(global::ThreeKingdoms.Shared.Types.RaidClaimReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default)
        {
            return _client.PostAsync<global::ThreeKingdoms.Shared.Types.RaidClaimReq, global::ThreeKingdoms.Shared.Types.RaidClaimRes>(new Rest.RestEndpoint("/client/private/raid/claim", true, new Rest.RestHeaderRequirement[] {  }), request, options, cancellationToken);
        }
    }
}
