// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Services
{
    public interface ICastleService
    {
        /// <summary>
        /// 영지 로비 정보
        /// 현재 서버 시각까지 영지 생산을 확정하고 전체 영지 스냅샷을 반환한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/lobby")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleSnapshotDto>> LobbyAsync(global::ThreeKingdoms.Shared.Types.CastleLobbyReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 건물 무장 배치/해제
        /// 한 건물의 무장 배치를 요청 순서의 전체 상태로 교체하고 최신 영지 스냅샷을 반환한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/building/set-characters")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleSnapshotDto>> BuildingSetCharactersAsync(global::ThreeKingdoms.Shared.Types.CastleSetCharactersReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 농지/시장 재화 수령
        /// 시장 또는 농지의 적립 생산물을 수령하고 최신 영지·재화 상태를 반환한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/building/collect")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleCollectRes>> BuildingCollectAsync(global::ThreeKingdoms.Shared.Types.CastleCollectReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 도둑 포획 시도
        /// 현재 도둑 instance를 tap해 포획을 판정하고 성공 시 경과 시간을 반영한 재화를 반환한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/thief/capture")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleThiefCaptureRes>> ThiefCaptureAsync(global::ThreeKingdoms.Shared.Types.CastleThiefCaptureReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 도둑 디버프 해제
        /// 해제 시각까지 감소된 생산을 정산하고 농지·시장의 정상 효율을 복원한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/thief/clear-debuff")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleThiefClearDebuffRes>> ThiefClearDebuffAsync(global::ThreeKingdoms.Shared.Types.CastleThiefClearDebuffReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 건물 증축 로비 정보
        /// 진행 중 건물별 상태·남은 시간, 현재 단축 효율과 광고 일일 사용량을 반환한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/building/upgrade/lobby")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleBuildingUpgradeLobbyDto>> BuildingUpgradeLobbyAsync(global::ThreeKingdoms.Shared.Types.CastleBuildingUpgradeLobbyReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 건물 증축 시작
        /// 목표 한 단계의 궁성/건물 선행조건과 배치 능력치를 검증하고 독립 증축을 시작한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/building/upgrade/start")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleBuildingUpgradeStartRes>> BuildingUpgradeStartAsync(global::ThreeKingdoms.Shared.Types.CastleBuildingUpgradeStartReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 건물 증축 시간석 단축
        /// 현재 궁성 매력 효율로 필요한 수량까지만 시간석을 차감하고 완료되면 생산 경계를 함께 정산한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/building/upgrade/shorten")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleBuildingUpgradeShortenRes>> BuildingUpgradeShortenAsync(global::ThreeKingdoms.Shared.Types.CastleBuildingUpgradeShortenReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 건물 증축 광고 단축
        /// 광고 완료 후 계정별 일일 상한 안에서 현재 궁성 레벨의 광고 단축 시간을 적용한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/building/upgrade/complete-ad")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleBuildingUpgradeCompleteAdRes>> BuildingUpgradeCompleteAdAsync(global::ThreeKingdoms.Shared.Types.CastleBuildingUpgradeCompleteAdReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 관아 파견 로비 정보
        /// 현재 offer3개·진행/완료 회차·보상 수령 가능 횟수·관아 경험치와 레벨을 반환한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/office/lobby")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleOfficeLobbyDto>> OfficeLobbyAsync(global::ThreeKingdoms.Shared.Types.CastleOfficeLobbyReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 관아 파견 시작
        /// 현재 offer와 무장 중복을 검증하고 결과·보상 snapshot을 고정하되 횟수는 보상 수령까지 차감하지 않는다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/office/start")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleOfficeStartRes>> OfficeStartAsync(global::ThreeKingdoms.Shared.Types.CastleOfficeStartReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 관아 파견 보상 수령
        /// 완료된 파견의 보상·관아 경험치/레벨·횟수1회 차감·원장·receipt를 원자적으로 확정한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/office/claim")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleOfficeClaimRes>> OfficeClaimAsync(global::ThreeKingdoms.Shared.Types.CastleOfficeClaimReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 관아 파견 목록 갱신
        /// 진행 중 파견은 유지하고 군량1000을 차감해 미사용 offer3개를 모두 교체한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/castle/office/refresh")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.CastleOfficeRefreshRes>> OfficeRefreshAsync(global::ThreeKingdoms.Shared.Types.CastleOfficeLobbyReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
    }
}
