// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Services
{
    public interface IDailyDungeonService
    {
        /// <summary>
        /// 요일던전 로비 정보
        /// 오늘 도전 가능한 보스, 남은 횟수, 광고 사용량과 보스별 최고 처치 기록을 조회한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/daily-dungeon/lobby")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.DailyDungeonLobbyDto>> LobbyAsync(global::ThreeKingdoms.Shared.Types.DailyDungeonLobbyReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 요일던전 입장
        /// 횟수 차감 없이 선택한 보스로 새 도전을 시작하며, 보상 수령 시 1회를 차감한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/daily-dungeon/enter")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.DailyDungeonEnterRes>> EnterAsync(global::ThreeKingdoms.Shared.Types.DailyDungeonBossReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 요일던전 광고 추가 횟수
        /// 광고 완료 시 일일 광고 상한 안에서 통합 입장 가능 횟수를1회 추가한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/daily-dungeon/complete-ad")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.DailyDungeonCompleteAdRes>> CompleteAdAsync(global::ThreeKingdoms.Shared.Types.DailyDungeonCompleteAdReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 요일던전 결과 정산
        /// 처치 완료 등급과 남은 HP로 보상을 지급하고 최고 기록과 입장 횟수1회 차감을 함께 확정한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/daily-dungeon/finish")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.DailyDungeonRewardRes>> FinishAsync(global::ThreeKingdoms.Shared.Types.DailyDungeonFinishReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 요일던전 토벌
        /// 공유 횟수1회를 소비해 해당 보스의 최고 처치 등급까지 누적 보상을 즉시 받는다.
        /// </summary>
        [Attributes.PostMethod("/client/private/daily-dungeon/sweep")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.DailyDungeonRewardRes>> SweepAsync(global::ThreeKingdoms.Shared.Types.DailyDungeonBossReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
    }
}
