// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Services
{
    public interface IGuideQuestService
    {
        /// <summary>
        /// 가이드 퀘스트 로비 정보
        /// 현재 발행 회차를 조회하며 미초기화 계정은 첫 학습 또는 반복 퀘스트를 한 번 발행한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/guide-quest/lobby")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.GuideQuestLobbyDto>> LobbyAsync(global::ThreeKingdoms.Shared.Types.GuideQuestLobbyReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 가이드 퀘스트 보상 수령
        /// 현재 회차 완료를 인정하고 보상 지급·완료 이력·다음 회차 발행을 한 transaction에서 확정한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/guide-quest/claim")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.GuideQuestClaimRes>> ClaimAsync(global::ThreeKingdoms.Shared.Types.GuideQuestClaimReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
    }
}
