// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Services
{
    public interface IItemService
    {
        /// <summary>
        /// 주머니·랜덤박스 개봉
        /// 보유 container를 차감하고 서버 추첨 결과·보상·원장·절대 잔액을 한 transaction에서 확정한다.
        /// </summary>
        [Attributes.PostMethod("/client/private/item/open-container")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<OpenItemContainerRes>> OpenContainerAsync(OpenItemContainerReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
    }
}
