// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Services
{
    public interface IPublicService
    {
        /// <summary>
        /// 로그인
        /// Firebase 익명·소셜 로그인 (ID token 검증 → 동일 Firebase UID의 게임 계정 조회/자동 가입)
        /// </summary>
        [Attributes.PostMethod("/client/public/login")]
        Cysharp.Threading.Tasks.UniTask<CommonBody<global::ThreeKingdoms.Shared.Types.LoginRes>> LoginAsync(global::ThreeKingdoms.Shared.Types.LoginReq request, Rest.RestRequestOptions options, System.Threading.CancellationToken cancellationToken = default);
    }
}
