// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 사용자가 현재 보유한 전체 재화 잔액 스냅샷.
    /// </summary>
    public class AssetDto
    {
        /// <summary>
        /// 재화가 변경될 때 증가하는 버전. BIGINT 정밀도 보존을 위해 10진 문자열로 전달한다.
        /// </summary>
        [JsonProperty("revision", NullValueHandling = NullValueHandling.Include)]
        public string Revision { get; set; } = default!;

        /// <summary>
        /// 현재 보유 군량 수량.
        /// </summary>
        [JsonProperty("rice", NullValueHandling = NullValueHandling.Include)]
        public long Rice { get; set; } = default!;

        /// <summary>
        /// 현재 보유 무료 금화 수량.
        /// </summary>
        [JsonProperty("free_gold", NullValueHandling = NullValueHandling.Include)]
        public long FreeGold { get; set; } = default!;

        /// <summary>
        /// 현재 보유 유료 금화 수량.
        /// </summary>
        [JsonProperty("paid_gold", NullValueHandling = NullValueHandling.Include)]
        public long PaidGold { get; set; } = default!;

        /// <summary>
        /// 현재 보유 시간석 수량.
        /// </summary>
        [JsonProperty("time_stone", NullValueHandling = NullValueHandling.Include)]
        public long TimeStone { get; set; } = default!;

        /// <summary>
        /// 시즌이 변경되어도 유지되는 토너먼트 포인트.
        /// </summary>
        [JsonProperty("tournament_point", NullValueHandling = NullValueHandling.Include)]
        public long TournamentPoint { get; set; } = default!;

    }
}
