// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 도둑 포획 판정과 반환 재화 적용 결과.
    /// </summary>
    public class CastleThiefCaptureRes
    {
        /// <summary>
        /// 같은 x-request-id 재시도에 재사용되는 서버 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 이 tap의 포획 판정 결과.
        /// </summary>
        [JsonProperty("captured", NullValueHandling = NullValueHandling.Include)]
        public bool Captured { get; set; } = default!;

        /// <summary>
        /// tap 결과까지 반영한 전체 영지 상태.
        /// </summary>
        [JsonProperty("castle", NullValueHandling = NullValueHandling.Include)]
        public CastleSnapshotDto Castle { get; set; } = default!;

        /// <summary>
        /// 자연 회복과 반환 재화까지 반영한 절대 잔액.
        /// </summary>
        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public AssetDto Asset { get; set; } = default!;

        /// <summary>
        /// rice, free_gold 순서의 실제 양수 지급분.
        /// </summary>
        [JsonProperty("rewards", NullValueHandling = NullValueHandling.Include)]
        public List<CastleThiefRewardDto> Rewards { get; set; } = default!;

    }
}
