// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 한 건물의 무장 배치를 요청 순서 그대로 전체 교체한다.
    /// </summary>
    public class CastleSetCharactersReq
    {
        /// <summary>
        /// 배치를 바꿀 s_building.idx 숫자 ID.
        /// </summary>
        [JsonProperty("building_id", NullValueHandling = NullValueHandling.Include)]
        public long BuildingId { get; set; } = default!;

        /// <summary>
        /// 0-based slot 순서의 보유 무장 ID 전체 목록. 빈 배열은 모두 해제한다.
        /// </summary>
        [JsonProperty("character_ids", NullValueHandling = NullValueHandling.Include)]
        public List<long> CharacterIds { get; set; } = default!;

        /// <summary>
        /// 마지막으로 확인한 영지 revision의 10진 문자열.
        /// </summary>
        [JsonProperty("expected_castle_revision", NullValueHandling = NullValueHandling.Include)]
        public string ExpectedCastleRevision { get; set; } = default!;

    }
}
