// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 현재 출현한 도둑을 포획 시도한다.
    /// </summary>
    public class CastleThiefCaptureReq
    {
        /// <summary>
        /// 마지막 lobby에서 받은 active.thief_instance_id.
        /// </summary>
        [JsonProperty("thief_instance_id", NullValueHandling = NullValueHandling.Include)]
        public string ThiefInstanceId { get; set; } = default!;

    }
}
