// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleThiefRewardDto
    {
        /// <summary>
        /// 농지 군량 또는 시장 무료 금화.
        /// </summary>
        [JsonProperty("currency", NullValueHandling = NullValueHandling.Include)]
        public UserAssetType Currency { get; set; } = default!;

        /// <summary>
        /// 경과 비율을 반영해 최종 floor한 지급 수량.
        /// </summary>
        [JsonProperty("amount", NullValueHandling = NullValueHandling.Include)]
        public long Amount { get; set; } = default!;

    }
}
