// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleBuildingUpgradeShortenRes
    {
        /// <summary>
        /// 시간석 단축 처리·원장·receipt가 공유하는 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        [JsonProperty("used_time_stone_count", NullValueHandling = NullValueHandling.Include)]
        public long UsedTimeStoneCount { get; set; } = default!;

        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public AssetDto Asset { get; set; } = default!;

        [JsonProperty("castle", NullValueHandling = NullValueHandling.Include)]
        public CastleSnapshotDto Castle { get; set; } = default!;

        [JsonProperty("building_upgrade", NullValueHandling = NullValueHandling.Include)]
        public CastleBuildingUpgradeLobbyDto BuildingUpgrade { get; set; } = default!;

    }
}
