// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleOfficeStartReq
    {
        /// <summary>
        /// 직전 office/lobby에서 받은 시작 대상 offer UUID.
        /// </summary>
        [JsonProperty("offer_id", NullValueHandling = NullValueHandling.Include)]
        public string OfferId { get; set; } = default!;

        /// <summary>
        /// 1명 이상, 보유 무장 중 다른 파견에 참여하지 않은 ID.
        /// </summary>
        [JsonProperty("character_ids", NullValueHandling = NullValueHandling.Include)]
        public List<long> CharacterIds { get; set; } = default!;

    }
}
