// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleBuildingUpgradeDto
    {
        [JsonProperty("building_id", NullValueHandling = NullValueHandling.Include)]
        public long BuildingId { get; set; } = default!;

        /// <summary>
        /// building_id와 같은 s_building 행의 stable key.
        /// </summary>
        [JsonProperty("building_key", NullValueHandling = NullValueHandling.Include)]
        public string BuildingKey { get; set; } = default!;

        [JsonProperty("current_level", NullValueHandling = NullValueHandling.Include)]
        public long CurrentLevel { get; set; } = default!;

        [JsonProperty("target_level", NullValueHandling = NullValueHandling.Include)]
        public long TargetLevel { get; set; } = default!;

        /// <summary>
        /// 증축 시간 진행 중 또는 조건 미충족 일시 정지.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Include)]
        public CastleBuildingUpgradeStatus Status { get; set; } = default!;

        /// <summary>
        /// state_at 기준 올림한 남은 초.
        /// </summary>
        [JsonProperty("remaining_seconds", NullValueHandling = NullValueHandling.Include)]
        public long RemainingSeconds { get; set; } = default!;

        /// <summary>
        /// running이면 예상 UTC 완료시각, paused이면 null.
        /// </summary>
        [JsonProperty("completes_at", NullValueHandling = NullValueHandling.Include)]
        public string? CompletesAt { get; set; } = default!;

        /// <summary>
        /// 시작 duration을 고정한 table hash.
        /// </summary>
        [JsonProperty("started_table_version", NullValueHandling = NullValueHandling.Include)]
        public string StartedTableVersion { get; set; } = default!;

        /// <summary>
        /// 이 증축을 최초 시작한 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("started_at", NullValueHandling = NullValueHandling.Include)]
        public string StartedAt { get; set; } = default!;

    }
}
