// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 한 시점의 전체 영지 상태. 별도 목록·상세 조회 없이 영지 action 응답에서 재사용한다.
    /// </summary>
    public class CastleSnapshotDto
    {
        /// <summary>
        /// 계산에 사용한 tracked table_data 세대의 SHA-256.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 실제 영지 상태 변경마다 증가하는 BIGINT 문자열.
        /// </summary>
        [JsonProperty("revision", NullValueHandling = NullValueHandling.Include)]
        public string Revision { get; set; } = default!;

        /// <summary>
        /// 이 snapshot을 확정한 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("server_time", NullValueHandling = NullValueHandling.Include)]
        public string ServerTime { get; set; } = default!;

        /// <summary>
        /// building_id 오름차순의 6개 건물.
        /// </summary>
        [JsonProperty("buildings", NullValueHandling = NullValueHandling.Include)]
        public List<CastleBuildingDto> Buildings { get; set; } = default!;

        /// <summary>
        /// 도둑 출현·디버프와 다음 전이 시각.
        /// </summary>
        [JsonProperty("thief", NullValueHandling = NullValueHandling.Include)]
        public CastleThiefSnapshotDto Thief { get; set; } = default!;

    }
}
