// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleOfficeRewardDto
    {
        [JsonProperty("item_id", NullValueHandling = NullValueHandling.Include)]
        public long ItemId { get; set; } = default!;

        /// <summary>
        /// item_id와 같은 s_item 행의 stable key.
        /// </summary>
        [JsonProperty("item_key", NullValueHandling = NullValueHandling.Include)]
        public string ItemKey { get; set; } = default!;

        [JsonProperty("amount", NullValueHandling = NullValueHandling.Include)]
        public long Amount { get; set; } = default!;

    }
}
