// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 도둑 출현·디버프와 다음 서버 판정 시각.
    /// </summary>
    public class CastleThiefSnapshotDto
    {
        /// <summary>
        /// 출현 중인 도둑. 없으면 null.
        /// </summary>
        [JsonProperty("active", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.CastleThiefActiveDto? Active { get; set; } = default!;

        /// <summary>
        /// active가 없을 때 다음 등장 판정이 가능한 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("next_spawn_check_at", NullValueHandling = NullValueHandling.Include)]
        public string? NextSpawnCheckAt { get; set; } = default!;

        /// <summary>
        /// 농지·시장 생산량과 보유 한도 감소 적용 여부.
        /// </summary>
        [JsonProperty("debuff_active", NullValueHandling = NullValueHandling.Include)]
        public bool DebuffActive { get; set; } = default!;

        /// <summary>
        /// debuff_active일 때의 0~1 감소율. 미적용은 null.
        /// </summary>
        [JsonProperty("debuff_rate", NullValueHandling = NullValueHandling.Include)]
        public double? DebuffRate { get; set; } = default!;

        /// <summary>
        /// active면 expires_at, waiting이면 next_spawn_check_at.
        /// </summary>
        [JsonProperty("next_transition_at", NullValueHandling = NullValueHandling.Include)]
        public string NextTransitionAt { get; set; } = default!;

    }
}
