// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 시장 또는 농지에 현재 적립된 생산물을 수령한다.
    /// </summary>
    public class CastleCollectReq
    {
        /// <summary>
        /// 수령할 시장 또는 농지의 s_building.idx 숫자 ID.
        /// </summary>
        [JsonProperty("building_id", NullValueHandling = NullValueHandling.Include)]
        public long BuildingId { get; set; } = default!;

    }
}
