// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 현재 출현한 도둑의 서버 권위 시간 상태. 좌표와 이동은 클라이언트가 결정한다.
    /// </summary>
    public class CastleThiefActiveDto
    {
        /// <summary>
        /// 이전 도둑에 대한 stale tap을 구분하는 UUID.
        /// </summary>
        [JsonProperty("thief_instance_id", NullValueHandling = NullValueHandling.Include)]
        public string ThiefInstanceId { get; set; } = default!;

        /// <summary>
        /// 갈취와 유지 시간이 시작된 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("spawned_at", NullValueHandling = NullValueHandling.Include)]
        public string SpawnedAt { get; set; } = default!;

        /// <summary>
        /// 이 시각 이전에 포획해야 하는 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("expires_at", NullValueHandling = NullValueHandling.Include)]
        public string ExpiresAt { get; set; } = default!;

    }
}
