// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleBuildingUpgradeLobbyDto
    {
        /// <summary>
        /// 현재 증축 계산에 사용한 table hash.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 남은 시간과 완료 여부를 판정한 서버 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("state_at", NullValueHandling = NullValueHandling.Include)]
        public string StateAt { get; set; } = default!;

        /// <summary>
        /// 공용 리셋 시각과 서버 시간대를 적용한 광고 사용 게임 날짜.
        /// </summary>
        [JsonProperty("game_date", NullValueHandling = NullValueHandling.Include)]
        public string GameDate { get; set; } = default!;

        /// <summary>
        /// 광고 일일 횟수 계산에 사용하는 서버 시간대.
        /// </summary>
        [JsonProperty("time_zone", NullValueHandling = NullValueHandling.Include)]
        public string TimeZone { get; set; } = default!;

        /// <summary>
        /// s_parameter DAILY_RESET_TIME의 HH:MM 값.
        /// </summary>
        [JsonProperty("reset_time", NullValueHandling = NullValueHandling.Include)]
        public string ResetTime { get; set; } = default!;

        [JsonProperty("palace_level", NullValueHandling = NullValueHandling.Include)]
        public long PalaceLevel { get; set; } = default!;

        /// <summary>
        /// 현재 궁성 매력 충족률까지 적용한 1개 단축 초.
        /// </summary>
        [JsonProperty("save_seconds_per_time_stone", NullValueHandling = NullValueHandling.Include)]
        public long SaveSecondsPerTimeStone { get; set; } = default!;

        /// <summary>
        /// 현재 궁성 레벨의 광고 1회 단축 초. 매력 보정은 적용하지 않는다.
        /// </summary>
        [JsonProperty("save_seconds_per_ad", NullValueHandling = NullValueHandling.Include)]
        public long SaveSecondsPerAd { get; set; } = default!;

        /// <summary>
        /// 해당 게임 날짜에 성공한 건물 증축 광고 단축 횟수.
        /// </summary>
        [JsonProperty("ad_used_count", NullValueHandling = NullValueHandling.Include)]
        public long AdUsedCount { get; set; } = default!;

        /// <summary>
        /// 건물 증축 광고 단축의 계정별 일일 상한.
        /// </summary>
        [JsonProperty("ad_limit", NullValueHandling = NullValueHandling.Include)]
        public long AdLimit { get; set; } = default!;

        [JsonProperty("upgrades", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.CastleBuildingUpgradeDto> Upgrades { get; set; } = default!;

    }
}
