// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleOfficeLobbyDto
    {
        /// <summary>
        /// 현재 파견 규칙과 offer를 계산한 table hash.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 파견 상태 변경마다 증가하는 BIGINT 문자열.
        /// </summary>
        [JsonProperty("revision", NullValueHandling = NullValueHandling.Include)]
        public string Revision { get; set; } = default!;

        /// <summary>
        /// 완료 여부를 판정한 서버 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("state_at", NullValueHandling = NullValueHandling.Include)]
        public string StateAt { get; set; } = default!;

        /// <summary>
        /// 일일 횟수를 계산한 YYYY-MM-DD 게임 날짜.
        /// </summary>
        [JsonProperty("game_date", NullValueHandling = NullValueHandling.Include)]
        public string GameDate { get; set; } = default!;

        /// <summary>
        /// game_date 계산에 사용한 서버 시간대.
        /// </summary>
        [JsonProperty("time_zone", NullValueHandling = NullValueHandling.Include)]
        public string TimeZone { get; set; } = default!;

        /// <summary>
        /// 공용 DAILY_RESET_TIME의 HH:MM 값.
        /// </summary>
        [JsonProperty("reset_time", NullValueHandling = NullValueHandling.Include)]
        public string ResetTime { get; set; } = default!;

        [JsonProperty("level", NullValueHandling = NullValueHandling.Include)]
        public long Level { get; set; } = default!;

        [JsonProperty("xp", NullValueHandling = NullValueHandling.Include)]
        public long Xp { get; set; } = default!;

        [JsonProperty("next_level_xp", NullValueHandling = NullValueHandling.Include)]
        public long? NextLevelXp { get; set; } = default!;

        /// <summary>
        /// 보상 수령 시 차감할 현재 횟수.
        /// </summary>
        [JsonProperty("remaining_count", NullValueHandling = NullValueHandling.Include)]
        public long RemainingCount { get; set; } = default!;

        /// <summary>
        /// 항상 3개인 현재 미사용 목록.
        /// </summary>
        [JsonProperty("offers", NullValueHandling = NullValueHandling.Include)]
        public List<CastleOfficeOfferDto> Offers { get; set; } = default!;

        /// <summary>
        /// 진행·완료 후 미수령 파견.
        /// </summary>
        [JsonProperty("runs", NullValueHandling = NullValueHandling.Include)]
        public List<CastleOfficeRunDto> Runs { get; set; } = default!;

        [JsonProperty("refresh_cost_rice", NullValueHandling = NullValueHandling.Include)]
        public long RefreshCostRice { get; set; } = default!;

    }
}
