// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 영지 생산물 수령 결과와 그 시점의 최신 영지·재화 상태.
    /// </summary>
    public class CastleCollectRes
    {
        /// <summary>
        /// 서버가 생성한 수령 처리 UUID. 같은 x-request-id 재시도에는 같은 값이 반환된다.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 생산량 초기화와 revision 증가까지 반영한 전체 영지 상태.
        /// </summary>
        [JsonProperty("castle", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.CastleSnapshotDto Castle { get; set; } = default!;

        /// <summary>
        /// 이번에 수령한 재화. 농지는 Rice, 시장은 FreeGold다.
        /// </summary>
        [JsonProperty("collected_currency", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.UserAssetType CollectedCurrency { get; set; } = default!;

        /// <summary>
        /// 자연 재생 선정산과 생산물 지급까지 반영한 재화 절대 상태.
        /// </summary>
        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.AssetDto Asset { get; set; } = default!;

    }
}
