// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleOfficeClaimReq
    {
        /// <summary>
        /// office/lobby에서 완료 상태로 확인한 파견 run UUID.
        /// </summary>
        [JsonProperty("run_id", NullValueHandling = NullValueHandling.Include)]
        public string RunId { get; set; } = default!;

    }
}
