// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleThiefClearDebuffRes
    {
        /// <summary>
        /// 같은 x-request-id 재시도에 재사용되는 서버 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 해제 시각까지 정산한 최신 영지 상태.
        /// </summary>
        [JsonProperty("castle", NullValueHandling = NullValueHandling.Include)]
        public CastleSnapshotDto Castle { get; set; } = default!;

    }
}
