// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleOfficeRefreshRes
    {
        /// <summary>
        /// offer 전체 갱신 처리와 receipt가 공유하는 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        [JsonProperty("rice_cost", NullValueHandling = NullValueHandling.Include)]
        public long RiceCost { get; set; } = default!;

        [JsonProperty("office", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.CastleOfficeLobbyDto Office { get; set; } = default!;

        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.AssetDto Asset { get; set; } = default!;

    }
}
