// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 영지 건물이 요구하는 고유 능력치와 현재 배치 충족 상태.
    /// </summary>
    public class CastleRequirementDto
    {
        /// <summary>
        /// s_building.stat_type_1/2의 실제 요구 능력치 종류. None은 포함하지 않는다.
        /// RequirementStatType: StatType.Leadership | StatType.Strength | StatType.Intellect | StatType.Politics | StatType.Charisma
        /// </summary>
        [JsonProperty("stat_type", NullValueHandling = NullValueHandling.Include)]
        public StatType StatType { get; set; } = default!;

        /// <summary>
        /// 배치된 무장의 현재 합산 능력치. scale 6 고정 소수 문자열.
        /// </summary>
        [JsonProperty("current_value", NullValueHandling = NullValueHandling.Include)]
        public string CurrentValue { get; set; } = default!;

        /// <summary>
        /// 궁성 부족 보정까지 반영된 요구 능력치. scale 6 고정 소수 문자열.
        /// </summary>
        [JsonProperty("required_value", NullValueHandling = NullValueHandling.Include)]
        public string RequiredValue { get; set; } = default!;

        /// <summary>
        /// 현재 충족률 0~1. scale 6 고정 소수 문자열.
        /// </summary>
        [JsonProperty("fulfillment_rate", NullValueHandling = NullValueHandling.Include)]
        public string FulfillmentRate { get; set; } = default!;

    }
}
