// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleOfficeRunDto
    {
        /// <summary>
        /// 목록 생성마다 새로 발급하는 offer UUID.
        /// </summary>
        [JsonProperty("offer_id", NullValueHandling = NullValueHandling.Include)]
        public string OfferId { get; set; } = default!;

        /// <summary>
        /// s_office_mission.idx.
        /// </summary>
        [JsonProperty("mission_id", NullValueHandling = NullValueHandling.Include)]
        public long MissionId { get; set; } = default!;

        /// <summary>
        /// s_office_mission.key.
        /// </summary>
        [JsonProperty("mission_key", NullValueHandling = NullValueHandling.Include)]
        public string MissionKey { get; set; } = default!;

        /// <summary>
        /// 파견 임무 등급.
        /// </summary>
        [JsonProperty("mission_grade", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.MissionGrade MissionGrade { get; set; } = default!;

        /// <summary>
        /// 달성률 계산에 사용할 실제 능력치 종류. None은 포함하지 않는다.
        /// RequirementStatType: StatType.Leadership | StatType.Strength | StatType.Intellect | StatType.Politics | StatType.Charisma
        /// </summary>
        [JsonProperty("stat_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.StatType StatType { get; set; } = default!;

        /// <summary>
        /// 시작 후 완료까지 서버가 고정할 기본 시간.
        /// </summary>
        [JsonProperty("duration_seconds", NullValueHandling = NullValueHandling.Include)]
        public long DurationSeconds { get; set; } = default!;

        /// <summary>
        /// 달성률100%에 필요한 core 능력치 합.
        /// </summary>
        [JsonProperty("required_stat_value", NullValueHandling = NullValueHandling.Include)]
        public long RequiredStatValue { get; set; } = default!;

        /// <summary>
        /// 보상 수령 시 지급할 관아 경험치.
        /// </summary>
        [JsonProperty("office_xp_reward", NullValueHandling = NullValueHandling.Include)]
        public long OfficeXpReward { get; set; } = default!;

        /// <summary>
        /// offer를 만든 table hash.
        /// </summary>
        [JsonProperty("issued_table_version", NullValueHandling = NullValueHandling.Include)]
        public string IssuedTableVersion { get; set; } = default!;

        /// <summary>
        /// 시작할 때 새로 만든 파견 UUID.
        /// </summary>
        [JsonProperty("run_id", NullValueHandling = NullValueHandling.Include)]
        public string RunId { get; set; } = default!;

        /// <summary>
        /// 이번 파견에 사용 중인 보유 무장 ID.
        /// </summary>
        [JsonProperty("character_ids", NullValueHandling = NullValueHandling.Include)]
        public List<long> CharacterIds { get; set; } = default!;

        /// <summary>
        /// 시작 시 고정한 0~1 달성률.
        /// </summary>
        [JsonProperty("achievement_rate", NullValueHandling = NullValueHandling.Include)]
        public double AchievementRate { get; set; } = default!;

        /// <summary>
        /// 파견을 시작한 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("started_at", NullValueHandling = NullValueHandling.Include)]
        public string StartedAt { get; set; } = default!;

        /// <summary>
        /// 보상 수령 가능 상태가 되는 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("completes_at", NullValueHandling = NullValueHandling.Include)]
        public string CompletesAt { get; set; } = default!;

        /// <summary>
        /// lobby의 state_at 기준 완료 여부.
        /// </summary>
        [JsonProperty("is_completed", NullValueHandling = NullValueHandling.Include)]
        public bool IsCompleted { get; set; } = default!;

    }
}
