// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleOfficeOfferDto
    {
        /// <summary>
        /// 목록 생성마다 새로 발급하는 offer UUID.
        /// </summary>
        [JsonProperty("offer_id", NullValueHandling = NullValueHandling.Include)]
        public string OfferId { get; set; } = default!;

        /// <summary>
        /// s_office_mission.idx.
        /// </summary>
        [JsonProperty("mission_id", NullValueHandling = NullValueHandling.Include)]
        public long MissionId { get; set; } = default!;

        /// <summary>
        /// s_office_mission.key.
        /// </summary>
        [JsonProperty("mission_key", NullValueHandling = NullValueHandling.Include)]
        public string MissionKey { get; set; } = default!;

        /// <summary>
        /// 파견 임무 등급.
        /// </summary>
        [JsonProperty("mission_grade", NullValueHandling = NullValueHandling.Include)]
        public MissionGrade MissionGrade { get; set; } = default!;

        /// <summary>
        /// 달성률 계산에 사용할 실제 능력치 종류. None은 포함하지 않는다.
        /// RequirementStatType: StatType.Leadership | StatType.Strength | StatType.Intellect | StatType.Politics | StatType.Charisma
        /// </summary>
        [JsonProperty("stat_type", NullValueHandling = NullValueHandling.Include)]
        public StatType StatType { get; set; } = default!;

        /// <summary>
        /// 시작 후 완료까지 서버가 고정할 기본 시간.
        /// </summary>
        [JsonProperty("duration_seconds", NullValueHandling = NullValueHandling.Include)]
        public long DurationSeconds { get; set; } = default!;

        /// <summary>
        /// 달성률100%에 필요한 core 능력치 합.
        /// </summary>
        [JsonProperty("required_stat_value", NullValueHandling = NullValueHandling.Include)]
        public long RequiredStatValue { get; set; } = default!;

        /// <summary>
        /// 보상 수령 시 지급할 관아 경험치.
        /// </summary>
        [JsonProperty("office_xp_reward", NullValueHandling = NullValueHandling.Include)]
        public long OfficeXpReward { get; set; } = default!;

        /// <summary>
        /// offer를 만든 table hash.
        /// </summary>
        [JsonProperty("issued_table_version", NullValueHandling = NullValueHandling.Include)]
        public string IssuedTableVersion { get; set; } = default!;

    }
}
