// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleBuildingUpgradeShortenReq
    {
        [JsonProperty("building_id", NullValueHandling = NullValueHandling.Include)]
        public long BuildingId { get; set; } = default!;

        /// <summary>
        /// 실제 남은 시간에 필요한 개수보다 크면 필요한 개수만 사용한다.
        /// </summary>
        [JsonProperty("time_stone_count", NullValueHandling = NullValueHandling.Include)]
        public long TimeStoneCount { get; set; } = default!;

    }
}
