// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleBuildingUpgradeCompleteAdRes
    {
        /// <summary>
        /// 이번 광고 완료 처리 UUID. 같은 요청 ID 재전송은 같은 결과를 반환한다.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 광고 단축으로 완료될 수 있는 최신 영지 상태.
        /// </summary>
        [JsonProperty("castle", NullValueHandling = NullValueHandling.Include)]
        public CastleSnapshotDto Castle { get; set; } = default!;

        /// <summary>
        /// 광고 횟수와 단축 결과를 반영한 증축 상태.
        /// </summary>
        [JsonProperty("building_upgrade", NullValueHandling = NullValueHandling.Include)]
        public CastleBuildingUpgradeLobbyDto BuildingUpgrade { get; set; } = default!;

    }
}
