// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleOfficeRewardDto
    {
        [JsonProperty("item_id", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ItemKey ItemId { get; set; } = default!;

        [JsonProperty("amount", NullValueHandling = NullValueHandling.Include)]
        public long Amount { get; set; } = default!;

    }
}
