// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleBuildingUpgradeStartRes
    {
        /// <summary>
        /// 증축 시작 처리와 receipt가 공유하는 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        [JsonProperty("building_upgrade", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.CastleBuildingUpgradeLobbyDto BuildingUpgrade { get; set; } = default!;

    }
}
