// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 시장·농지의 마지막 서버 정산 상태와 표시용 생산 기준.
    /// </summary>
    public class CastleProductionDto
    {
        /// <summary>
        /// 농지는 Rice, 시장은 FreeGold다.
        /// </summary>
        [JsonProperty("currency", NullValueHandling = NullValueHandling.Include)]
        public UserAssetType Currency { get; set; } = default!;

        /// <summary>
        /// 아직 수령하지 않은 적립량. scale 9 고정 소수 문자열.
        /// </summary>
        [JsonProperty("production_amount", NullValueHandling = NullValueHandling.Include)]
        public string ProductionAmount { get; set; } = default!;

        /// <summary>
        /// 초당 생산량. scale 6 고정 소수 문자열.
        /// </summary>
        [JsonProperty("production_per_seconds", NullValueHandling = NullValueHandling.Include)]
        public string ProductionPerSeconds { get; set; } = default!;

        /// <summary>
        /// 현재 생산 보유 한도. scale 6 고정 소수 문자열.
        /// </summary>
        [JsonProperty("storage_cap", NullValueHandling = NullValueHandling.Include)]
        public string StorageCap { get; set; } = default!;

        /// <summary>
        /// production_amount를 마지막으로 확정한 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("settled_at", NullValueHandling = NullValueHandling.Include)]
        public string SettledAt { get; set; } = default!;

    }
}
