// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 영지 건물 한 개의 서버 권위 상태.
    /// </summary>
    public class CastleBuildingDto
    {
        /// <summary>
        /// s_building.idx 숫자 ID.
        /// </summary>
        [JsonProperty("building_id", NullValueHandling = NullValueHandling.Include)]
        public long BuildingId { get; set; } = default!;

        /// <summary>
        /// 같은 s_building row의 영구 key.
        /// </summary>
        [JsonProperty("building_key", NullValueHandling = NullValueHandling.Include)]
        public string BuildingKey { get; set; } = default!;

        /// <summary>
        /// 현재 완료된 건물 레벨.
        /// </summary>
        [JsonProperty("level", NullValueHandling = NullValueHandling.Include)]
        public long Level { get; set; } = default!;

        /// <summary>
        /// 이번 서버 단계에서 건물 무장 배치를 지원하는지 여부.
        /// </summary>
        [JsonProperty("assignment_enabled", NullValueHandling = NullValueHandling.Include)]
        public bool AssignmentEnabled { get; set; } = default!;

        /// <summary>
        /// 이번 서버 단계에서 이 건물 효과를 계산하는지 여부.
        /// </summary>
        [JsonProperty("effect_enabled", NullValueHandling = NullValueHandling.Include)]
        public bool EffectEnabled { get; set; } = default!;

        /// <summary>
        /// slot_index 오름차순의 배치 무장 ID 목록.
        /// </summary>
        [JsonProperty("assigned_character_ids", NullValueHandling = NullValueHandling.Include)]
        public List<long> AssignedCharacterIds { get; set; } = default!;

        /// <summary>
        /// stat_type_1 뒤 stat_type_2 순서이며 None은 제외한다.
        /// </summary>
        [JsonProperty("requirements", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.CastleRequirementDto> Requirements { get; set; } = default!;

        /// <summary>
        /// 시장·농지만 생산 상태가 있고 다른 건물은 null이다.
        /// </summary>
        [JsonProperty("production", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.CastleProductionDto? Production { get; set; } = default!;

    }
}
