// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CastleOfficeClaimRes
    {
        /// <summary>
        /// 보상 지급 원장과 receipt가 공유하는 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 이번에 보상 수령을 완료한 파견 run UUID.
        /// </summary>
        [JsonProperty("run_id", NullValueHandling = NullValueHandling.Include)]
        public string RunId { get; set; } = default!;

        [JsonProperty("rewards", NullValueHandling = NullValueHandling.Include)]
        public List<CastleOfficeRewardDto> Rewards { get; set; } = default!;

        [JsonProperty("office", NullValueHandling = NullValueHandling.Include)]
        public CastleOfficeLobbyDto Office { get; set; } = default!;

        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public AssetDto Asset { get; set; } = default!;

        [JsonProperty("item_updates", NullValueHandling = NullValueHandling.Include)]
        public List<ItemStackDto> ItemUpdates { get; set; } = default!;

        [JsonProperty("character_snapshot", NullValueHandling = NullValueHandling.Include)]
        public CharacterSnapshotDto? CharacterSnapshot { get; set; } = default!;

    }
}
