// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 무장의 잠기지 않은 모든 특성을 재추첨한다.
    /// </summary>
    public class CharacterRerollTraitsReq
    {
        /// <summary>
        /// 보유 무장 ID.
        /// </summary>
        [JsonProperty("character_id", NullValueHandling = NullValueHandling.Include)]
        public long CharacterId { get; set; } = default!;

    }
}
