// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 열린 특성 슬롯의 잠금 상태를 지정한다.
    /// </summary>
    public class CharacterSetTraitLockReq
    {
        /// <summary>
        /// 보유 무장 ID.
        /// </summary>
        [JsonProperty("character_id", NullValueHandling = NullValueHandling.Include)]
        public long CharacterId { get; set; } = default!;

        /// <summary>
        /// 열린 슬롯 번호 0~2.
        /// </summary>
        [JsonProperty("slot_index", NullValueHandling = NullValueHandling.Include)]
        public int SlotIndex { get; set; } = default!;

        /// <summary>
        /// 적용할 잠금 상태.
        /// </summary>
        [JsonProperty("is_locked", NullValueHandling = NullValueHandling.Include)]
        public bool IsLocked { get; set; } = default!;

    }
}
