// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 승급으로 열린 특성 슬롯의 서버 저장 상태.
    /// </summary>
    public class CharacterTraitStateDto
    {
        /// <summary>
        /// 특성 슬롯 0~2.
        /// </summary>
        [JsonProperty("slot_index", NullValueHandling = NullValueHandling.Include)]
        public int SlotIndex { get; set; } = default!;

        /// <summary>
        /// s_traits_pool.key.
        /// </summary>
        [JsonProperty("trait_key", NullValueHandling = NullValueHandling.Include)]
        public string TraitKey { get; set; } = default!;

        /// <summary>
        /// 추첨된 수치 등급.
        /// </summary>
        [JsonProperty("trait_value_grade", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.TraitsValueGrade TraitValueGrade { get; set; } = default!;

        /// <summary>
        /// 기획 수치의 자리 번호(0,1,2)를 key로 보존.
        /// </summary>
        [JsonProperty("values", NullValueHandling = NullValueHandling.Include)]
        public Dictionary<string, int> Values { get; set; } = default!;

        /// <summary>
        /// 재추첨 보호 여부.
        /// </summary>
        [JsonProperty("is_locked", NullValueHandling = NullValueHandling.Include)]
        public bool IsLocked { get; set; } = default!;

    }
}
