// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 보유 무장의 다음 성장 단계에 한 번 도전하는 요청.
    /// </summary>
    public class CharacterGrowReq
    {
        /// <summary>
        /// 성장시킬 보유 무장의 s_character.idx 숫자 ID.
        /// </summary>
        [JsonProperty("character_id", NullValueHandling = NullValueHandling.Include)]
        public long CharacterId { get; set; } = default!;

    }
}
