// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 현재 조건으로 새 직책 해금을 반영하고 전체 직책 정보를 반환한다.
    /// </summary>
    public class CharacterPositionSyncRes
    {
        /// <summary>
        /// 판정에 사용한 기획 테이블 버전.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 직책 ID 순의 전체 목록. 새 해금도 저장된 상태다.
        /// </summary>
        [JsonProperty("positions", NullValueHandling = NullValueHandling.Include)]
        public List<CharacterPositionDto> Positions { get; set; } = default!;

    }
}
