// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 현재 클라이언트 계산 순서로 등급·성장·보너스를 반영한 최종 전투 능력치.
    /// </summary>
    public class CharacterCombatStatsDto
    {
        /// <summary>
        /// 최종 공격력.
        /// </summary>
        [JsonProperty("attack_power", NullValueHandling = NullValueHandling.Include)]
        public double AttackPower { get; set; } = default!;

        /// <summary>
        /// 최종 방어력.
        /// </summary>
        [JsonProperty("defence", NullValueHandling = NullValueHandling.Include)]
        public double Defence { get; set; } = default!;

        /// <summary>
        /// 정수 절삭까지 반영한 최대 체력.
        /// </summary>
        [JsonProperty("health_max", NullValueHandling = NullValueHandling.Include)]
        public long HealthMax { get; set; } = default!;

        /// <summary>
        /// 초당 공격 횟수.
        /// </summary>
        [JsonProperty("attack_speed", NullValueHandling = NullValueHandling.Include)]
        public double AttackSpeed { get; set; } = default!;

        /// <summary>
        /// 최종 이동속도.
        /// </summary>
        [JsonProperty("move_speed", NullValueHandling = NullValueHandling.Include)]
        public double MoveSpeed { get; set; } = default!;

        /// <summary>
        /// 치명타 확률의 최종 비율. 0.1은 10%다.
        /// </summary>
        [JsonProperty("critical_rate", NullValueHandling = NullValueHandling.Include)]
        public double CriticalRate { get; set; } = default!;

        /// <summary>
        /// 치명타 피해 배율.
        /// </summary>
        [JsonProperty("critical_damage", NullValueHandling = NullValueHandling.Include)]
        public double CriticalDamage { get; set; } = default!;

        /// <summary>
        /// 재사용 시간 감소의 최종 비율.
        /// </summary>
        [JsonProperty("cooldown_rate", NullValueHandling = NullValueHandling.Include)]
        public double CooldownRate { get; set; } = default!;

        /// <summary>
        /// 흡혈의 최종 비율.
        /// </summary>
        [JsonProperty("life_steal", NullValueHandling = NullValueHandling.Include)]
        public double LifeSteal { get; set; } = default!;

        /// <summary>
        /// 보스 추가 피해의 최종 비율.
        /// </summary>
        [JsonProperty("boss_damage", NullValueHandling = NullValueHandling.Include)]
        public double BossDamage { get; set; } = default!;

    }
}
