// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 현재 테이블 버전을 기준으로 구성한 사용자의 전체 보유 무장 스냅샷.
    /// </summary>
    public class CharacterSnapshotDto
    {
        /// <summary>
        /// 영혼석 등 현재 보유 stack. 없는 item은 보유량0이며 0행의 버전도 유지한다.
        /// </summary>
        [JsonProperty("items", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.ItemStackDto> Items { get; set; } = default!;

        /// <summary>
        /// 계정이 보유한 보물과 현재 장착 순서.
        /// </summary>
        [JsonProperty("treasures", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.TreasureStateDto> Treasures { get; set; } = default!;

        /// <summary>
        /// 이 스냅샷 계산에 사용한 table_hash의 64자리 SHA-256 값.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 기본 표시용으로 사용할 최초 획득 무장 ID. 보유 무장이 없으면 null이다.
        /// </summary>
        [JsonProperty("bootstrap_character_id", NullValueHandling = NullValueHandling.Include)]
        public long? BootstrapCharacterId { get; set; } = default!;

        /// <summary>
        /// 획득 시각이 빠른 순서로 정렬된 전체 보유 무장 상태.
        /// </summary>
        [JsonProperty("characters", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.CharacterStateDto> Characters { get; set; } = default!;

    }
}
