// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class CharacterSetPositionRes
    {
        /// <summary>
        /// 중복 요청에도 유지되는 이번 처리 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 처리에 사용한 기획 테이블 버전.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 이번 처리 후의 전체 직책 상태.
        /// </summary>
        [JsonProperty("positions", NullValueHandling = NullValueHandling.Include)]
        public List<CharacterPositionDto> Positions { get; set; } = default!;

        /// <summary>
        /// 직책 변경과 전투 스탯·CP를 반영한 전체 무장 스냅샷.
        /// </summary>
        [JsonProperty("character_snapshot", NullValueHandling = NullValueHandling.Include)]
        public CharacterSnapshotDto CharacterSnapshot { get; set; } = default!;

    }
}
