// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 보유 무장을 원하는 상위 등급까지 수동 승급한다.
    /// </summary>
    public class CharacterAscendReq
    {
        /// <summary>
        /// 보유 무장 ID.
        /// </summary>
        [JsonProperty("character_id", NullValueHandling = NullValueHandling.Include)]
        public long CharacterId { get; set; } = default!;

        /// <summary>
        /// 도달할 등급 Elite~Legend. 현재보다 높은 등급이어야 한다.
        /// AscendTargetGrade: CharacterGrade.Elite | CharacterGrade.General | CharacterGrade.Hero | CharacterGrade.Legend
        /// </summary>
        [JsonProperty("target_grade", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.CharacterGrade TargetGrade { get; set; } = default!;

    }
}
