// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 무장 특성 재추첨 후 전체 전투 상태와 군량.
    /// </summary>
    public class CharacterRerollTraitsRes
    {
        /// <summary>
        /// 서버 처리 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 요청 테이블 버전.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 특성·CP를 반영한 전체 무장 상태.
        /// </summary>
        [JsonProperty("character_snapshot", NullValueHandling = NullValueHandling.Include)]
        public CharacterSnapshotDto CharacterSnapshot { get; set; } = default!;

        /// <summary>
        /// 비용 차감 후 재화 절대 상태.
        /// </summary>
        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public AssetDto Asset { get; set; } = default!;

        /// <summary>
        /// 영지 생산 능력에 영향이 있으면 갱신된 영지 버전.
        /// </summary>
        [JsonProperty("castle_revision", NullValueHandling = NullValueHandling.Include)]
        public string? CastleRevision { get; set; } = default!;

    }
}
