// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 직책을 한 무장에게 장착하거나 명시적으로 해제한다.
    /// </summary>
    public class CharacterSetPositionReq
    {
        /// <summary>
        /// 설정할 s_position.idx.
        /// </summary>
        [JsonProperty("position_id", NullValueHandling = NullValueHandling.Include)]
        public long PositionId { get; set; } = default!;

        /// <summary>
        /// 장착할 보유 무장 ID. null이면 해당 직책을 해제한다.
        /// </summary>
        [JsonProperty("character_id", NullValueHandling = NullValueHandling.Include)]
        public long? CharacterId { get; set; } = default!;

    }
}
