// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 계정 공용 직책의 해금·장착·조건 진행 정보. 정적 효과와 조건 설명은 s_position을 함께 사용한다.
    /// </summary>
    public class CharacterPositionDto
    {
        /// <summary>
        /// s_position.idx.
        /// </summary>
        [JsonProperty("position_id", NullValueHandling = NullValueHandling.Include)]
        public long PositionId { get; set; } = default!;

        /// <summary>
        /// s_position.key.
        /// </summary>
        [JsonProperty("position_key", NullValueHandling = NullValueHandling.Include)]
        public string PositionKey { get; set; } = default!;

        /// <summary>
        /// 해금 완료, 조건 미충족, 실제 진행 기록 연결 전을 구분한다.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Include)]
        public CharacterPositionStatus Status { get; set; } = default!;

        /// <summary>
        /// 현재 이 직책을 장착한 무장 ID. 미장착이면 null이다.
        /// </summary>
        [JsonProperty("character_id", NullValueHandling = NullValueHandling.Include)]
        public long? CharacterId { get; set; } = default!;

        /// <summary>
        /// 저장된 직책 상태 버전. 아직 해금되지 않아 저장 행이 없으면 null이다.
        /// </summary>
        [JsonProperty("revision", NullValueHandling = NullValueHandling.Include)]
        public string? Revision { get; set; } = default!;

        /// <summary>
        /// 해금 조건의 현재 인원/레벨/횟수. 실제 기록을 확인할 수 없으면 null이다.
        /// </summary>
        [JsonProperty("unlock_current", NullValueHandling = NullValueHandling.Include)]
        public string? UnlockCurrent { get; set; } = default!;

        /// <summary>
        /// 기획표의 해금 기준값. 무조건 해금은0이다.
        /// </summary>
        [JsonProperty("unlock_required", NullValueHandling = NullValueHandling.Include)]
        public long UnlockRequired { get; set; } = default!;

        /// <summary>
        /// 해금과 장착 조건을 충족한 보유 무장 ID 목록.
        /// </summary>
        [JsonProperty("eligible_character_ids", NullValueHandling = NullValueHandling.Include)]
        public List<long> EligibleCharacterIds { get; set; } = default!;

    }
}
