// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 영혼석 차감과 신규 특성 슬롯까지 반영한 승급 결과.
    /// </summary>
    public class CharacterAscendRes
    {
        /// <summary>
        /// 서버가 발급한 처리 UUID. 재시도는 같은 결과를 반환한다.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 비용과 영혼석 metadata 판정에 사용한 테이블 버전.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 등급·특성·인연·CP를 갱신한 전체 무장 상태.
        /// </summary>
        [JsonProperty("character_snapshot", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.CharacterSnapshotDto CharacterSnapshot { get; set; } = default!;

        /// <summary>
        /// 이번에 차감된 stack의 절대 잔액과 버전.
        /// </summary>
        [JsonProperty("item_updates", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.ItemStackDto> ItemUpdates { get; set; } = default!;

        /// <summary>
        /// 영지에 배치된 무장의 능력 변경이 반영된 영지 버전.
        /// </summary>
        [JsonProperty("castle_revision", NullValueHandling = NullValueHandling.Include)]
        public string? CastleRevision { get; set; } = default!;

    }
}
