// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 무장 성장 1회의 판정과 변경된 무장·재화 상태.
    /// </summary>
    public class CharacterGrowRes
    {
        /// <summary>
        /// 서버가 생성한 성장 처리 UUID. 같은 x-request-id 재시도에는 같은 값이 반환된다.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 서버가 검증하고 성장 계산에 사용한 요청의 테이블 버전.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 성장 성공·실패와 성장 포인트가 반영된 전체 무장 상태.
        /// </summary>
        [JsonProperty("character_snapshot", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.CharacterSnapshotDto CharacterSnapshot { get; set; } = default!;

        /// <summary>
        /// 성공 여부와 관계없이 비용이 반영된 재화 절대 상태.
        /// </summary>
        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.AssetDto Asset { get; set; } = default!;

        /// <summary>
        /// 이번 성장 시도의 최종 판정.
        /// </summary>
        [JsonProperty("growth_result", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.CharacterGrowthResult GrowthResult { get; set; } = default!;

        /// <summary>
        /// 이번 성장으로 영지 cache가 무효화됐으면 새 revision, 아니면 null.
        /// </summary>
        [JsonProperty("castle_revision", NullValueHandling = NullValueHandling.Include)]
        public string? CastleRevision { get; set; } = default!;

    }
}
