// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>성공 응답 봉투. HTTP 전송 구현은 code가 SUCCESS인지 먼저 확인한 뒤 Data를 T로 읽는다.</summary>
    public sealed class CommonBody<T>
    {
        [JsonProperty("code", NullValueHandling = NullValueHandling.Include)] public string Code { get; set; } = default!;
        private T? _data;
        [JsonIgnore] public bool DataSpecified { get; private set; }
        [JsonProperty("data", NullValueHandling = NullValueHandling.Include)] public T? Data { get => _data; set { _data = value; DataSpecified = true; } }
        public bool ShouldSerializeData() => DataSpecified;
    }
    /// <summary>business/transport/system 오류. Data를 성공 DTO로 강제 변환하지 않는다.</summary>
    public sealed class ApiErrorBody
    {
        [JsonProperty("code", NullValueHandling = NullValueHandling.Include)] public string Code { get; set; } = default!;
        private Newtonsoft.Json.Linq.JToken? _data;
        [JsonIgnore] public bool DataSpecified { get; private set; }
        [JsonProperty("data", NullValueHandling = NullValueHandling.Include)] public Newtonsoft.Json.Linq.JToken? Data { get => _data; set { _data = value; DataSpecified = true; } }
        public bool ShouldSerializeData() => DataSpecified;
        private string? _requestId;
        [JsonIgnore] public bool RequestIdSpecified { get; private set; }
        [JsonProperty("request_id", NullValueHandling = NullValueHandling.Include)] public string? RequestId { get => _requestId; set { _requestId = value; RequestIdSpecified = true; } }
        public bool ShouldSerializeRequestId() => RequestIdSpecified;
    }
}
