// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 세 콘텐츠 상점의 현재 카탈로그·진열·구매한도와 행상 적용 상태.
    /// </summary>
    public class ContentShopLobbyDto
    {
        /// <summary>
        /// 진열과 가격 계산에 사용한 table hash.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 일일 진열 세대 버전. 해당 날짜 진열을 새로 만들 때 증가한다.
        /// </summary>
        [JsonProperty("revision", NullValueHandling = NullValueHandling.Include)]
        public string Revision { get; set; } = default!;

        /// <summary>
        /// 구매 가능 상태를 확정한 서버 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("state_at", NullValueHandling = NullValueHandling.Include)]
        public string StateAt { get; set; } = default!;

        /// <summary>
        /// 일일 진열·구매한도 기준 YYYY-MM-DD 날짜.
        /// </summary>
        [JsonProperty("game_date", NullValueHandling = NullValueHandling.Include)]
        public string GameDate { get; set; } = default!;

        /// <summary>
        /// game_date 계산에 사용한 서버 시간대.
        /// </summary>
        [JsonProperty("time_zone", NullValueHandling = NullValueHandling.Include)]
        public string TimeZone { get; set; } = default!;

        /// <summary>
        /// 공용 DAILY_RESET_TIME의 HH:MM 값.
        /// </summary>
        [JsonProperty("reset_time", NullValueHandling = NullValueHandling.Include)]
        public string ResetTime { get; set; } = default!;

        [JsonProperty("merchant_level", NullValueHandling = NullValueHandling.Include)]
        public long MerchantLevel { get; set; } = default!;

        [JsonProperty("merchant_discount_rate", NullValueHandling = NullValueHandling.Include)]
        public double MerchantDiscountRate { get; set; } = default!;

        [JsonProperty("merchant_grade_up_rate", NullValueHandling = NullValueHandling.Include)]
        public double MerchantGradeUpRate { get; set; } = default!;

        [JsonProperty("shops", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.ContentShopDto> Shops { get; set; } = default!;

    }
}
