// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 콘텐츠 상점의 상품 하나와 현재 사용자의 구매 상태.
    /// </summary>
    public class ContentShopProductDto
    {
        /// <summary>
        /// 소속 shop 안의 상품 numeric idx.
        /// </summary>
        [JsonProperty("product_id", NullValueHandling = NullValueHandling.Include)]
        public long ProductId { get; set; } = default!;

        /// <summary>
        /// 지급할 concrete s_item.idx.
        /// </summary>
        [JsonProperty("reward_item_id", NullValueHandling = NullValueHandling.Include)]
        public long RewardItemId { get; set; } = default!;

        /// <summary>
        /// 표시와 지급 검증에 사용할 s_item.key.
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;

        /// <summary>
        /// 1개 구매 단위당 지급 수량.
        /// </summary>
        [JsonProperty("reward_count", NullValueHandling = NullValueHandling.Include)]
        public long RewardCount { get; set; } = default!;

        /// <summary>
        /// 결제에 사용하는 기획 재화 종류.
        /// </summary>
        [JsonProperty("pay_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.PayType PayType { get; set; } = default!;

        /// <summary>
        /// 행상 할인까지 확정한 1개당 결제 가격.
        /// </summary>
        [JsonProperty("unit_price", NullValueHandling = NullValueHandling.Include)]
        public long UnitPrice { get; set; } = default!;

        /// <summary>
        /// -1이면 영구 무제한, 양수이면 period 내 한도.
        /// </summary>
        [JsonProperty("buy_limit", NullValueHandling = NullValueHandling.Include)]
        public long BuyLimit { get; set; } = default!;

        /// <summary>
        /// 현재 period에서 이미 구매한 수량.
        /// </summary>
        [JsonProperty("bought_count", NullValueHandling = NullValueHandling.Include)]
        public long BoughtCount { get; set; } = default!;

        /// <summary>
        /// 무제한이면 null, 아니면 추가 구매 가능 수량.
        /// </summary>
        [JsonProperty("remaining_count", NullValueHandling = NullValueHandling.Include)]
        public long? RemainingCount { get; set; } = default!;

        /// <summary>
        /// 작은 값부터 표시한다.
        /// </summary>
        [JsonProperty("display_order", NullValueHandling = NullValueHandling.Include)]
        public long DisplayOrder { get; set; } = default!;

    }
}
