// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class ContentShopDto
    {
        /// <summary>
        /// Daily(1)·Raid(2)·Tournament(3) 상점 타입.
        /// </summary>
        [JsonProperty("shop_type", NullValueHandling = NullValueHandling.Include)]
        public ContentShopType ShopType { get; set; } = default!;

        /// <summary>
        /// 상점 탭 표시 순서.
        /// </summary>
        [JsonProperty("display_order", NullValueHandling = NullValueHandling.Include)]
        public long DisplayOrder { get; set; } = default!;

        /// <summary>
        /// 현재 서버 범위에서 구매 가능한지 여부. 접근 표시는 client가 결정한다.
        /// </summary>
        [JsonProperty("purchase_enabled", NullValueHandling = NullValueHandling.Include)]
        public bool PurchaseEnabled { get; set; } = default!;

        /// <summary>
        /// 일일은 확정 진열, 포인트 상점은 활성 고정 카탈로그.
        /// </summary>
        [JsonProperty("products", NullValueHandling = NullValueHandling.Include)]
        public List<ContentShopProductDto> Products { get; set; } = default!;

    }
}
