// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class ContentShopBuyRes
    {
        /// <summary>
        /// 구매 지급 원장과 receipt가 공유하는 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 실제 구매한 상점 타입.
        /// </summary>
        [JsonProperty("shop_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ContentShopType ShopType { get; set; } = default!;

        /// <summary>
        /// 구매 직후 갱신된 한도 상태.
        /// </summary>
        [JsonProperty("product", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.ContentShopProductDto Product { get; set; } = default!;

        /// <summary>
        /// 이번에 구매한 수량.
        /// </summary>
        [JsonProperty("quantity", NullValueHandling = NullValueHandling.Include)]
        public long Quantity { get; set; } = default!;

        /// <summary>
        /// 할인과 수량을 적용한 실제 결제 총액.
        /// </summary>
        [JsonProperty("total_price", NullValueHandling = NullValueHandling.Include)]
        public long TotalPrice { get; set; } = default!;

        /// <summary>
        /// 수량을 적용한 실제 지급 총수량.
        /// </summary>
        [JsonProperty("total_reward_count", NullValueHandling = NullValueHandling.Include)]
        public long TotalRewardCount { get; set; } = default!;

        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.AssetDto Asset { get; set; } = default!;

        [JsonProperty("item_updates", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.ItemStackDto> ItemUpdates { get; set; } = default!;

        [JsonProperty("character_snapshot", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.CharacterSnapshotDto? CharacterSnapshot { get; set; } = default!;

    }
}
