// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class ContentShopBuyReq
    {
        /// <summary>
        /// 구매할 상점 타입. Daily(1)·Raid(2)·Tournament(3).
        /// </summary>
        [JsonProperty("shop_type", NullValueHandling = NullValueHandling.Include)]
        public ContentShopType ShopType { get; set; } = default!;

        /// <summary>
        /// 같은 shop_type의 content-shop/lobby에서 받은 상품 ID.
        /// </summary>
        [JsonProperty("product_id", NullValueHandling = NullValueHandling.Include)]
        public long ProductId { get; set; } = default!;

        /// <summary>
        /// 한 번에 구매할 수량. 1 이상이며 남은 구매한도 이하여야 한다.
        /// </summary>
        [JsonProperty("quantity", NullValueHandling = NullValueHandling.Include)]
        public long Quantity { get; set; } = default!;

    }
}
