// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 서버가 보관하는 정산 대상 입장 정보. 전투 진행도 복원 데이터는 포함하지 않는다.
    /// </summary>
    public class DailyDungeonActiveEntryDto
    {
        /// <summary>
        /// 단일 active 입장의 event UUID.
        /// </summary>
        [JsonProperty("entry_event_id", NullValueHandling = NullValueHandling.Include)]
        public string EntryEventId { get; set; } = default!;

        /// <summary>
        /// 입장할 때 선택한 보스 ID.
        /// </summary>
        [JsonProperty("boss_id", NullValueHandling = NullValueHandling.Include)]
        public long BossId { get; set; } = default!;

        /// <summary>
        /// 전투를 시작한 게임 날짜 YYYY-MM-DD. 횟수는 보상 수령 날짜에 차감한다.
        /// </summary>
        [JsonProperty("game_date", NullValueHandling = NullValueHandling.Include)]
        public string GameDate { get; set; } = default!;

        /// <summary>
        /// 입장 시각, UTC ISO 8601.
        /// </summary>
        [JsonProperty("started_at", NullValueHandling = NullValueHandling.Include)]
        public string StartedAt { get; set; } = default!;

        /// <summary>
        /// 입장 시 고정된 보상표 버전.
        /// </summary>
        [JsonProperty("reward_table_version", NullValueHandling = NullValueHandling.Include)]
        public string RewardTableVersion { get; set; } = default!;

    }
}
