// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 입장 성공 시 클라이언트가 새 전투를 시작할 정보.
    /// </summary>
    public class DailyDungeonEntryDto
    {
        /// <summary>
        /// 이 입장의 event UUID. finish의 entry_event_id로 전달한다.
        /// </summary>
        [JsonProperty("entry_event_id", NullValueHandling = NullValueHandling.Include)]
        public string EntryEventId { get; set; } = default!;

        /// <summary>
        /// 선택한 보스 ID.
        /// </summary>
        [JsonProperty("boss_id", NullValueHandling = NullValueHandling.Include)]
        public long BossId { get; set; } = default!;

        /// <summary>
        /// 전투 시작 날짜 YYYY-MM-DD. 횟수는 finish 보상 수령 날짜에 차감한다.
        /// </summary>
        [JsonProperty("game_date", NullValueHandling = NullValueHandling.Include)]
        public string GameDate { get; set; } = default!;

        /// <summary>
        /// 전투 시작 기준 서버 시각, UTC ISO 8601.
        /// </summary>
        [JsonProperty("started_at", NullValueHandling = NullValueHandling.Include)]
        public string StartedAt { get; set; } = default!;

        /// <summary>
        /// 한 도전의 기획 제한시간. 매번 일반 등급부터 시작한다.
        /// </summary>
        [JsonProperty("play_time_seconds", NullValueHandling = NullValueHandling.Include)]
        public long PlayTimeSeconds { get; set; } = default!;

    }
}
