// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 보스별 영구 최고 처치 완료 등급.
    /// </summary>
    public class DailyDungeonRecordDto
    {
        /// <summary>
        /// 요일던전 보스 ID.
        /// </summary>
        [JsonProperty("boss_id", NullValueHandling = NullValueHandling.Include)]
        public long BossId { get; set; } = default!;

        /// <summary>
        /// 처치 완료 등급. 해당 보스의 일반도 미처치면 null.
        /// </summary>
        [JsonProperty("highest_killed_grade", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.DungeonBossGrade? HighestKilledGrade { get; set; } = default!;

    }
}
