// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 입장과 토벌에서 선택할 요일던전 보스.
    /// </summary>
    public class DailyDungeonBossReq
    {
        /// <summary>
        /// s_daily_dungeon_boss.idx. 일요일은 매 요청마다 다른 보스를 선택할 수 있다.
        /// </summary>
        [JsonProperty("boss_id", NullValueHandling = NullValueHandling.Include)]
        public long BossId { get; set; } = default!;

    }
}
