// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 이번 정산으로 얻은 보상량. 보유 잔액과 구분한다.
    /// </summary>
    public class DailyDungeonRewardsDto
    {
        /// <summary>
        /// 해당 보스 클래스의 concrete 영혼석 s_item.idx.
        /// </summary>
        [JsonProperty("class_item_id", NullValueHandling = NullValueHandling.Include)]
        public long ClassItemId { get; set; } = default!;

        /// <summary>
        /// 이번 클래스 영혼석 지급량.
        /// </summary>
        [JsonProperty("soul_stone_count", NullValueHandling = NullValueHandling.Include)]
        public long SoulStoneCount { get; set; } = default!;

        /// <summary>
        /// 던전 군량 지급량. 자연회복량은 포함하지 않는다.
        /// </summary>
        [JsonProperty("rice", NullValueHandling = NullValueHandling.Include)]
        public long Rice { get; set; } = default!;

        /// <summary>
        /// 이번 금화 지급량.
        /// </summary>
        [JsonProperty("gold", NullValueHandling = NullValueHandling.Include)]
        public long Gold { get; set; } = default!;

        /// <summary>
        /// 이번 시간석 지급량.
        /// </summary>
        [JsonProperty("time_stone_count", NullValueHandling = NullValueHandling.Include)]
        public long TimeStoneCount { get; set; } = default!;

    }
}
