// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 현재 일일 횟수와 보스별 기록의 서버 확정 상태.
    /// </summary>
    public class DailyDungeonLobbyDto
    {
        /// <summary>
        /// 현재 조회에 사용한 서버 테이블 버전.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 요일던전 상태의 단조 증가 BIGINT 버전. 과거 응답으로 새 상태를 덮지 않는다.
        /// </summary>
        [JsonProperty("revision", NullValueHandling = NullValueHandling.Include)]
        public string Revision { get; set; } = default!;

        /// <summary>
        /// 잠금 획득 후 판정한 서버 시각, UTC ISO 8601.
        /// </summary>
        [JsonProperty("state_at", NullValueHandling = NullValueHandling.Include)]
        public string StateAt { get; set; } = default!;

        /// <summary>
        /// 공용 리셋 시각과 시간대를 적용한 게임 날짜 YYYY-MM-DD.
        /// </summary>
        [JsonProperty("game_date", NullValueHandling = NullValueHandling.Include)]
        public string GameDate { get; set; } = default!;

        /// <summary>
        /// 게임 날짜의 요일. 일0~토6.
        /// </summary>
        [JsonProperty("weekday", NullValueHandling = NullValueHandling.Include)]
        public int Weekday { get; set; } = default!;

        /// <summary>
        /// 공용 게임 날짜 시간대. 초기 Asia/Seoul.
        /// </summary>
        [JsonProperty("time_zone", NullValueHandling = NullValueHandling.Include)]
        public string TimeZone { get; set; } = default!;

        /// <summary>
        /// 공용 DAILY_RESET_TIME의 HH:MM 값.
        /// </summary>
        [JsonProperty("reset_time", NullValueHandling = NullValueHandling.Include)]
        public string ResetTime { get; set; } = default!;

        /// <summary>
        /// 기본·광고 구분 없이 공유하는 보상 수령 가능 횟수. 입장만으로는 줄지 않는다.
        /// </summary>
        [JsonProperty("remaining_count", NullValueHandling = NullValueHandling.Include)]
        public long RemainingCount { get; set; } = default!;

        /// <summary>
        /// 해당 게임 날짜에서 성공한 광고 완료 횟수.
        /// </summary>
        [JsonProperty("ad_used_count", NullValueHandling = NullValueHandling.Include)]
        public long AdUsedCount { get; set; } = default!;

        /// <summary>
        /// 기획테이블의 일일 광고 완료 상한.
        /// </summary>
        [JsonProperty("ad_limit", NullValueHandling = NullValueHandling.Include)]
        public long AdLimit { get; set; } = default!;

        /// <summary>
        /// 오늘 입장·토벌할 수 있는 보스 ID. 일요일에는 전체6종.
        /// </summary>
        [JsonProperty("available_boss_ids", NullValueHandling = NullValueHandling.Include)]
        public List<long> AvailableBossIds { get; set; } = default!;

        /// <summary>
        /// 보스 ID 순의 전체 최고 기록. 미처치는 null로 포함한다.
        /// </summary>
        [JsonProperty("records", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.DailyDungeonRecordDto> Records { get; set; } = default!;

        /// <summary>
        /// 현재 정산 가능한 입장. 새 입장 성공 시 대체한다.
        /// </summary>
        [JsonProperty("active_entry", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.DailyDungeonActiveEntryDto? ActiveEntry { get; set; } = default!;

    }
}
