// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class DailyDungeonEnterRes
    {
        /// <summary>
        /// 이번 입장 처리 UUID. entry.entry_event_id와 같은 값.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 횟수 차감 없이 새 입장만 반영된 상태.
        /// </summary>
        [JsonProperty("daily_dungeon", NullValueHandling = NullValueHandling.Include)]
        public DailyDungeonLobbyDto DailyDungeon { get; set; } = default!;

        /// <summary>
        /// 새 전투 시작 정보.
        /// </summary>
        [JsonProperty("entry", NullValueHandling = NullValueHandling.Include)]
        public DailyDungeonEntryDto Entry { get; set; } = default!;

    }
}
