// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 클라이언트 전투 결과. 보상 수량은 서버가 계산한다.
    /// </summary>
    public class DailyDungeonFinishReq
    {
        /// <summary>
        /// 입장 응답의 entry_event_id. 정산 요청의 x-request-id와 다르다.
        /// </summary>
        [JsonProperty("entry_event_id", NullValueHandling = NullValueHandling.Include)]
        public string EntryEventId { get; set; } = default!;

        /// <summary>
        /// 이번에 처치 완료한 등급. 일반도 미처치면 null, 진행 중 등급이 아니다.
        /// </summary>
        [JsonProperty("highest_killed_grade", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.DungeonBossGrade? HighestKilledGrade { get; set; } = default!;

        /// <summary>
        /// 진행 중 보스의 남은 HP를 양수 INT64 10진 문자열로 전달. 심연 처치 완료면 null.
        /// </summary>
        [JsonProperty("current_boss_hp", NullValueHandling = NullValueHandling.Include)]
        public string? CurrentBossHp { get; set; } = default!;

        /// <summary>
        /// 같은 보스의 최대 HP. 남은 HP 이상인 양수 INT64 문자열, 심연 처치 완료면 null.
        /// </summary>
        [JsonProperty("current_boss_max_hp", NullValueHandling = NullValueHandling.Include)]
        public string? CurrentBossMaxHp { get; set; } = default!;

    }
}
