// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 다음 무장 성장 1회에 적용될 비용·성공 확률·보정 정보.
    /// </summary>
    public class GrowthPreviewDto
    {
        /// <summary>
        /// 다음 성장 시도에 소비되는 군량 수량.
        /// </summary>
        [JsonProperty("cost_rice", NullValueHandling = NullValueHandling.Include)]
        public long CostRice { get; set; } = default!;

        /// <summary>
        /// 다음 성장 시도의 기본 성공 확률(0~1).
        /// </summary>
        [JsonProperty("success_rate", NullValueHandling = NullValueHandling.Include)]
        public double SuccessRate { get; set; } = default!;

        /// <summary>
        /// 실패 시 추가되는 성장 포인트. 소수 둘째 자리까지의 10진 문자열이다.
        /// </summary>
        [JsonProperty("fail_growth_point", NullValueHandling = NullValueHandling.Include)]
        public string FailGrowthPoint { get; set; } = default!;

        /// <summary>
        /// 현재 누적 성장 포인트로 다음 시도가 보장 성공인지 여부.
        /// </summary>
        [JsonProperty("is_guaranteed", NullValueHandling = NullValueHandling.Include)]
        public bool IsGuaranteed { get; set; } = default!;

    }
}
