// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class GuideQuestClaimRes
    {
        /// <summary>
        /// 보상 원장·receipt가 공유하는 처리 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 이번에 수령 완료한 발행 회차.
        /// </summary>
        [JsonProperty("claimed_issue_id", NullValueHandling = NullValueHandling.Include)]
        public string ClaimedIssueId { get; set; } = default!;

        /// <summary>
        /// 실제 지급한 s_item.idx.
        /// </summary>
        [JsonProperty("reward_item_id", NullValueHandling = NullValueHandling.Include)]
        public long RewardItemId { get; set; } = default!;

        /// <summary>
        /// 실제 지급한 보상 key.
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;

        /// <summary>
        /// 실제 지급한 수량.
        /// </summary>
        [JsonProperty("reward_amount", NullValueHandling = NullValueHandling.Include)]
        public long RewardAmount { get; set; } = default!;

        /// <summary>
        /// 수령 뒤 새로 발행된 다음 회차.
        /// </summary>
        [JsonProperty("guide_quest", NullValueHandling = NullValueHandling.Include)]
        public GuideQuestLobbyDto GuideQuest { get; set; } = default!;

        /// <summary>
        /// 지급 뒤 전체 재화 절대 잔액.
        /// </summary>
        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public AssetDto Asset { get; set; } = default!;

        /// <summary>
        /// 일반 item 보상이면 영향받은 절대 stack. 재화만 지급하면 빈 배열.
        /// </summary>
        [JsonProperty("item_updates", NullValueHandling = NullValueHandling.Include)]
        public List<ItemStackDto> ItemUpdates { get; set; } = default!;

        /// <summary>
        /// 무장·보물 획득이 발생한 item 보상이면 최신 상태.
        /// </summary>
        [JsonProperty("character_snapshot", NullValueHandling = NullValueHandling.Include)]
        public CharacterSnapshotDto? CharacterSnapshot { get; set; } = default!;

    }
}
