// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 서버가 발행한 가이드 퀘스트 한 회차의 고정 정보.
    /// </summary>
    public class GuideQuestIssueDto
    {
        /// <summary>
        /// 발행할 때마다 새로 만든 UUID. 같은 반복 퀘스트도 회차마다 다르다.
        /// </summary>
        [JsonProperty("issue_id", NullValueHandling = NullValueHandling.Include)]
        public string IssueId { get; set; } = default!;

        /// <summary>
        /// 학습 퀘스트 또는 반복 퀘스트.
        /// </summary>
        [JsonProperty("kind", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.GuideQuestKind Kind { get; set; } = default!;

        /// <summary>
        /// kind에 해당하는 기획 테이블의 numeric idx.
        /// </summary>
        [JsonProperty("quest_id", NullValueHandling = NullValueHandling.Include)]
        public long QuestId { get; set; } = default!;

        /// <summary>
        /// 클라이언트가 조건·화면을 연결할 stable key.
        /// </summary>
        [JsonProperty("quest_key", NullValueHandling = NullValueHandling.Include)]
        public string QuestKey { get; set; } = default!;

        /// <summary>
        /// 이 회차를 발행할 때 고정한 목표값.
        /// </summary>
        [JsonProperty("target_value", NullValueHandling = NullValueHandling.Include)]
        public long TargetValue { get; set; } = default!;

        /// <summary>
        /// 원본 navigation 문자열. 공란과 복합 경로를 그대로 전달한다.
        /// </summary>
        [JsonProperty("navigation", NullValueHandling = NullValueHandling.Include)]
        public string Navigation { get; set; } = default!;

        /// <summary>
        /// reward_item_key에 대응하는 s_item.idx.
        /// </summary>
        [JsonProperty("reward_item_id", NullValueHandling = NullValueHandling.Include)]
        public long RewardItemId { get; set; } = default!;

        /// <summary>
        /// 서버가 지급할 concrete 보상 key.
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;

        /// <summary>
        /// 서버가 지급할 보상 수량.
        /// </summary>
        [JsonProperty("reward_amount", NullValueHandling = NullValueHandling.Include)]
        public long RewardAmount { get; set; } = default!;

        /// <summary>
        /// 이 회차 내용을 만든 기획 테이블 hash.
        /// </summary>
        [JsonProperty("issued_table_version", NullValueHandling = NullValueHandling.Include)]
        public string IssuedTableVersion { get; set; } = default!;

        /// <summary>
        /// 서버 발행 시각 UTC ISO 8601.
        /// </summary>
        [JsonProperty("issued_at", NullValueHandling = NullValueHandling.Include)]
        public string IssuedAt { get; set; } = default!;

    }
}
