// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 가이드 퀘스트 로비의 현재 서버 권위 상태.
    /// </summary>
    public class GuideQuestLobbyDto
    {
        /// <summary>
        /// 기기 로컬 저장 없이 튜토리얼 완료 상태를 복원할 기획 quest idx 목록.
        /// </summary>
        [JsonProperty("completed_learning_quest_ids", NullValueHandling = NullValueHandling.Include)]
        public List<long> CompletedLearningQuestIds { get; set; } = default!;

        /// <summary>
        /// 현재 서버의 기획 테이블 hash.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 수령 성공마다 증가하는 사용자 가이드 상태 버전.
        /// </summary>
        [JsonProperty("revision", NullValueHandling = NullValueHandling.Include)]
        public string Revision { get; set; } = default!;

        /// <summary>
        /// 현재 클라이언트가 진행하고 수령할 단일 회차.
        /// </summary>
        [JsonProperty("issue", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.GuideQuestIssueDto Issue { get; set; } = default!;

    }
}
