// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 현재 발행 회차 완료와 보상 수령을 한 번에 요청한다.
    /// </summary>
    public class GuideQuestClaimReq
    {
        /// <summary>
        /// 로비 응답의 현재 issue_id.
        /// </summary>
        [JsonProperty("issue_id", NullValueHandling = NullValueHandling.Include)]
        public string IssueId { get; set; } = default!;

        /// <summary>
        /// 클라이언트가 보고하는 현재 도달 stage N-M. 초기 서버는 이 값을 신뢰한다.
        /// </summary>
        [JsonProperty("reached_stage", NullValueHandling = NullValueHandling.Include)]
        public string ReachedStage { get; set; } = default!;

    }
}
