// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 아이템 stack의 서버 확정 절대 잔액.
    /// </summary>
    public class ItemStackDto
    {
        /// <summary>
        /// s_item.idx에 대응하는 숫자 ID.
        /// </summary>
        [JsonProperty("item_id", NullValueHandling = NullValueHandling.Include)]
        public long ItemId { get; set; } = default!;

        /// <summary>
        /// s_item.key. 표시 이름은 string table에서 조회한다.
        /// </summary>
        [JsonProperty("item_key", NullValueHandling = NullValueHandling.Include)]
        public string ItemKey { get; set; } = default!;

        /// <summary>
        /// 처리 후 절대 보유량. 0이 된 stack도 버전을 보존한다.
        /// </summary>
        [JsonProperty("amount", NullValueHandling = NullValueHandling.Include)]
        public long Amount { get; set; } = default!;

        /// <summary>
        /// 해당 stack의 변경 버전. 더 오래된 응답은 적용하지 않는다.
        /// </summary>
        [JsonProperty("revision", NullValueHandling = NullValueHandling.Include)]
        public string Revision { get; set; } = default!;

    }
}
