// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// Firebase 익명·소셜 로그인. 앱 버전은 client-version HTTP header로 전달한다.
    /// </summary>
    public class LoginReq
    {
        private string _FirebaseToken = default!;
        [JsonIgnore] public bool FirebaseTokenSpecified { get; private set; }
        /// <summary>
        /// Firebase SDK에서 받은 ID token. 서버가 UID와 로그인 종류를 검증한다. 미전달 시 development 환경에서만 test_uid로 대신 로그인한다.
        /// </summary>
        [JsonProperty("firebase_token", NullValueHandling = NullValueHandling.Include)]
        public string FirebaseToken { get => _FirebaseToken; set { _FirebaseToken = value; FirebaseTokenSpecified = true; } }
        public bool ShouldSerializeFirebaseToken() => FirebaseTokenSpecified;

        private long _TestUid = default!;
        [JsonIgnore] public bool TestUidSpecified { get; private set; }
        /// <summary>
        /// DEV 전용 테스트 로그인. firebase_token이 없을 때 이 uid로 Firebase 검증 없이 같은 로그인 흐름을 탄다. 없는 uid는 요청한 번호 그대로 게스트 계정을 만들어 is_new_account=true로 응답한다. development 외 환경은 INVALID_REQUEST다.
        /// </summary>
        [JsonProperty("test_uid", NullValueHandling = NullValueHandling.Include)]
        public long TestUid { get => _TestUid; set { _TestUid = value; TestUidSpecified = true; } }
        public bool ShouldSerializeTestUid() => TestUidSpecified;

        /// <summary>
        /// 플랫폼 구분. 허용된 OsType 숫자만 전달한다.
        /// </summary>
        [JsonProperty("os_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.OsType OsType { get; set; } = default!;

        private string? _OsName = default!;
        [JsonIgnore] public bool OsNameSpecified { get; private set; }
        /// <summary>
        /// OS 이름, 최대 32자. 미전달/null은 미확인, 빈 문자열은 불가.
        /// </summary>
        [JsonProperty("os_name", NullValueHandling = NullValueHandling.Include)]
        public string? OsName { get => _OsName; set { _OsName = value; OsNameSpecified = true; } }
        public bool ShouldSerializeOsName() => OsNameSpecified;

        private string? _OsVersion = default!;
        [JsonIgnore] public bool OsVersionSpecified { get; private set; }
        /// <summary>
        /// OS 버전, 최대 64자. 미전달/null은 미확인, 빈 문자열은 불가.
        /// </summary>
        [JsonProperty("os_version", NullValueHandling = NullValueHandling.Include)]
        public string? OsVersion { get => _OsVersion; set { _OsVersion = value; OsVersionSpecified = true; } }
        public bool ShouldSerializeOsVersion() => OsVersionSpecified;

        private string _FcmToken = default!;
        [JsonIgnore] public bool FcmTokenSpecified { get; private set; }
        /// <summary>
        /// FCM 등록 토큰(1..255자). 전달 시 확인 시각 갱신, 미전달은 유지, null/빈 값 불가.
        /// </summary>
        [JsonProperty("fcm_token", NullValueHandling = NullValueHandling.Include)]
        public string FcmToken { get => _FcmToken; set { _FcmToken = value; FcmTokenSpecified = true; } }
        public bool ShouldSerializeFcmToken() => FcmTokenSpecified;

    }
}
