// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 로그인 성공 후 세션과 초기 사용자·재화 상태를 반환하는 응답. 무장 상태는 전용 조회 API에서 받는다.
    /// </summary>
    public class LoginRes
    {
        /// <summary>
        /// 새 session_key를 포함한 현재 계정·프로필 정보.
        /// </summary>
        [JsonProperty("user_info", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.UserInfoDto UserInfo { get; set; } = default!;

        /// <summary>
        /// 이번 로그인 요청에서 계정이 새로 생성됐는지 여부.
        /// </summary>
        [JsonProperty("is_new_account", NullValueHandling = NullValueHandling.Include)]
        public bool IsNewAccount { get; set; } = default!;

        /// <summary>
        /// 사용자가 현재 초기 지역을 선택한 상태인지 여부.
        /// </summary>
        [JsonProperty("region_selected", NullValueHandling = NullValueHandling.Include)]
        public bool RegionSelected { get; set; } = default!;

        /// <summary>
        /// 로그인 시점의 전체 재화 잔액.
        /// </summary>
        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.AssetDto Asset { get; set; } = default!;

    }
}
