// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class OpenItemContainerRewardDto
    {
        /// <summary>
        /// 추첨·고정 지급된 concrete s_item.idx.
        /// </summary>
        [JsonProperty("item_id", NullValueHandling = NullValueHandling.Include)]
        public long ItemId { get; set; } = default!;

        /// <summary>
        /// 표시용 stable item key.
        /// </summary>
        [JsonProperty("item_key", NullValueHandling = NullValueHandling.Include)]
        public string ItemKey { get; set; } = default!;

        /// <summary>
        /// 전체 개봉 결과를 item별로 합산한 수량.
        /// </summary>
        [JsonProperty("amount", NullValueHandling = NullValueHandling.Include)]
        public long Amount { get; set; } = default!;

    }
}
