// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class OpenItemContainerReq
    {
        /// <summary>
        /// 열 주머니 또는 랜덤박스 s_item.idx.
        /// </summary>
        [JsonProperty("item_id", NullValueHandling = NullValueHandling.Include)]
        public long ItemId { get; set; } = default!;

        /// <summary>
        /// 한 번에 열 수량. 서버 제한은 1~100개다.
        /// </summary>
        [JsonProperty("quantity", NullValueHandling = NullValueHandling.Include)]
        public long Quantity { get; set; } = default!;

    }
}
