// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class OpenItemContainerRes
    {
        /// <summary>
        /// 개봉 차감·지급 원장과 receipt가 공유하는 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        [JsonProperty("opened_item_id", NullValueHandling = NullValueHandling.Include)]
        public long OpenedItemId { get; set; } = default!;

        [JsonProperty("opened_quantity", NullValueHandling = NullValueHandling.Include)]
        public long OpenedQuantity { get; set; } = default!;

        [JsonProperty("rewards", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.OpenItemContainerRewardDto> Rewards { get; set; } = default!;

        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.AssetDto Asset { get; set; } = default!;

        [JsonProperty("item_updates", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.ItemStackDto> ItemUpdates { get; set; } = default!;

        [JsonProperty("character_snapshot", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.CharacterSnapshotDto? CharacterSnapshot { get; set; } = default!;

    }
}
