// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class RaidRoundDto
    {
        [JsonProperty("raid_id", NullValueHandling = NullValueHandling.Include)]
        public string RaidId { get; set; } = default!;

        [JsonProperty("season_id", NullValueHandling = NullValueHandling.Include)]
        public int SeasonId { get; set; } = default!;

        [JsonProperty("revision", NullValueHandling = NullValueHandling.Include)]
        public string Revision { get; set; } = default!;

        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        [JsonProperty("boss_character_id", NullValueHandling = NullValueHandling.Include)]
        public int BossCharacterId { get; set; } = default!;

        [JsonProperty("boss_key", NullValueHandling = NullValueHandling.Include)]
        public string BossKey { get; set; } = default!;

        [JsonProperty("difficulty", NullValueHandling = NullValueHandling.Include)]
        public int Difficulty { get; set; } = default!;

        [JsonProperty("phase", NullValueHandling = NullValueHandling.Include)]
        public string Phase { get; set; } = default!;

        [JsonProperty("starts_at", NullValueHandling = NullValueHandling.Include)]
        public string StartsAt { get; set; } = default!;

        [JsonProperty("ends_at", NullValueHandling = NullValueHandling.Include)]
        public string EndsAt { get; set; } = default!;

        [JsonProperty("phase_started_at", NullValueHandling = NullValueHandling.Include)]
        public string PhaseStartedAt { get; set; } = default!;

        [JsonProperty("transition_ends_at", NullValueHandling = NullValueHandling.Include)]
        public string? TransitionEndsAt { get; set; } = default!;

        [JsonProperty("remaining_milliseconds", NullValueHandling = NullValueHandling.Include)]
        public long RemainingMilliseconds { get; set; } = default!;

        [JsonProperty("hp", NullValueHandling = NullValueHandling.Include)]
        public string Hp { get; set; } = default!;

        [JsonProperty("max_hp", NullValueHandling = NullValueHandling.Include)]
        public string MaxHp { get; set; } = default!;

        [JsonProperty("normal_max_hp", NullValueHandling = NullValueHandling.Include)]
        public string NormalMaxHp { get; set; } = default!;

        [JsonProperty("jin_max_hp", NullValueHandling = NullValueHandling.Include)]
        public string JinMaxHp { get; set; } = default!;

        [JsonProperty("attack_power", NullValueHandling = NullValueHandling.Include)]
        public double AttackPower { get; set; } = default!;

        [JsonProperty("defence", NullValueHandling = NullValueHandling.Include)]
        public double Defence { get; set; } = default!;

        [JsonProperty("pattern_index", NullValueHandling = NullValueHandling.Include)]
        public int PatternIndex { get; set; } = default!;

        [JsonProperty("pattern_started_at", NullValueHandling = NullValueHandling.Include)]
        public string? PatternStartedAt { get; set; } = default!;

        [JsonProperty("pattern_interval_seconds", NullValueHandling = NullValueHandling.Include)]
        public int PatternIntervalSeconds { get; set; } = default!;

        [JsonProperty("participant_count", NullValueHandling = NullValueHandling.Include)]
        public int ParticipantCount { get; set; } = default!;

        [JsonProperty("can_join", NullValueHandling = NullValueHandling.Include)]
        public bool CanJoin { get; set; } = default!;

        [JsonProperty("settled", NullValueHandling = NullValueHandling.Include)]
        public bool Settled { get; set; } = default!;

    }
}
