// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class RaidParticipantDto
    {
        [JsonProperty("damage", NullValueHandling = NullValueHandling.Include)]
        public string Damage { get; set; } = default!;

        [JsonProperty("rank", NullValueHandling = NullValueHandling.Include)]
        public int Rank { get; set; } = default!;

        [JsonProperty("percentile", NullValueHandling = NullValueHandling.Include)]
        public double Percentile { get; set; } = default!;

        [JsonProperty("reward_points", NullValueHandling = NullValueHandling.Include)]
        public string? RewardPoints { get; set; } = default!;

        [JsonProperty("reward_claimed", NullValueHandling = NullValueHandling.Include)]
        public bool RewardClaimed { get; set; } = default!;

    }
}
