// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class RaidClaimRes
    {
        [JsonProperty("raid_id", NullValueHandling = NullValueHandling.Include)]
        public string RaidId { get; set; } = default!;

        [JsonProperty("reward_points", NullValueHandling = NullValueHandling.Include)]
        public string RewardPoints { get; set; } = default!;

        [JsonProperty("point_raid_balance", NullValueHandling = NullValueHandling.Include)]
        public string PointRaidBalance { get; set; } = default!;

        [JsonProperty("already_claimed", NullValueHandling = NullValueHandling.Include)]
        public bool AlreadyClaimed { get; set; } = default!;

    }
}
