// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class RaidRankRes
    {
        [JsonProperty("raid_id", NullValueHandling = NullValueHandling.Include)]
        public string RaidId { get; set; } = default!;

        [JsonProperty("participant_count", NullValueHandling = NullValueHandling.Include)]
        public int ParticipantCount { get; set; } = default!;

        [JsonProperty("settled", NullValueHandling = NullValueHandling.Include)]
        public bool Settled { get; set; } = default!;

        [JsonProperty("top", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.RaidRankEntryDto> Top { get; set; } = default!;

        [JsonProperty("around_me", NullValueHandling = NullValueHandling.Include)]
        public List<global::ThreeKingdoms.Shared.Types.RaidRankEntryDto> AroundMe { get; set; } = default!;

        [JsonProperty("me", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.RaidRankEntryDto? Me { get; set; } = default!;

    }
}
