// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class RaidClaimReq
    {
        [JsonProperty("raid_id", NullValueHandling = NullValueHandling.Include)]
        public string RaidId { get; set; } = default!;

    }
}
