// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class RaidStateRes
    {
        [JsonProperty("server_time", NullValueHandling = NullValueHandling.Include)]
        public string ServerTime { get; set; } = default!;

        [JsonProperty("round", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.RaidRoundDto? Round { get; set; } = default!;

        [JsonProperty("participant", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.RaidParticipantDto? Participant { get; set; } = default!;

        [JsonProperty("last_participated_raid_id", NullValueHandling = NullValueHandling.Include)]
        public string? LastParticipatedRaidId { get; set; } = default!;

        [JsonProperty("raid_point_balance", NullValueHandling = NullValueHandling.Include)]
        public string RaidPointBalance { get; set; } = default!;

    }
}
