// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class RelicStateDto_NextEnhance
    {
        [JsonProperty("cost_time_stone", NullValueHandling = NullValueHandling.Include)]
        public long CostTimeStone { get; set; } = default!;

    }
}
