// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 목표 단계 유물 강화 후 변경된 무장·시간석 상태.
    /// </summary>
    public class RelicEnhanceRes
    {
        /// <summary>
        /// 서버가 생성한 유물 강화 처리 UUID. 같은 x-request-id 재시도에는 같은 값이 반환된다.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 서버가 검증하고 누적 강화 비용 계산에 사용한 요청의 테이블 버전.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 대상 무장과 클래스 공유 효과가 적용된 같은 클래스 무장까지 반영한 전체 무장 상태.
        /// </summary>
        [JsonProperty("character_snapshot", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.CharacterSnapshotDto CharacterSnapshot { get; set; } = default!;

        /// <summary>
        /// 현재 단계부터 목표 단계까지의 누적 비용이 차감된 재화 절대 상태.
        /// </summary>
        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.AssetDto Asset { get; set; } = default!;

    }
}
