// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 보유 무장에 1:1로 연결된 전용 유물의 현재 강화 상태와 다음 단계 비용.
    /// </summary>
    public class RelicStateDto
    {
        /// <summary>
        /// s_relic.idx에 대응하는 전용 유물 숫자 ID.
        /// </summary>
        [JsonProperty("relic_id", NullValueHandling = NullValueHandling.Include)]
        public long RelicId { get; set; } = default!;

        /// <summary>
        /// s_relic.key에 대응하는 사람이 읽을 수 있는 유물 식별자.
        /// </summary>
        [JsonProperty("relic_key", NullValueHandling = NullValueHandling.Include)]
        public string RelicKey { get; set; } = default!;

        /// <summary>
        /// 현재 유물 강화 단계. 미강화 상태는 0이다.
        /// </summary>
        [JsonProperty("enhance_stage", NullValueHandling = NullValueHandling.Include)]
        public long EnhanceStage { get; set; } = default!;

        /// <summary>
        /// 현재 무장 등급에서 허용되는 유물 최대 강화 단계.
        /// </summary>
        [JsonProperty("max_enhance_stage", NullValueHandling = NullValueHandling.Include)]
        public long MaxEnhanceStage { get; set; } = default!;

        /// <summary>
        /// 다음 한 단계의 시간석 비용. 현재 등급 상한에 도달했으면 null이다.
        /// </summary>
        [JsonProperty("next_enhance", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.RelicStateDto_NextEnhance? NextEnhance { get; set; } = default!;

    }
}
