// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 보유 무장의 전용 유물을 현재보다 높은 목표 단계까지 강화하는 요청.
    /// </summary>
    public class RelicEnhanceReq
    {
        /// <summary>
        /// 강화할 전용 유물의 주인인 보유 무장 ID.
        /// </summary>
        [JsonProperty("character_id", NullValueHandling = NullValueHandling.Include)]
        public long CharacterId { get; set; } = default!;

        /// <summary>
        /// 이동할 누적 목표 단계. 현재 단계보다 높고 해당 무장 등급의 상한 이하여야 한다.
        /// </summary>
        [JsonProperty("target_stage", NullValueHandling = NullValueHandling.Include)]
        public long TargetStage { get; set; } = default!;

    }
}
