// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 서버 시각으로 군량 자동 충전을 정산한 뒤의 잔액과 다음 충전 타이머.
    /// </summary>
    public class RiceTimerRes
    {
        /// <summary>
        /// 자동 충전 정산 후의 재화 버전. 변경이 없으면 기존 버전과 같다.
        /// </summary>
        [JsonProperty("revision", NullValueHandling = NullValueHandling.Include)]
        public string Revision { get; set; } = default!;

        /// <summary>
        /// 경과 시간 정산까지 반영된 현재 군량 수량.
        /// </summary>
        [JsonProperty("rice", NullValueHandling = NullValueHandling.Include)]
        public long Rice { get; set; } = default!;

        /// <summary>
        /// 다음 군량 1개 충전까지 남은 초. 충전 상한이면 0이다.
        /// </summary>
        [JsonProperty("remain_seconds", NullValueHandling = NullValueHandling.Include)]
        public long RemainSeconds { get; set; } = default!;

        /// <summary>
        /// 자동 충전으로 도달할 수 있는 군량 상한.
        /// </summary>
        [JsonProperty("regen_max", NullValueHandling = NullValueHandling.Include)]
        public long RegenMax { get; set; } = default!;

        /// <summary>
        /// 군량 1개가 자동 충전되는 주기(초).
        /// </summary>
        [JsonProperty("regen_interval_seconds", NullValueHandling = NullValueHandling.Include)]
        public long RegenIntervalSeconds { get; set; } = default!;

    }
}
