// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 게임 시작 시 Wei·Shu·Wu 중 하나의 초기 지역을 선택하거나 재선택하는 요청.
    /// </summary>
    public class SelectRegionReq
    {
        /// <summary>
        /// 선택할 지역. Wei(0)·Shu(1)·Wu(2)만 허용한다.
        /// SelectableRegionType: RegionType.Wei | RegionType.Shu | RegionType.Wu
        /// </summary>
        [JsonProperty("region", NullValueHandling = NullValueHandling.Include)]
        public RegionType Region { get; set; } = default!;

    }
}
