// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 지역 선택 후 적용된 지역과 최신 사용자·무장 상태.
    /// </summary>
    public class SelectRegionRes
    {
        /// <summary>
        /// 서버가 적용한 초기 지역.
        /// SelectableRegionType: RegionType.Wei | RegionType.Shu | RegionType.Wu
        /// </summary>
        [JsonProperty("region", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.RegionType Region { get; set; } = default!;

        /// <summary>
        /// 선택 결과가 반영된 현재 사용자 정보.
        /// </summary>
        [JsonProperty("user_info", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.UserInfoDto UserInfo { get; set; } = default!;

        /// <summary>
        /// 최초 선택의 대표 무장 지급까지 반영된 전체 무장 상태.
        /// </summary>
        [JsonProperty("character_snapshot", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.CharacterSnapshotDto CharacterSnapshot { get; set; } = default!;

    }
}
