// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentRankingRes
    {
        /// <summary>
        /// 조회 시즌.
        /// </summary>
        [JsonProperty("season_id", NullValueHandling = NullValueHandling.Include)]
        public long SeasonId { get; set; } = default!;

        /// <summary>
        /// 조회 기준 UTC 시각.
        /// </summary>
        [JsonProperty("server_time", NullValueHandling = NullValueHandling.Include)]
        public string ServerTime { get; set; } = default!;

        /// <summary>
        /// 순위 순 참가자.
        /// </summary>
        [JsonProperty("entries", NullValueHandling = NullValueHandling.Include)]
        public List<TournamentRankingRes_Entries> Entries { get; set; } = default!;

        /// <summary>
        /// 해당 시즌 미참여면 null.
        /// </summary>
        [JsonProperty("my_rank", NullValueHandling = NullValueHandling.Include)]
        public long? MyRank { get; set; } = default!;

        /// <summary>
        /// 추가 순위가 있으면 다음 cursor.
        /// </summary>
        [JsonProperty("next_cursor", NullValueHandling = NullValueHandling.Include)]
        public string? NextCursor { get; set; } = default!;

    }
}
