// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentCandidateDto
    {
        /// <summary>
        /// 점수순 정렬 이후의 슬롯1~4. 승패 점수 기준이다.
        /// </summary>
        [JsonProperty("slot", NullValueHandling = NullValueHandling.Include)]
        public int Slot { get; set; } = default!;

        /// <summary>
        /// 상대 사용자 ID.
        /// </summary>
        [JsonProperty("uid", NullValueHandling = NullValueHandling.Include)]
        public long Uid { get; set; } = default!;

        /// <summary>
        /// 후보 생성 당시 점수.
        /// </summary>
        [JsonProperty("score", NullValueHandling = NullValueHandling.Include)]
        public long Score { get; set; } = default!;

        /// <summary>
        /// 후보 생성 당시 저장된 방어 전투력.
        /// </summary>
        [JsonProperty("combat_power", NullValueHandling = NullValueHandling.Include)]
        public long CombatPower { get; set; } = default!;

        /// <summary>
        /// 후보 생성 당시 방어 버전. 입장 때 최신 방어로 다시 고정한다.
        /// </summary>
        [JsonProperty("defense_revision", NullValueHandling = NullValueHandling.Include)]
        public string DefenseRevision { get; set; } = default!;

        /// <summary>
        /// 후보 생성 시점 상대 닉네임.
        /// </summary>
        [JsonProperty("nickname", NullValueHandling = NullValueHandling.Include)]
        public string Nickname { get; set; } = default!;

        /// <summary>
        /// 상대 프로필 무장 ID.
        /// </summary>
        [JsonProperty("profile_character_id", NullValueHandling = NullValueHandling.Include)]
        public long? ProfileCharacterId { get; set; } = default!;

    }
}
