// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentCombatSnapshot
    {
        /// <summary>
        /// 저장 시점의 테이블 버전.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 전투 스탯 계산 계약 버전.
        /// </summary>
        [JsonProperty("combat_version", NullValueHandling = NullValueHandling.Include)]
        public long CombatVersion { get; set; } = default!;

        /// <summary>
        /// 저장 UTC ISO 시각.
        /// </summary>
        [JsonProperty("saved_at", NullValueHandling = NullValueHandling.Include)]
        public string SavedAt { get; set; } = default!;

        /// <summary>
        /// 위치와 스탯이 고정된 무장 목록.
        /// </summary>
        [JsonProperty("heroes", NullValueHandling = NullValueHandling.Include)]
        public List<TournamentCombatHeroDto> Heroes { get; set; } = default!;

        /// <summary>
        /// 선택 순서의 보물 효과.
        /// </summary>
        [JsonProperty("treasures", NullValueHandling = NullValueHandling.Include)]
        public List<TournamentCombatTreasureDto> Treasures { get; set; } = default!;

        /// <summary>
        /// 편성 전체 전투력.
        /// </summary>
        [JsonProperty("combat_power", NullValueHandling = NullValueHandling.Include)]
        public long CombatPower { get; set; } = default!;

    }
}
