// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentUserDto
    {
        /// <summary>
        /// 개인 편성·횟수·후보 상태의 버전.
        /// </summary>
        [JsonProperty("revision", NullValueHandling = NullValueHandling.Include)]
        public string Revision { get; set; } = default!;

        /// <summary>
        /// 시즌 점수의 버전.
        /// </summary>
        [JsonProperty("season_revision", NullValueHandling = NullValueHandling.Include)]
        public string SeasonRevision { get; set; } = default!;

        /// <summary>
        /// 현재 시즌 경쟁 점수.
        /// </summary>
        [JsonProperty("score", NullValueHandling = NullValueHandling.Include)]
        public long Score { get; set; } = default!;

        /// <summary>
        /// 조회 시점 순위.
        /// </summary>
        [JsonProperty("rank", NullValueHandling = NullValueHandling.Include)]
        public long Rank { get; set; } = default!;

        /// <summary>
        /// 현재 티어 master idx.
        /// </summary>
        [JsonProperty("tier_idx", NullValueHandling = NullValueHandling.Include)]
        public long TierIdx { get; set; } = default!;

        /// <summary>
        /// 일일 횟수 기준 게임 날짜.
        /// </summary>
        [JsonProperty("day_key", NullValueHandling = NullValueHandling.Include)]
        public string DayKey { get; set; } = default!;

        /// <summary>
        /// 공유 도전 잔량.
        /// </summary>
        [JsonProperty("remaining_count", NullValueHandling = NullValueHandling.Include)]
        public long RemainingCount { get; set; } = default!;

        /// <summary>
        /// 당일 성공한 광고 완료 횟수.
        /// </summary>
        [JsonProperty("ad_used_count", NullValueHandling = NullValueHandling.Include)]
        public long AdUsedCount { get; set; } = default!;

        /// <summary>
        /// 자연 충전되는 무료 갱신 잔량.
        /// </summary>
        [JsonProperty("free_refresh_count", NullValueHandling = NullValueHandling.Include)]
        public long FreeRefreshCount { get; set; } = default!;

        /// <summary>
        /// 당일 유료 갱신 횟수.
        /// </summary>
        [JsonProperty("paid_refresh_count", NullValueHandling = NullValueHandling.Include)]
        public long PaidRefreshCount { get; set; } = default!;

        /// <summary>
        /// 무료 충전 기준 시각. 가득 차면 null.
        /// </summary>
        [JsonProperty("recharge_at", NullValueHandling = NullValueHandling.Include)]
        public string? RechargeAt { get; set; } = default!;

        /// <summary>
        /// 후보가 생성된 게임 날짜.
        /// </summary>
        [JsonProperty("candidate_day_key", NullValueHandling = NullValueHandling.Include)]
        public string? CandidateDayKey { get; set; } = default!;

        /// <summary>
        /// 입장·갱신 요청에서 대조할 후보 버전.
        /// </summary>
        [JsonProperty("candidate_set_revision", NullValueHandling = NullValueHandling.Include)]
        public string CandidateSetRevision { get; set; } = default!;

        /// <summary>
        /// 저장된 방어 버전.
        /// </summary>
        [JsonProperty("defense_revision", NullValueHandling = NullValueHandling.Include)]
        public string DefenseRevision { get; set; } = default!;

        /// <summary>
        /// 현재 공격 선택 편성.
        /// </summary>
        [JsonProperty("attack_formation", NullValueHandling = NullValueHandling.Include)]
        public TournamentFormationInput? AttackFormation { get; set; } = default!;

        /// <summary>
        /// 마지막 저장 시점 방어 입력.
        /// </summary>
        [JsonProperty("defense_snapshot", NullValueHandling = NullValueHandling.Include)]
        public TournamentCombatSnapshot? DefenseSnapshot { get; set; } = default!;

        /// <summary>
        /// 실제 사용자0~4명.
        /// </summary>
        [JsonProperty("candidates", NullValueHandling = NullValueHandling.Include)]
        public List<TournamentCandidateDto> Candidates { get; set; } = default!;

        /// <summary>
        /// 아직 정산되지 않은 본인 전투 ID.
        /// </summary>
        [JsonProperty("active_battle_id", NullValueHandling = NullValueHandling.Include)]
        public string? ActiveBattleId { get; set; } = default!;

    }
}
