// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentMutationRes
    {
        /// <summary>
        /// 멱등 처리 event UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 처리 후 본인 상태.
        /// </summary>
        [JsonProperty("tournament", NullValueHandling = NullValueHandling.Include)]
        public TournamentSnapshotDto Tournament { get; set; } = default!;

        /// <summary>
        /// 재화를 쓰지 않는 action도 현재 절대 상태를 그대로 반환한다.
        /// </summary>
        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public AssetDto Asset { get; set; } = default!;

    }
}
