// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentFormationInput
    {
        /// <summary>
        /// 보유 무장1~4명과 위치.
        /// </summary>
        [JsonProperty("heroes", NullValueHandling = NullValueHandling.Include)]
        public List<TournamentHeroPositionDto> Heroes { get; set; } = default!;

        /// <summary>
        /// 순서 있는 보유 보물0~3개. 일반 장착과 독립이다.
        /// </summary>
        [JsonProperty("treasure_ids", NullValueHandling = NullValueHandling.Include)]
        public List<long> TreasureIds { get; set; } = default!;

    }
}
