// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentEntryDto
    {
        /// <summary>
        /// finish에서 보낼 전투 ID.
        /// </summary>
        [JsonProperty("battle_id", NullValueHandling = NullValueHandling.Include)]
        public string BattleId { get; set; } = default!;

        /// <summary>
        /// 입장 시즌.
        /// </summary>
        [JsonProperty("season_id", NullValueHandling = NullValueHandling.Include)]
        public long SeasonId { get; set; } = default!;

        /// <summary>
        /// 확정된 상대 ID.
        /// </summary>
        [JsonProperty("target_uid", NullValueHandling = NullValueHandling.Include)]
        public long TargetUid { get; set; } = default!;

        /// <summary>
        /// 이번 입장에 고정한 상대 방어 버전.
        /// </summary>
        [JsonProperty("defense_revision", NullValueHandling = NullValueHandling.Include)]
        public string DefenseRevision { get; set; } = default!;

        /// <summary>
        /// 복수 원본. 일반 공격은 null.
        /// </summary>
        [JsonProperty("source_battle_id", NullValueHandling = NullValueHandling.Include)]
        public string? SourceBattleId { get; set; } = default!;

        /// <summary>
        /// 일반 공격의 점수 슬롯. 복수는 null.
        /// </summary>
        [JsonProperty("slot", NullValueHandling = NullValueHandling.Include)]
        public int? Slot { get; set; } = default!;

        /// <summary>
        /// 실제 입장 UTC 시각.
        /// </summary>
        [JsonProperty("started_at", NullValueHandling = NullValueHandling.Include)]
        public string StartedAt { get; set; } = default!;

        /// <summary>
        /// 클라이언트 자동 전투 제한시간.
        /// </summary>
        [JsonProperty("battle_duration_seconds", NullValueHandling = NullValueHandling.Include)]
        public long BattleDurationSeconds { get; set; } = default!;

        /// <summary>
        /// 승리 기준 점수. 상대 잔액보다 큰 부분은 획득하지 않는다.
        /// </summary>
        [JsonProperty("win_score", NullValueHandling = NullValueHandling.Include)]
        public long WinScore { get; set; } = default!;

        /// <summary>
        /// 패배 기준 감점(음수).
        /// </summary>
        [JsonProperty("lose_score", NullValueHandling = NullValueHandling.Include)]
        public long LoseScore { get; set; } = default!;

        /// <summary>
        /// 승리 포인트.
        /// </summary>
        [JsonProperty("point_win", NullValueHandling = NullValueHandling.Include)]
        public long PointWin { get; set; } = default!;

        /// <summary>
        /// 패배 포인트.
        /// </summary>
        [JsonProperty("point_lose", NullValueHandling = NullValueHandling.Include)]
        public long PointLose { get; set; } = default!;

        /// <summary>
        /// 이번 전투에 고정된 공격 입력.
        /// </summary>
        [JsonProperty("attack", NullValueHandling = NullValueHandling.Include)]
        public TournamentCombatSnapshot Attack { get; set; } = default!;

        /// <summary>
        /// 이번 전투에 고정된 최신 저장 방어 입력.
        /// </summary>
        [JsonProperty("defense", NullValueHandling = NullValueHandling.Include)]
        public TournamentCombatSnapshot Defense { get; set; } = default!;

    }
}
