// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentCombatTreasureDto
    {
        /// <summary>
        /// 보유 보물 ID.
        /// </summary>
        [JsonProperty("treasure_id", NullValueHandling = NullValueHandling.Include)]
        public long TreasureId { get; set; } = default!;

        /// <summary>
        /// s_treasure.key.
        /// </summary>
        [JsonProperty("treasure_key", NullValueHandling = NullValueHandling.Include)]
        public string TreasureKey { get; set; } = default!;

        /// <summary>
        /// 선택 시점에 고정한 보물 효과.
        /// </summary>
        [JsonProperty("effects", NullValueHandling = NullValueHandling.Include)]
        public List<TournamentTreasureEffectDto> Effects { get; set; } = default!;

    }
}
