// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentRankingReq
    {
        /// <summary>
        /// 조회할 YYYYMM 시즌 ID.
        /// </summary>
        [JsonProperty("season_id", NullValueHandling = NullValueHandling.Include)]
        public long SeasonId { get; set; } = default!;

        /// <summary>
        /// 첫 조회는 null, 다음 조회는 직전 응답의 next_cursor.
        /// </summary>
        [JsonProperty("cursor", NullValueHandling = NullValueHandling.Include)]
        public string? Cursor { get; set; } = default!;

        /// <summary>
        /// 한 번에 조회할 순위 수1~100.
        /// </summary>
        [JsonProperty("limit", NullValueHandling = NullValueHandling.Include)]
        public int Limit { get; set; } = default!;

    }
}
