// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentCombatHeroDto
    {
        /// <summary>
        /// 보유 무장 master ID.
        /// </summary>
        [JsonProperty("character_id", NullValueHandling = NullValueHandling.Include)]
        public long CharacterId { get; set; } = default!;

        /// <summary>
        /// 3×3 편성의 위치0~8. 같은 위치에 두 무장을 배치할 수 없다.
        /// </summary>
        [JsonProperty("position", NullValueHandling = NullValueHandling.Include)]
        public int Position { get; set; } = default!;

        /// <summary>
        /// 무장 master key.
        /// </summary>
        [JsonProperty("character_key", NullValueHandling = NullValueHandling.Include)]
        public string CharacterKey { get; set; } = default!;

        /// <summary>
        /// 스냅샷 시점 등급.
        /// </summary>
        [JsonProperty("character_grade", NullValueHandling = NullValueHandling.Include)]
        public CharacterGrade CharacterGrade { get; set; } = default!;

        /// <summary>
        /// 스냅샷 시점 성장 단계.
        /// </summary>
        [JsonProperty("growth_stage", NullValueHandling = NullValueHandling.Include)]
        public long GrowthStage { get; set; } = default!;

        /// <summary>
        /// 스냅샷 시점 유물 단계.
        /// </summary>
        [JsonProperty("relic_enhance_stage", NullValueHandling = NullValueHandling.Include)]
        public long RelicEnhanceStage { get; set; } = default!;

        /// <summary>
        /// 선택된 무장의 특성.
        /// </summary>
        [JsonProperty("traits", NullValueHandling = NullValueHandling.Include)]
        public List<CharacterTraitStateDto> Traits { get; set; } = default!;

        /// <summary>
        /// 서버가 계산한 최종 전투 스탯.
        /// </summary>
        [JsonProperty("combat_stats", NullValueHandling = NullValueHandling.Include)]
        public CharacterCombatStatsDto CombatStats { get; set; } = default!;

        /// <summary>
        /// 서버가 계산한 전투력.
        /// </summary>
        [JsonProperty("combat_power", NullValueHandling = NullValueHandling.Include)]
        public long CombatPower { get; set; } = default!;

    }
}
