// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentSnapshotDto
    {
        /// <summary>
        /// 다음 요청 header에 사용할 현재 서버 테이블 버전.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 시즌 시작에 고정된 점수·횟수 규칙의 테이블 버전.
        /// </summary>
        [JsonProperty("rules_table_version", NullValueHandling = NullValueHandling.Include)]
        public string RulesTableVersion { get; set; } = default!;

        /// <summary>
        /// 게임 날짜 기준 YYYYMM.
        /// </summary>
        [JsonProperty("season_id", NullValueHandling = NullValueHandling.Include)]
        public long SeasonId { get; set; } = default!;

        /// <summary>
        /// 시즌 준비 중이면 새 동작을 진행할 수 없다.
        /// </summary>
        [JsonProperty("season_status", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.TournamentAvailabilityStatus SeasonStatus { get; set; } = default!;

        /// <summary>
        /// 서버 UTC 시각.
        /// </summary>
        [JsonProperty("server_time", NullValueHandling = NullValueHandling.Include)]
        public string ServerTime { get; set; } = default!;

        /// <summary>
        /// 시즌 시작 UTC 시각.
        /// </summary>
        [JsonProperty("starts_at", NullValueHandling = NullValueHandling.Include)]
        public string StartsAt { get; set; } = default!;

        /// <summary>
        /// 신규 입장 차단 UTC 시각.
        /// </summary>
        [JsonProperty("cutoff_at", NullValueHandling = NullValueHandling.Include)]
        public string CutoffAt { get; set; } = default!;

        /// <summary>
        /// 시즌 마감 UTC 시각.
        /// </summary>
        [JsonProperty("ends_at", NullValueHandling = NullValueHandling.Include)]
        public string EndsAt { get; set; } = default!;

        /// <summary>
        /// preparing 상태에는 null.
        /// </summary>
        [JsonProperty("user", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.TournamentUserDto? User { get; set; } = default!;

    }
}
