// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentHistoryBattleDto
    {
        /// <summary>
        /// 전투 이력 ID.
        /// </summary>
        [JsonProperty("battle_id", NullValueHandling = NullValueHandling.Include)]
        public string BattleId { get; set; } = default!;

        /// <summary>
        /// 전투가 열린 시즌 ID.
        /// </summary>
        [JsonProperty("season_id", NullValueHandling = NullValueHandling.Include)]
        public long SeasonId { get; set; } = default!;

        /// <summary>
        /// 공격 사용자 UID.
        /// </summary>
        [JsonProperty("attacker_uid", NullValueHandling = NullValueHandling.Include)]
        public long AttackerUid { get; set; } = default!;

        /// <summary>
        /// 방어 사용자 UID.
        /// </summary>
        [JsonProperty("defender_uid", NullValueHandling = NullValueHandling.Include)]
        public long DefenderUid { get; set; } = default!;

        /// <summary>
        /// 진행·완료·포기·만료 상태.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.TournamentBattleStatus Status { get; set; } = default!;

        /// <summary>
        /// 완료되지 않았으면 null, 완료되었으면 조회 사용자 관점 승패.
        /// </summary>
        [JsonProperty("result", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.TournamentBattleResult? Result { get; set; } = default!;

        /// <summary>
        /// 조회 사용자 관점의 실제 점수 증감.
        /// </summary>
        [JsonProperty("score_delta", NullValueHandling = NullValueHandling.Include)]
        public long ScoreDelta { get; set; } = default!;

        /// <summary>
        /// 종료 UTC ISO 8601 시각. 진행 중이면 null.
        /// </summary>
        [JsonProperty("completed_at", NullValueHandling = NullValueHandling.Include)]
        public string? CompletedAt { get; set; } = default!;

        /// <summary>
        /// 현재 복수 입장이 가능한지 여부.
        /// </summary>
        [JsonProperty("revenge_available", NullValueHandling = NullValueHandling.Include)]
        public bool RevengeAvailable { get; set; } = default!;

    }
}
