// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentHeroPositionDto
    {
        /// <summary>
        /// 보유 무장 master ID.
        /// </summary>
        [JsonProperty("character_id", NullValueHandling = NullValueHandling.Include)]
        public long CharacterId { get; set; } = default!;

        /// <summary>
        /// 3×3 편성의 위치0~8. 같은 위치에 두 무장을 배치할 수 없다.
        /// </summary>
        [JsonProperty("position", NullValueHandling = NullValueHandling.Include)]
        public int Position { get; set; } = default!;

    }
}
