// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentFinishReq
    {
        /// <summary>
        /// start/revenge 응답에서 받은 현재 active 전투 ID.
        /// </summary>
        [JsonProperty("battle_id", NullValueHandling = NullValueHandling.Include)]
        public string BattleId { get; set; } = default!;

        /// <summary>
        /// 클라이언트가 보고할 Win(0) 또는 Lose(1).
        /// </summary>
        [JsonProperty("result", NullValueHandling = NullValueHandling.Include)]
        public TournamentBattleResult Result { get; set; } = default!;

    }
}
