// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentFinishRes
    {
        /// <summary>
        /// 멱등 처리 event UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 처리 후 본인 상태.
        /// </summary>
        [JsonProperty("tournament", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.TournamentSnapshotDto Tournament { get; set; } = default!;

        /// <summary>
        /// 재화를 쓰지 않는 action도 현재 절대 상태를 그대로 반환한다.
        /// </summary>
        [JsonProperty("asset", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Types.AssetDto Asset { get; set; } = default!;

        /// <summary>
        /// 정산한 전투.
        /// </summary>
        [JsonProperty("battle_id", NullValueHandling = NullValueHandling.Include)]
        public string BattleId { get; set; } = default!;

        /// <summary>
        /// 최초로 확정된 결과.
        /// </summary>
        [JsonProperty("result", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.TournamentBattleResult Result { get; set; } = default!;

        /// <summary>
        /// 공격자 실제 점수 증감.
        /// </summary>
        [JsonProperty("attacker_score_delta", NullValueHandling = NullValueHandling.Include)]
        public long AttackerScoreDelta { get; set; } = default!;

        /// <summary>
        /// 방어자 실제 점수 증감. 방어 성공은0.
        /// </summary>
        [JsonProperty("defender_score_delta", NullValueHandling = NullValueHandling.Include)]
        public long DefenderScoreDelta { get; set; } = default!;

        /// <summary>
        /// 공격자에게 지급한 영구 보유 토너먼트 포인트.
        /// </summary>
        [JsonProperty("point_delta", NullValueHandling = NullValueHandling.Include)]
        public long PointDelta { get; set; } = default!;

    }
}
