// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentTreasureEffectDto
    {
        /// <summary>
        /// CharacterCombatStatsDto의 10개 property 이름 중 하나.
        /// </summary>
        [JsonProperty("stat", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.CombatStatKey Stat { get; set; } = default!;

        /// <summary>
        /// 스냅샷에 고정한 효과 수치.
        /// </summary>
        [JsonProperty("value", NullValueHandling = NullValueHandling.Include)]
        public double Value { get; set; } = default!;

    }
}
