// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentStartReq
    {
        /// <summary>
        /// snapshot에서 받은 현재 후보 목록 revision.
        /// </summary>
        [JsonProperty("candidate_set_revision", NullValueHandling = NullValueHandling.Include)]
        public string CandidateSetRevision { get; set; } = default!;

        /// <summary>
        /// 현재 후보 목록에서 선택할 슬롯1~4.
        /// </summary>
        [JsonProperty("slot", NullValueHandling = NullValueHandling.Include)]
        public int Slot { get; set; } = default!;

    }
}
