// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentHistoryRes
    {
        /// <summary>
        /// 승패·점수 증감이 조회한 본인 관점인 공격·방어 이력.
        /// </summary>
        [JsonProperty("battles", NullValueHandling = NullValueHandling.Include)]
        public List<TournamentHistoryBattleDto> Battles { get; set; } = default!;

        /// <summary>
        /// 추가 이력이 있으면 다음 cursor.
        /// </summary>
        [JsonProperty("next_cursor", NullValueHandling = NullValueHandling.Include)]
        public string? NextCursor { get; set; } = default!;

    }
}
