// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentRankingRes_Entries
    {
        [JsonProperty("uid", NullValueHandling = NullValueHandling.Include)]
        public long Uid { get; set; } = default!;

        [JsonProperty("rank", NullValueHandling = NullValueHandling.Include)]
        public long Rank { get; set; } = default!;

        [JsonProperty("score", NullValueHandling = NullValueHandling.Include)]
        public long Score { get; set; } = default!;

        [JsonProperty("tier_idx", NullValueHandling = NullValueHandling.Include)]
        public long TierIdx { get; set; } = default!;

        [JsonProperty("nickname", NullValueHandling = NullValueHandling.Include)]
        public string Nickname { get; set; } = default!;

        [JsonProperty("profile_character_id", NullValueHandling = NullValueHandling.Include)]
        public long? ProfileCharacterId { get; set; } = default!;

    }
}
