// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    public class TournamentRevengeReq
    {
        /// <summary>
        /// history에서 복수 가능으로 받은 원 전투 ID.
        /// </summary>
        [JsonProperty("source_battle_id", NullValueHandling = NullValueHandling.Include)]
        public string SourceBattleId { get; set; } = default!;

    }
}
