// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 장착할 보물을 순서 있는 전체 목록으로 설정한다.
    /// </summary>
    public class TreasureSetEquippedReq
    {
        /// <summary>
        /// 장착할 보물 ID 0~3개. 빈 목록은 전체 해제.
        /// </summary>
        [JsonProperty("equipped_treasure_ids", NullValueHandling = NullValueHandling.Include)]
        public List<long> EquippedTreasureIds { get; set; } = default!;

    }
}
