// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 보물 장착 변경 후 보유 목록과 전투 상태.
    /// </summary>
    public class TreasureSetEquippedRes
    {
        /// <summary>
        /// 서버가 발급한 처리 UUID.
        /// </summary>
        [JsonProperty("event_id", NullValueHandling = NullValueHandling.Include)]
        public string EventId { get; set; } = default!;

        /// <summary>
        /// 요청에 사용한 테이블 버전.
        /// </summary>
        [JsonProperty("table_version", NullValueHandling = NullValueHandling.Include)]
        public string TableVersion { get; set; } = default!;

        /// <summary>
        /// 미장착 보물을 포함한 전체 보유 목록.
        /// </summary>
        [JsonProperty("treasures", NullValueHandling = NullValueHandling.Include)]
        public List<TreasureStateDto> Treasures { get; set; } = default!;

        /// <summary>
        /// 보물 효과를 반영한 전체 무장 상태.
        /// </summary>
        [JsonProperty("character_snapshot", NullValueHandling = NullValueHandling.Include)]
        public CharacterSnapshotDto CharacterSnapshot { get; set; } = default!;

    }
}
