// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Types
{
    /// <summary>
    /// 계정이 보유한 보물의 현재 장착 위치.
    /// </summary>
    public class TreasureStateDto
    {
        /// <summary>
        /// s_treasure.idx에 대응하는 보물 ID.
        /// </summary>
        [JsonProperty("treasure_id", NullValueHandling = NullValueHandling.Include)]
        public long TreasureId { get; set; } = default!;

        /// <summary>
        /// 보물 master key.
        /// </summary>
        [JsonProperty("treasure_key", NullValueHandling = NullValueHandling.Include)]
        public string TreasureKey { get; set; } = default!;

        /// <summary>
        /// 장착 순서 0~2. 미장착이면 null.
        /// </summary>
        [JsonProperty("equipped_slot", NullValueHandling = NullValueHandling.Include)]
        public int? EquippedSlot { get; set; } = default!;

        /// <summary>
        /// 최초 획득 UTC ISO 8601 시각.
        /// </summary>
        [JsonProperty("acquired_at", NullValueHandling = NullValueHandling.Include)]
        public string AcquiredAt { get; set; } = default!;

    }
}
