// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 계정의 현재 이용 가능 상태.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AccountState
    {
        /// <summary>
        /// 정상 이용 가능
        /// </summary>
        [EnumMember(Value = "ACTIVE")]
        Active = 0,
        /// <summary>
        /// 기간이 있는 일시 정지
        /// </summary>
        [EnumMember(Value = "TEMPORARY_SUSPENDED")]
        TemporarySuspended = 1,
        /// <summary>
        /// 영구 이용 정지
        /// </summary>
        [EnumMember(Value = "PERMANENT_SUSPENDED")]
        PermanentSuspended = 2,
        /// <summary>
        /// 삭제 완료
        /// </summary>
        [EnumMember(Value = "DELETED")]
        Deleted = 3,
    }

    /// <summary>
    /// 승급 재료 타입
    /// </summary>
    public enum AscensionMaterialType
    {
        /// <summary>
        /// 공용 영혼석
        /// </summary>
        SoulStonePublic = 0,
        /// <summary>
        /// 클래스 영혼석
        /// </summary>
        SoulStoneClass = 1,
        /// <summary>
        /// 장수 영혼석
        /// </summary>
        SoulStoneDedicated = 2,
    }

    /// <summary>
    /// 보스 등급
    /// </summary>
    public enum BossGrade
    {
        /// <summary>
        /// 일반
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 정예
        /// </summary>
        Elite = 1,
        /// <summary>
        /// 명장
        /// </summary>
        General = 2,
        /// <summary>
        /// 영웅
        /// </summary>
        Hero = 3,
        /// <summary>
        /// 전설
        /// </summary>
        Legend = 4,
    }

    /// <summary>
    /// 보스 타입
    /// </summary>
    public enum BossType
    {
        /// <summary>
        /// 기본
        /// </summary>
        Basic = 0,
        /// <summary>
        /// 진
        /// </summary>
        Jin = 1,
    }

    /// <summary>
    /// 번들 아이템 타입
    /// </summary>
    public enum BundleItemType
    {
        /// <summary>
        /// 주머니
        /// </summary>
        Pocket = 0,
        /// <summary>
        /// 랜덤 상자
        /// </summary>
        RandomBox = 1,
    }

    /// <summary>
    /// 영지 건물 증축의 현재 진행 상태.
    /// </summary>
    public enum CastleBuildingUpgradeStatus
    {
        /// <summary>
        /// 시간 경과 중
        /// </summary>
        Running = 0,
        /// <summary>
        /// 선행 조건 미충족으로 일시 정지
        /// </summary>
        Paused = 1,
    }

    /// <summary>
    /// 영지 디버프 타입
    /// </summary>
    public enum CastleDebuffType
    {
        /// <summary>
        /// 시간 단축 효율 감소 (궁성)
        /// </summary>
        DebuffTimeReduceEfficiency = 0,
        /// <summary>
        /// 획득량 감소 수령 시점 (시장/농지)
        /// </summary>
        DebuffIncomeRate = 1,
        /// <summary>
        /// 아이템 할인율 감소 (행상)
        /// </summary>
        DebuffDiscountRate = 2,
        /// <summary>
        /// 높은 등급 임무 등장 확률 감소 (관아)
        /// </summary>
        DebuffHighGradeMissionRate = 3,
    }

    /// <summary>
    /// 캐릭터 클래스
    /// </summary>
    public enum CharacterClass
    {
        /// <summary>
        /// 지휘관
        /// </summary>
        Commander = 0,
        /// <summary>
        /// 용장
        /// </summary>
        Champion = 1,
        /// <summary>
        /// 선봉장
        /// </summary>
        Vanguard = 2,
        /// <summary>
        /// 추격자
        /// </summary>
        Chaser = 3,
        /// <summary>
        /// 궁장
        /// </summary>
        Archer = 4,
        /// <summary>
        /// 책사
        /// </summary>
        Strategist = 5,
    }

    /// <summary>
    /// 캐릭터 등급
    /// </summary>
    public enum CharacterGrade
    {
        /// <summary>
        /// 일반
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 정예
        /// </summary>
        Elite = 1,
        /// <summary>
        /// 명장
        /// </summary>
        General = 2,
        /// <summary>
        /// 영웅
        /// </summary>
        Hero = 3,
        /// <summary>
        /// 전설
        /// </summary>
        Legend = 4,
    }

    /// <summary>
    /// 무장 성장 한 번의 최종 판정.
    /// </summary>
    public enum CharacterGrowthResult
    {
        /// <summary>
        /// 확률 성공
        /// </summary>
        Success = 0,
        /// <summary>
        /// 실패
        /// </summary>
        Fail = 1,
        /// <summary>
        /// 누적 성장 포인트 보장 성공
        /// </summary>
        GuaranteedSuccess = 2,
    }

    /// <summary>
    /// 직책의 해금·진행 가능 상태.
    /// </summary>
    public enum CharacterPositionStatus
    {
        /// <summary>
        /// 해금 완료
        /// </summary>
        Unlocked = 0,
        /// <summary>
        /// 해금 조건 미충족
        /// </summary>
        Locked = 1,
        /// <summary>
        /// 진행 기록 연결 전이라 판정 불가
        /// </summary>
        Unavailable = 2,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CombatStatKey
    {
        [EnumMember(Value = "attack_power")]
        AttackPower = 0,
        [EnumMember(Value = "defence")]
        Defence = 1,
        [EnumMember(Value = "health_max")]
        HealthMax = 2,
        [EnumMember(Value = "attack_speed")]
        AttackSpeed = 3,
        [EnumMember(Value = "move_speed")]
        MoveSpeed = 4,
        [EnumMember(Value = "critical_rate")]
        CriticalRate = 5,
        [EnumMember(Value = "critical_damage")]
        CriticalDamage = 6,
        [EnumMember(Value = "cooldown_rate")]
        CooldownRate = 7,
        [EnumMember(Value = "life_steal")]
        LifeSteal = 8,
        [EnumMember(Value = "boss_damage")]
        BossDamage = 9,
    }

    /// <summary>
    /// 콘텐츠 상점 타입 (s_shop.shop_type 및 API)
    /// </summary>
    public enum ContentShopType
    {
        /// <summary>
        /// 일일 상점
        /// </summary>
        Daily = 1,
        /// <summary>
        /// 레이드 상점
        /// </summary>
        Raid = 2,
        /// <summary>
        /// 토너먼트 상점
        /// </summary>
        Tournament = 3,
    }

    /// <summary>
    /// 무장·매치 소속 국가 분류 (초기 지역 선택 API용 아님)
    /// </summary>
    public enum Country
    {
        /// <summary>
        /// 위
        /// </summary>
        Wei = 0,
        /// <summary>
        /// 촉
        /// </summary>
        Shu = 1,
        /// <summary>
        /// 오
        /// </summary>
        Wu = 2,
        /// <summary>
        /// 군
        /// </summary>
        Force = 3,
        /// <summary>
        /// 다중 국가(s_match 전용)
        /// </summary>
        Mixed = 4,
        /// <summary>
        /// 추후 생성될 국가분류
        /// </summary>
        Etc = 5,
        /// <summary>
        /// 황건적
        /// </summary>
        YellowTurban = 6,
        /// <summary>
        /// 동탁 세력
        /// </summary>
        DongzhuoGroup = 7,
        /// <summary>
        /// 원소 세력
        /// </summary>
        YuanshaoGroup = 8,
        /// <summary>
        /// 원술 세력
        /// </summary>
        YuanshuGroup = 9,
        /// <summary>
        /// 엄백호 세력
        /// </summary>
        YanbaihuGroup = 10,
        /// <summary>
        /// 여포 세력
        /// </summary>
        LubuGroup = 11,
    }

    /// <summary>
    /// 던전 보스 클래스
    /// </summary>
    public enum DungeonBossClass
    {
        /// <summary>
        /// 지휘관
        /// </summary>
        Commander = 0,
        /// <summary>
        /// 용장
        /// </summary>
        Champion = 1,
        /// <summary>
        /// 선봉장
        /// </summary>
        Vanguard = 2,
        /// <summary>
        /// 추격자
        /// </summary>
        Chaser = 3,
        /// <summary>
        /// 궁장
        /// </summary>
        Archer = 4,
        /// <summary>
        /// 책사
        /// </summary>
        Strategist = 5,
    }

    /// <summary>
    /// 던전 보스 등급
    /// </summary>
    public enum DungeonBossGrade
    {
        /// <summary>
        /// 일반
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 난세
        /// </summary>
        Elite = 1,
        /// <summary>
        /// 극한
        /// </summary>
        General = 2,
        /// <summary>
        /// 지옥
        /// </summary>
        Hero = 3,
        /// <summary>
        /// 심연
        /// </summary>
        Legend = 4,
    }

    /// <summary>
    /// 적 국가
    /// </summary>
    public enum EnemyCountry
    {
        /// <summary>
        /// 위
        /// </summary>
        Wei = 0,
        /// <summary>
        /// 촉
        /// </summary>
        Shu = 1,
        /// <summary>
        /// 오
        /// </summary>
        Wu = 2,
        /// <summary>
        /// 군
        /// </summary>
        Force = 3,
        /// <summary>
        /// 황건적
        /// </summary>
        YellowTurbans = 4,
        /// <summary>
        /// 고대
        /// </summary>
        Ancient = 5,
    }

    /// <summary>
    /// 계정 생성 및 로그인에 사용한 인증 방식.
    /// </summary>
    public enum GameClientLoginType
    {
        /// <summary>
        /// Firebase anonymous 인증. 소셜 연동 목록에는 포함하지 않는다.
        /// </summary>
        GuestLogin = 1,
        /// <summary>
        /// Google 계정 로그인
        /// </summary>
        GoogleLogin = 2,
        /// <summary>
        /// Facebook 계정 로그인
        /// </summary>
        FacebookLogin = 3,
        /// <summary>
        /// Apple 계정 로그인
        /// </summary>
        AppleLogin = 4,
    }

    /// <summary>
    /// 성장 재료 타입
    /// </summary>
    public enum GrowthMaterialType
    {
        /// <summary>
        /// 군량
        /// </summary>
        Rice = 0,
        /// <summary>
        /// 금화
        /// </summary>
        Gold = 1,
    }

    /// <summary>
    /// 가이드 퀘스트 종류
    /// </summary>
    public enum GuideQuestKind
    {
        /// <summary>
        /// 학습 퀘스트
        /// </summary>
        Learning = 0,
        /// <summary>
        /// 반복 퀘스트
        /// </summary>
        Repeat = 1,
    }

    /// <summary>
    /// 아이템 상세 타입
    /// </summary>
    public enum ItemDetailType
    {
        /// <summary>
        /// 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 군량
        /// </summary>
        Rice = 0,
        /// <summary>
        /// 금화
        /// </summary>
        Gold = 1,
        /// <summary>
        /// 시간석
        /// </summary>
        TimeStone = 2,
        /// <summary>
        /// 군량 주머니
        /// </summary>
        PocketRice = 3,
        /// <summary>
        /// 금화 주머니
        /// </summary>
        PocketGold = 4,
        /// <summary>
        /// 시간석 주머니
        /// </summary>
        PocketTimeStone = 5,
        /// <summary>
        /// 클래스 영혼석 랜덤박스
        /// </summary>
        RandomBoxSoulStoneClass = 6,
        /// <summary>
        /// 전용 영혼석 랜덤박스
        /// </summary>
        RandomBoxSoulStoneDedicated = 7,
        /// <summary>
        /// 보물 조각 랜덤박스
        /// </summary>
        RandomBoxTreasurePiece = 8,
        /// <summary>
        /// 일반 연회권
        /// </summary>
        TicketGachaNormal = 9,
        /// <summary>
        /// 고급 연회권
        /// </summary>
        TicketGachaPremium = 10,
        /// <summary>
        /// 레이드 포인트
        /// </summary>
        PointRaid = 11,
        /// <summary>
        /// 토너먼트 포인트
        /// </summary>
        PointTournament = 12,
        /// <summary>
        /// 공용 영혼석
        /// </summary>
        SoulStonePublic = 13,
        /// <summary>
        /// 전용 영혼석
        /// </summary>
        SoulStoneDedicated = 14,
        /// <summary>
        /// 클래스 영혼석
        /// </summary>
        SoulStoneClass = 15,
        /// <summary>
        /// 보물 마일리지
        /// </summary>
        TreasureMileage = 16,
        /// <summary>
        /// 보물 조각
        /// </summary>
        TreasurePiece = 17,
        /// <summary>
        /// 보물
        /// </summary>
        Treasure = 18,
        /// <summary>
        /// 토너먼트 티켓
        /// </summary>
        TicketTournament = 19,
        /// <summary>
        /// 패스
        /// </summary>
        Pass = 20,
        Max = 21,
    }

    /// <summary>
    /// 아이템 등급
    /// </summary>
    public enum ItemGrade
    {
        /// <summary>
        /// 일반
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 고급
        /// </summary>
        Elite = 1,
        /// <summary>
        /// 희귀
        /// </summary>
        General = 2,
        /// <summary>
        /// 명품
        /// </summary>
        Hero = 3,
        /// <summary>
        /// 국보
        /// </summary>
        Legend = 4,
    }

    /// <summary>
    /// 아이템 식별자 (값은 s_item.idx)
    /// </summary>
    public enum ItemKey
    {
        /// <summary>
        /// 군량
        /// </summary>
        Rice = 1,
        /// <summary>
        /// 무료 금화
        /// </summary>
        GoldFree = 2,
        /// <summary>
        /// 유료 금화
        /// </summary>
        GoldPaid = 3,
        /// <summary>
        /// 시간석
        /// </summary>
        TimeStone = 4,
        /// <summary>
        /// 군량 주머니 일반
        /// </summary>
        PocketRiceNormal = 5,
        /// <summary>
        /// 군량 주머니 고급
        /// </summary>
        PocketRiceElite = 6,
        /// <summary>
        /// 군량 주머니 희귀
        /// </summary>
        PocketRiceGeneral = 7,
        /// <summary>
        /// 군량 주머니 명품
        /// </summary>
        PocketRiceHero = 8,
        /// <summary>
        /// 군량 주머니 국보
        /// </summary>
        PocketRiceLegend = 9,
        /// <summary>
        /// 금화 주머니 일반
        /// </summary>
        PocketGoldNormal = 10,
        /// <summary>
        /// 금화 주머니 고급
        /// </summary>
        PocketGoldElite = 11,
        /// <summary>
        /// 금화 주머니 희귀
        /// </summary>
        PocketGoldGeneral = 12,
        /// <summary>
        /// 금화 주머니 명품
        /// </summary>
        PocketGoldHero = 13,
        /// <summary>
        /// 금화 주머니 국보
        /// </summary>
        PocketGoldLegend = 14,
        /// <summary>
        /// 시간석 주머니 일반
        /// </summary>
        PocketTimeStoneNormal = 15,
        /// <summary>
        /// 시간석 주머니 고급
        /// </summary>
        PocketTimeStoneElite = 16,
        /// <summary>
        /// 시간석 주머니 희귀
        /// </summary>
        PocketTimeStoneGeneral = 17,
        /// <summary>
        /// 시간석 주머니 명품
        /// </summary>
        PocketTimeStoneHero = 18,
        /// <summary>
        /// 시간석 주머니 국보
        /// </summary>
        PocketTimeStoneLegend = 19,
        /// <summary>
        /// 클래스 영혼석 랜덤 상자 일반
        /// </summary>
        RandomBoxSoulStoneClassNormal = 20,
        /// <summary>
        /// 클래스 영혼석 랜덤 상자 고급
        /// </summary>
        RandomBoxSoulStoneClassElite = 21,
        /// <summary>
        /// 클래스 영혼석 랜덤 상자 희귀
        /// </summary>
        RandomBoxSoulStoneClassGeneral = 22,
        /// <summary>
        /// 클래스 영혼석 랜덤 상자 명품
        /// </summary>
        RandomBoxSoulStoneClassHero = 23,
        /// <summary>
        /// 클래스 영혼석 랜덤 상자 국보
        /// </summary>
        RandomBoxSoulStoneClassLegend = 24,
        /// <summary>
        /// 전용 영혼석 랜덤 상자 일반
        /// </summary>
        RandomBoxSoulStoneDedicatedNormal = 25,
        /// <summary>
        /// 전용 영혼석 랜덤 상자 고급
        /// </summary>
        RandomBoxSoulStoneDedicatedElite = 26,
        /// <summary>
        /// 전용 영혼석 랜덤 상자 희귀
        /// </summary>
        RandomBoxSoulStoneDedicatedGeneral = 27,
        /// <summary>
        /// 전용 영혼석 랜덤 상자 명품
        /// </summary>
        RandomBoxSoulStoneDedicatedHero = 28,
        /// <summary>
        /// 전용 영혼석 랜덤 상자 국보
        /// </summary>
        RandomBoxSoulStoneDedicatedLegend = 29,
        /// <summary>
        /// 보물 파편 랜덤 상자 일반
        /// </summary>
        RandomBoxTreasurePieceNormal = 30,
        /// <summary>
        /// 보물 파편 랜덤 상자 고급
        /// </summary>
        RandomBoxTreasurePieceElite = 31,
        /// <summary>
        /// 보물 파편 랜덤 상자 희귀
        /// </summary>
        RandomBoxTreasurePieceGeneral = 32,
        /// <summary>
        /// 보물 파편 랜덤 상자 명품
        /// </summary>
        RandomBoxTreasurePieceHero = 33,
        /// <summary>
        /// 보물 파편 랜덤 상자 국보
        /// </summary>
        RandomBoxTreasurePieceLegend = 34,
        /// <summary>
        /// 일반 연회권
        /// </summary>
        TicketGachaNormal = 35,
        /// <summary>
        /// 고급 연회권
        /// </summary>
        TicketGachaPremium = 36,
        /// <summary>
        /// 레이드 포인트
        /// </summary>
        PointRaid = 37,
        /// <summary>
        /// 토너먼트 포인트
        /// </summary>
        PointTournament = 38,
        /// <summary>
        /// 공용 영혼석
        /// </summary>
        SoulStonePublic = 39,
        /// <summary>
        /// 조조 전용 영혼석
        /// </summary>
        SoulStoneDedicatedCaoCao = 40,
        /// <summary>
        /// 조인 전용 영혼석
        /// </summary>
        SoulStoneDedicatedCaoRen = 41,
        /// <summary>
        /// 하후돈 전용 영혼석
        /// </summary>
        SoulStoneDedicatedXiahouDun = 42,
        /// <summary>
        /// 장료 전용 영혼석
        /// </summary>
        SoulStoneDedicatedZhangLiao = 43,
        /// <summary>
        /// 하후연 전용 영혼석
        /// </summary>
        SoulStoneDedicatedXiahouYuan = 44,
        /// <summary>
        /// 순욱 전용 영혼석
        /// </summary>
        SoulStoneDedicatedXunYu = 45,
        /// <summary>
        /// 유비 전용 영혼석
        /// </summary>
        SoulStoneDedicatedLiuBei = 46,
        /// <summary>
        /// 관우 전용 영혼석
        /// </summary>
        SoulStoneDedicatedGuanYu = 47,
        /// <summary>
        /// 장비 전용 영혼석
        /// </summary>
        SoulStoneDedicatedZhangFei = 48,
        /// <summary>
        /// 조운 전용 영혼석
        /// </summary>
        SoulStoneDedicatedZhaoYun = 49,
        /// <summary>
        /// 황충 전용 영혼석
        /// </summary>
        SoulStoneDedicatedHuangZhong = 50,
        /// <summary>
        /// 제갈량 전용 영혼석
        /// </summary>
        SoulStoneDedicatedZhugeLiang = 51,
        /// <summary>
        /// 손견 전용 영혼석
        /// </summary>
        SoulStoneDedicatedSunJian = 52,
        /// <summary>
        /// 손권 전용 영혼석
        /// </summary>
        SoulStoneDedicatedSunQuan = 53,
        /// <summary>
        /// 황개 전용 영혼석
        /// </summary>
        SoulStoneDedicatedHuangGai = 54,
        /// <summary>
        /// 손책 전용 영혼석
        /// </summary>
        SoulStoneDedicatedSunCe = 55,
        /// <summary>
        /// 태사자 전용 영혼석
        /// </summary>
        SoulStoneDedicatedTaishiCi = 56,
        /// <summary>
        /// 한당 전용 영혼석
        /// </summary>
        SoulStoneDedicatedHanDang = 57,
        /// <summary>
        /// 주유 전용 영혼석
        /// </summary>
        SoulStoneDedicatedZhouYu = 58,
        /// <summary>
        /// 여포 전용 영혼석
        /// </summary>
        SoulStoneDedicatedLuBu = 59,
        /// <summary>
        /// 지휘관 클래스 영혼석
        /// </summary>
        SoulStoneClassCommander = 60,
        /// <summary>
        /// 용장 클래스 영혼석
        /// </summary>
        SoulStoneClassChampion = 61,
        /// <summary>
        /// 선봉장 클래스 영혼석
        /// </summary>
        SoulStoneClassVanguard = 62,
        /// <summary>
        /// 추격자 클래스 영혼석
        /// </summary>
        SoulStoneClassChaser = 63,
        /// <summary>
        /// 궁장 클래스 영혼석
        /// </summary>
        SoulStoneClassArcher = 64,
        /// <summary>
        /// 책사 클래스 영혼석
        /// </summary>
        SoulStoneClassStrategist = 65,
        /// <summary>
        /// 보물 마일리지
        /// </summary>
        TreasureMileage = 66,
        /// <summary>
        /// 육도 조각
        /// </summary>
        TreasurePieceLiutao = 67,
        /// <summary>
        /// 삼략 조각
        /// </summary>
        TreasurePieceSanlue = 68,
        /// <summary>
        /// 위료자 조각
        /// </summary>
        TreasurePieceWeiliaozi = 69,
        /// <summary>
        /// 장수기 조각
        /// </summary>
        TreasurePieceCommandersBanner = 70,
        /// <summary>
        /// 호부 조각
        /// </summary>
        TreasurePieceTigerTally = 71,
        /// <summary>
        /// 금고 조각
        /// </summary>
        TreasurePieceWarDrumGong = 72,
        /// <summary>
        /// 사마법 조각
        /// </summary>
        TreasurePieceSimaFa = 73,
        /// <summary>
        /// 오자 조각
        /// </summary>
        TreasurePieceWuzi = 74,
        /// <summary>
        /// 적벽의 화염 조각
        /// </summary>
        TreasurePieceRedCliffFlame = 75,
        /// <summary>
        /// 방천화극 파편 조각
        /// </summary>
        TreasurePieceBangcheonhwagugShard = 76,
        /// <summary>
        /// 간장막야 조각
        /// </summary>
        TreasurePieceGanjiangMoye = 77,
        /// <summary>
        /// 순구 조각
        /// </summary>
        TreasurePieceChungou = 78,
        /// <summary>
        /// 담로 조각
        /// </summary>
        TreasurePieceZhanlu = 79,
        /// <summary>
        /// 어장 조각
        /// </summary>
        TreasurePieceYuchang = 80,
        /// <summary>
        /// 태아 조각
        /// </summary>
        TreasurePieceTaie = 81,
        /// <summary>
        /// 거궐 조각
        /// </summary>
        TreasurePieceJuque = 82,
        /// <summary>
        /// 승영 조각
        /// </summary>
        TreasurePieceShengxie = 83,
        /// <summary>
        /// 군왕궁 조각
        /// </summary>
        TreasurePieceLordsWarBow = 84,
        /// <summary>
        /// 오장원의 별 조각
        /// </summary>
        TreasurePieceWujangwonStar = 85,
        /// <summary>
        /// 손자병법 조각
        /// </summary>
        TreasurePieceArtOfWar = 86,
        /// <summary>
        /// 기문둔갑 조각
        /// </summary>
        TreasurePieceQimenDunjia = 87,
        /// <summary>
        /// 주역 조각
        /// </summary>
        TreasurePieceIChing = 88,
        /// <summary>
        /// 귀곡자 조각
        /// </summary>
        TreasurePieceGuiguzi = 89,
        /// <summary>
        /// 관자 조각
        /// </summary>
        TreasurePieceGuanzi = 90,
        /// <summary>
        /// 한비자 조각
        /// </summary>
        TreasurePieceHanFeizi = 91,
        /// <summary>
        /// 황석공소서 조각
        /// </summary>
        TreasurePieceSuShuOfHuangshi = 92,
        /// <summary>
        /// 묵자 조각
        /// </summary>
        TreasurePieceMozi = 93,
        /// <summary>
        /// 황제의 인장 조각
        /// </summary>
        TreasurePieceEmperorsSeal = 94,
        /// <summary>
        /// 상군서 조각
        /// </summary>
        TreasurePieceBookOfLordShang = 95,
        /// <summary>
        /// 여씨춘추 조각
        /// </summary>
        TreasurePieceLushiChunqiu = 96,
        /// <summary>
        /// 논어 조각
        /// </summary>
        TreasurePieceAnalects = 97,
        /// <summary>
        /// 정전 조각
        /// </summary>
        TreasurePieceWeiAdministrativeCode = 98,
        /// <summary>
        /// 전국책 조각
        /// </summary>
        TreasurePieceStratagemsOfWarringStates = 99,
        /// <summary>
        /// 옥새 조각
        /// </summary>
        TreasurePieceImperialJadeSeal = 100,
        /// <summary>
        /// 군목 인장 조각
        /// </summary>
        TreasurePiecePrefectsOfficialSeal = 101,
        /// <summary>
        /// 황노백서 조각
        /// </summary>
        TreasurePieceHuanglaoSilkManuscript = 102,
        /// <summary>
        /// 도원의 술잔 조각
        /// </summary>
        TreasurePieceDoewonCup = 103,
        /// <summary>
        /// 화씨벽 조각
        /// </summary>
        TreasurePieceHesJadeDisc = 104,
        /// <summary>
        /// 산해경 조각
        /// </summary>
        TreasurePieceClassicOfMountainsAndSeas = 105,
        /// <summary>
        /// 현학금 조각
        /// </summary>
        TreasurePieceXuanheQin = 106,
        /// <summary>
        /// 봉황패 조각
        /// </summary>
        TreasurePiecePhoenixJadePendant = 107,
        /// <summary>
        /// 예기 조각
        /// </summary>
        TreasurePieceBookOfRites = 108,
        /// <summary>
        /// 연환서 조각
        /// </summary>
        TreasurePieceAllianceLetter = 109,
        /// <summary>
        /// 하도낙서 조각
        /// </summary>
        TreasurePieceHetuLuoshu = 110,
        /// <summary>
        /// 서왕모도 조각
        /// </summary>
        TreasurePieceMapOfQueenMotherOfTheWest = 111,
        /// <summary>
        /// 육도 완제품
        /// </summary>
        TreasureLiutao = 112,
        /// <summary>
        /// 삼략 완제품
        /// </summary>
        TreasureSanlue = 113,
        /// <summary>
        /// 위료자 완제품
        /// </summary>
        TreasureWeiliaozi = 114,
        /// <summary>
        /// 장수기 완제품
        /// </summary>
        TreasureCommandersBanner = 115,
        /// <summary>
        /// 호부 완제품
        /// </summary>
        TreasureTigerTally = 116,
        /// <summary>
        /// 금고 완제품
        /// </summary>
        TreasureWarDrumGong = 117,
        /// <summary>
        /// 사마법 완제품
        /// </summary>
        TreasureSimaFa = 118,
        /// <summary>
        /// 오자 완제품
        /// </summary>
        TreasureWuzi = 119,
        /// <summary>
        /// 적벽의 화염 완제품
        /// </summary>
        TreasureRedCliffFlame = 120,
        /// <summary>
        /// 방천화극 파편 완제품
        /// </summary>
        TreasureBangcheonhwagugShard = 121,
        /// <summary>
        /// 간장막야 완제품
        /// </summary>
        TreasureGanjiangMoye = 122,
        /// <summary>
        /// 순구 완제품
        /// </summary>
        TreasureChungou = 123,
        /// <summary>
        /// 담로 완제품
        /// </summary>
        TreasureZhanlu = 124,
        /// <summary>
        /// 어장 완제품
        /// </summary>
        TreasureYuchang = 125,
        /// <summary>
        /// 태아 완제품
        /// </summary>
        TreasureTaie = 126,
        /// <summary>
        /// 거궐 완제품
        /// </summary>
        TreasureJuque = 127,
        /// <summary>
        /// 승영 완제품
        /// </summary>
        TreasureShengxie = 128,
        /// <summary>
        /// 군왕궁 완제품
        /// </summary>
        TreasureLordsWarBow = 129,
        /// <summary>
        /// 오장원의 별 완제품
        /// </summary>
        TreasureWujangwonStar = 130,
        /// <summary>
        /// 손자병법 완제품
        /// </summary>
        TreasureArtOfWar = 131,
        /// <summary>
        /// 기문둔갑 완제품
        /// </summary>
        TreasureQimenDunjia = 132,
        /// <summary>
        /// 주역 완제품
        /// </summary>
        TreasureIChing = 133,
        /// <summary>
        /// 귀곡자 완제품
        /// </summary>
        TreasureGuiguzi = 134,
        /// <summary>
        /// 관자 완제품
        /// </summary>
        TreasureGuanzi = 135,
        /// <summary>
        /// 한비자 완제품
        /// </summary>
        TreasureHanFeizi = 136,
        /// <summary>
        /// 황석공소서 완제품
        /// </summary>
        TreasureSuShuOfHuangshi = 137,
        /// <summary>
        /// 묵자 완제품
        /// </summary>
        TreasureMozi = 138,
        /// <summary>
        /// 황제의 인장 완제품
        /// </summary>
        TreasureEmperorsSeal = 139,
        /// <summary>
        /// 상군서 완제품
        /// </summary>
        TreasureBookOfLordShang = 140,
        /// <summary>
        /// 여씨춘추 완제품
        /// </summary>
        TreasureLushiChunqiu = 141,
        /// <summary>
        /// 논어 완제품
        /// </summary>
        TreasureAnalects = 142,
        /// <summary>
        /// 정전 완제품
        /// </summary>
        TreasureWeiAdministrativeCode = 143,
        /// <summary>
        /// 전국책 완제품
        /// </summary>
        TreasureStratagemsOfWarringStates = 144,
        /// <summary>
        /// 옥새 완제품
        /// </summary>
        TreasureImperialJadeSeal = 145,
        /// <summary>
        /// 군목 인장 완제품
        /// </summary>
        TreasurePrefectsOfficialSeal = 146,
        /// <summary>
        /// 황노백서 완제품
        /// </summary>
        TreasureHuanglaoSilkManuscript = 147,
        /// <summary>
        /// 도원의 술잔 완제품
        /// </summary>
        TreasureDoewonCup = 148,
        /// <summary>
        /// 화씨벽 완제품
        /// </summary>
        TreasureHesJadeDisc = 149,
        /// <summary>
        /// 산해경 완제품
        /// </summary>
        TreasureClassicOfMountainsAndSeas = 150,
        /// <summary>
        /// 현학금 완제품
        /// </summary>
        TreasureXuanheQin = 151,
        /// <summary>
        /// 봉황패 완제품
        /// </summary>
        TreasurePhoenixJadePendant = 152,
        /// <summary>
        /// 예기 완제품
        /// </summary>
        TreasureBookOfRites = 153,
        /// <summary>
        /// 연환서 완제품
        /// </summary>
        TreasureAllianceLetter = 154,
        /// <summary>
        /// 하도낙서 완제품
        /// </summary>
        TreasureHetuLuoshu = 155,
        /// <summary>
        /// 서왕모도 완제품
        /// </summary>
        TreasureMapOfQueenMotherOfTheWest = 156,
        /// <summary>
        /// 토너먼트 티켓
        /// </summary>
        TicketTournament = 157,
        /// <summary>
        /// 패스
        /// </summary>
        PassBattle = 158,
    }

    /// <summary>
    /// 아이템 타입
    /// </summary>
    public enum ItemType
    {
        /// <summary>
        /// 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 재화
        /// </summary>
        Currency = 0,
        /// <summary>
        /// 영혼석
        /// </summary>
        SoulStone = 1,
        /// <summary>
        /// 번들 (주머니·랜덤 상자)
        /// </summary>
        Bundle = 2,
        /// <summary>
        /// 아이템
        /// </summary>
        Item = 4,
        /// <summary>
        /// 보물 파편
        /// </summary>
        TreasurePiece = 5,
        /// <summary>
        /// 연회권
        /// </summary>
        TicketGacha = 6,
        /// <summary>
        /// 보물
        /// </summary>
        Treasure = 7,
        /// <summary>
        /// 입장권
        /// </summary>
        TicketContents = 8,
        /// <summary>
        /// 패스
        /// </summary>
        Pass = 9,
        Max = 10,
    }

    /// <summary>
    /// 구매한도 초기화 주기
    /// </summary>
    public enum LimitResetType
    {
        /// <summary>
        /// 일일 (빈칸일 때 기본값)
        /// </summary>
        Daily = 0,
        /// <summary>
        /// 주간
        /// </summary>
        Weekly = 1,
        /// <summary>
        /// 시즌
        /// </summary>
        Season = 2,
        /// <summary>
        /// 영구 (초기화 없음)
        /// </summary>
        Permanent = 3,
    }

    /// <summary>
    /// 미션 등급
    /// </summary>
    public enum MissionGrade
    {
        /// <summary>
        /// 일반
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 명장
        /// </summary>
        General = 1,
        /// <summary>
        /// 전설
        /// </summary>
        Legend = 2,
    }

    /// <summary>
    /// 네비게이션
    /// </summary>
    public enum Navigation
    {
        /// <summary>
        /// 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 장수관리
        /// </summary>
        Character = 0,
        /// <summary>
        /// 영지
        /// </summary>
        Castle = 1,
        /// <summary>
        /// 요일던전
        /// </summary>
        Dungeon = 2,
        /// <summary>
        /// 상점
        /// </summary>
        Shop = 3,
        /// <summary>
        /// 연회
        /// </summary>
        Gacha = 4,
        /// <summary>
        /// 스토리모드
        /// </summary>
        Story = 5,
        /// <summary>
        /// 레이드
        /// </summary>
        Raid = 6,
        /// <summary>
        /// 프로필
        /// </summary>
        Profile = 7,
        /// <summary>
        /// 토너먼트
        /// </summary>
        Tournament = 8,
        /// <summary>
        /// 인벤토리
        /// </summary>
        Inventory = 9,
    }

    /// <summary>
    /// 로그인 메타데이터에 기록하는 클라이언트 실행 플랫폼.
    /// </summary>
    public enum OsType
    {
        /// <summary>
        /// Android 앱
        /// </summary>
        Aos = 1,
        /// <summary>
        /// iOS 앱
        /// </summary>
        Ios = 2,
        /// <summary>
        /// APK 배포 앱
        /// </summary>
        Apk = 3,
        /// <summary>
        /// Unity WebGL 클라이언트
        /// </summary>
        Webgl = 4,
        /// <summary>
        /// 일반 웹 클라이언트
        /// </summary>
        Web = 5,
    }

    /// <summary>
    /// 상점 상품 결제에 사용하는 재화 종류
    /// </summary>
    public enum PayType
    {
        /// <summary>
        /// 군량 결제
        /// </summary>
        Rice = 0,
        /// <summary>
        /// 무료 금화 결제
        /// </summary>
        GoldFree = 1,
        /// <summary>
        /// 유료 금화 결제
        /// </summary>
        GoldPaid = 2,
        /// <summary>
        /// 레이드 포인트 결제
        /// </summary>
        PointRaid = 3,
        /// <summary>
        /// 토너먼트 포인트 결제
        /// </summary>
        PointTournament = 4,
        /// <summary>
        /// 현금 결제
        /// </summary>
        Cash = 5,
        /// <summary>
        /// 광고 결제
        /// </summary>
        Ad = 6,
    }

    /// <summary>
    /// 직책 분류
    /// </summary>
    public enum PositionCategory
    {
        /// <summary>
        /// 수장
        /// </summary>
        Leader = 0,
        /// <summary>
        /// 관직
        /// </summary>
        Rank = 1,
        /// <summary>
        /// 칭호
        /// </summary>
        Title = 2,
    }

    /// <summary>
    /// 직책 장착 조건 종류
    /// </summary>
    public enum PositionEquipConditionType
    {
        /// <summary>
        /// 무장 등급
        /// </summary>
        CharacterGrade = 0,
        /// <summary>
        /// 무장 성장 단계
        /// </summary>
        CharacterGrowthStage = 1,
    }

    /// <summary>
    /// 직책 해금 조건 종류
    /// </summary>
    public enum PositionUnlockConditionType
    {
        /// <summary>
        /// 해금 조건 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 모든 무장 클래스마다 전설 등급 무장을 설정 인원 이상 보유
        /// </summary>
        AllCharacterClassGradeOwned = 0,
        /// <summary>
        /// 책사 외 전설 등급 무장을 설정 인원 이상 보유
        /// </summary>
        NonStrategistCharacterGradeOwned = 1,
        /// <summary>
        /// 책사 클래스에서 직책별 고정 등급 이상 무장을 설정 인원 이상 보유
        /// </summary>
        StrategistCharacterGradeOwned = 2,
        /// <summary>
        /// 궁성 레벨이 설정값 이상
        /// </summary>
        PalaceLevelReached = 3,
        /// <summary>
        /// 관아 레벨이 설정값 이상
        /// </summary>
        OfficeLevelReached = 4,
        /// <summary>
        /// 레이드 누적 참여 횟수가 설정값 이상
        /// </summary>
        RaidPlayCountReached = 5,
        /// <summary>
        /// 요일던전 누적 참여 횟수가 설정값 이상
        /// </summary>
        DailyDungeonPlayCountReached = 6,
        /// <summary>
        /// 토너먼트 누적 참여 횟수가 설정값 이상
        /// </summary>
        TournamentPlayCountReached = 7,
        /// <summary>
        /// 적 누적 처치 횟수가 설정값 이상
        /// </summary>
        EnemyKillCountReached = 8,
        /// <summary>
        /// 스킬 누적 사용 횟수가 설정값 이상
        /// </summary>
        SkillUseCountReached = 9,
        /// <summary>
        /// 지휘관 클래스의 정예 등급 무장을 설정 인원 이상 보유
        /// </summary>
        CommanderCharacterGradeOwned = 10,
        /// <summary>
        /// 용장 클래스의 정예 등급 무장을 설정 인원 이상 보유
        /// </summary>
        ChampionCharacterGradeOwned = 11,
        /// <summary>
        /// 선봉장 클래스의 정예 등급 무장을 설정 인원 이상 보유
        /// </summary>
        VanguardCharacterGradeOwned = 12,
        /// <summary>
        /// 추격자 클래스의 정예 등급 무장을 설정 인원 이상 보유
        /// </summary>
        ChaserCharacterGradeOwned = 13,
        /// <summary>
        /// 궁장 클래스의 정예 등급 무장을 설정 인원 이상 보유
        /// </summary>
        ArcherCharacterGradeOwned = 14,
    }

    /// <summary>
    /// 퀘스트 기간 타입
    /// </summary>
    public enum QuestDateType
    {
        /// <summary>
        /// 일일
        /// </summary>
        Daily = 0,
        /// <summary>
        /// 주간
        /// </summary>
        Weekly = 1,
        /// <summary>
        /// 시즌
        /// </summary>
        Season = 2,
    }

    /// <summary>
    /// 미션 타입
    /// </summary>
    public enum QuestType
    {
        None = -1,
        /// <summary>
        /// 로그인
        /// </summary>
        Login = 0,
        /// <summary>
        /// 적 처치하기
        /// </summary>
        EnemyKill = 1,
        /// <summary>
        /// 토너먼트 참여하기
        /// </summary>
        TournamentPlay = 2,
        /// <summary>
        /// 레이드 참여하기
        /// </summary>
        RaidPlay = 3,
        /// <summary>
        /// 연회 진행하기
        /// </summary>
        GachaProceed = 4,
        /// <summary>
        /// 군량 수확하기
        /// </summary>
        RiceClaim = 5,
        /// <summary>
        /// 금화 수확하기
        /// </summary>
        GoldClaim = 6,
        /// <summary>
        /// 관아 파견하기
        /// </summary>
        OfficeDispatch = 7,
        /// <summary>
        /// 요일 던전 플레이하기
        /// </summary>
        DailyDungeonPlay = 8,
        /// <summary>
        /// 스테이지 보스 처치하기
        /// </summary>
        StageBossKill = 9,
        /// <summary>
        /// 광고 시청하기
        /// </summary>
        AdsWatch = 10,
        /// <summary>
        /// 상품 구매하기
        /// </summary>
        ItemBuy = 11,
        /// <summary>
        /// 아이템 사용하기
        /// </summary>
        ItemUse = 12,
        Max = 13,
    }

    /// <summary>
    /// 레이드 랭킹 티어 타입
    /// </summary>
    public enum RaidRankTierType
    {
        /// <summary>
        /// 정확한 순위
        /// </summary>
        Rank = 0,
        /// <summary>
        /// 퍼센타일 구간
        /// </summary>
        Percent = 1,
    }

    /// <summary>
    /// 레이드 구간 타입
    /// </summary>
    public enum RaidRankType
    {
        /// <summary>
        /// 정확한 순위 구간
        /// </summary>
        Rank = 0,
        /// <summary>
        /// 상위 백분위 구간
        /// </summary>
        Percent = 1,
    }

    /// <summary>
    /// 게임 시작 지역 (클라이언트 RegionType과 숫자 일치)
    /// </summary>
    public enum RegionType
    {
        /// <summary>
        /// 미선택 (API body에서는 허용하지 않고 DB는 null 사용)
        /// </summary>
        None = -1,
        /// <summary>
        /// 위 지역
        /// </summary>
        Wei = 0,
        /// <summary>
        /// 촉 지역
        /// </summary>
        Shu = 1,
        /// <summary>
        /// 오 지역
        /// </summary>
        Wu = 2,
        /// <summary>
        /// 기타 지역 (초기 선택 API 불가)
        /// </summary>
        Etc = 3,
        /// <summary>
        /// 클라이언트 UI 범위 sentinel (초기 선택 API 불가)
        /// </summary>
        Max = 4,
        /// <summary>
        /// 역사 분류 (초기 선택 API 불가)
        /// </summary>
        Historical = 5,
    }

    /// <summary>
    /// 스토리 보상 재화 타입
    /// </summary>
    public enum RewardCurrencyType
    {
        /// <summary>
        /// 재화 보상 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 금화
        /// </summary>
        Gold = 0,
    }

    /// <summary>
    /// 상점 카테고리 타입
    /// </summary>
    public enum ShopCategoryType
    {
        /// <summary>
        /// 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 금화
        /// </summary>
        Gold = 0,
        /// <summary>
        /// 군량
        /// </summary>
        Rice = 1,
        /// <summary>
        /// 패키지
        /// </summary>
        Package = 2,
        /// <summary>
        /// 패스
        /// </summary>
        Pass = 3,
        Max = 4,
    }

    /// <summary>
    /// 상점 상품 타입
    /// </summary>
    public enum ShopProductType
    {
        /// <summary>
        /// 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 단일
        /// </summary>
        Single = 0,
        /// <summary>
        /// 패키지
        /// </summary>
        Package = 1,
        /// <summary>
        /// 패스
        /// </summary>
        Pass = 2,
        Max = 3,
    }

    /// <summary>
    /// 등장 트리거
    /// </summary>
    public enum SpawnTrigger
    {
        /// <summary>
        /// 상시 등장
        /// </summary>
        Always = 0,
        /// <summary>
        /// 성문 무력 요구치 미달
        /// </summary>
        GateStrengthLack = 1,
    }

    /// <summary>
    /// 영지 능력치 타입
    /// </summary>
    public enum StatType
    {
        /// <summary>
        /// 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 통솔
        /// </summary>
        Leadership = 0,
        /// <summary>
        /// 무력
        /// </summary>
        Strength = 1,
        /// <summary>
        /// 지력
        /// </summary>
        Intellect = 2,
        /// <summary>
        /// 정치
        /// </summary>
        Politics = 3,
        /// <summary>
        /// 매력
        /// </summary>
        Charisma = 4,
        /// <summary>
        /// 최대
        /// </summary>
        Max = 5,
    }

    /// <summary>
    /// 스토리 노드 타입
    /// </summary>
    public enum StoryNodeType
    {
        /// <summary>
        /// 스토리
        /// </summary>
        Story = 0,
        /// <summary>
        /// 장수 획득
        /// </summary>
        Character = 1,
        /// <summary>
        /// 복합
        /// </summary>
        StoryCharacter = 2,
        /// <summary>
        /// IF 스토리
        /// </summary>
        IfStory = 3,
    }

    /// <summary>
    /// 이용 정지 이력에 기록하는 정지 종류.
    /// </summary>
    public enum SuspendedType
    {
        /// <summary>
        /// 기간이 있는 일시 정지
        /// </summary>
        TemporarySuspended = 2,
        /// <summary>
        /// 영구 이용 정지
        /// </summary>
        PermanentSuspended = 3,
    }

    /// <summary>
    /// 토너먼트 이용 가능 상태
    /// </summary>
    public enum TournamentAvailabilityStatus
    {
        /// <summary>
        /// 이용 가능
        /// </summary>
        Open = 0,
        /// <summary>
        /// 시즌 준비 중
        /// </summary>
        Preparing = 1,
    }

    /// <summary>
    /// 토너먼트 전투 결과
    /// </summary>
    public enum TournamentBattleResult
    {
        /// <summary>
        /// 승리
        /// </summary>
        Win = 0,
        /// <summary>
        /// 패배
        /// </summary>
        Lose = 1,
    }

    /// <summary>
    /// 토너먼트 전투 이력 상태
    /// </summary>
    public enum TournamentBattleStatus
    {
        /// <summary>
        /// 진행 중
        /// </summary>
        Active = 0,
        /// <summary>
        /// 정산 완료
        /// </summary>
        Completed = 1,
        /// <summary>
        /// 포기
        /// </summary>
        Abandoned = 2,
        /// <summary>
        /// 만료
        /// </summary>
        Expired = 3,
    }

    /// <summary>
    /// 특성 등급
    /// </summary>
    public enum TraitsGrade
    {
        /// <summary>
        /// 일반
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 명장
        /// </summary>
        General = 1,
        /// <summary>
        /// 전설
        /// </summary>
        Legend = 2,
    }

    /// <summary>
    /// 특성 수치 등급
    /// </summary>
    public enum TraitsValueGrade
    {
        /// <summary>
        /// 일반
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 정예
        /// </summary>
        Elite = 1,
        /// <summary>
        /// 명장
        /// </summary>
        General = 2,
        /// <summary>
        /// 영웅
        /// </summary>
        Hero = 3,
        /// <summary>
        /// 전설
        /// </summary>
        Legend = 4,
    }

    /// <summary>
    /// 사용자에게 귀속되는 재화 종류 (실제 저장 위치는 각 member 설명 참조)
    /// </summary>
    public enum UserAssetType
    {
        /// <summary>
        /// 군량 (user_asset.rice)
        /// </summary>
        Rice = 0,
        /// <summary>
        /// 무료 금화 (user_asset.gold_free)
        /// </summary>
        GoldFree = 1,
        /// <summary>
        /// 유료 금화 (user_asset.gold_paid)
        /// </summary>
        GoldPaid = 2,
        /// <summary>
        /// 레이드 시즌 재화 (user_raid_wallet.balance, 일반 user_asset과 별도 저장)
        /// </summary>
        PointRaid = 3,
        /// <summary>
        /// 시즌이 바뀌어도 유지되는 토너먼트 재화 (user_asset.point_tournament)
        /// </summary>
        PointTournament = 4,
        /// <summary>
        /// 시간석 (user_asset.time_stone)
        /// </summary>
        TimeStone = 5,
    }
}
