// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SAscension
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 등급
        /// </summary>
        [JsonProperty("character_grade", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.CharacterGrade CharacterGrade { get; set; } = default!;
        /// <summary>
        /// 해당 등급 도달 시 별도로 소비하는 수량 일반 등급은 최초 무장 획득 비용 여러 등급 승급은 현재 다음 등급부터 목표까지 합산 전용 → 같은 클래스 → 공용 영혼석 순서로 자동 사용
        /// </summary>
        [JsonProperty("material_count", NullValueHandling = NullValueHandling.Include)]
        public int MaterialCount { get; set; } = default!;
        /// <summary>
        /// 특성 슬롯 해금 개수 증분값 (명장부터 개방)
        /// </summary>
        [JsonProperty("traits_slot", NullValueHandling = NullValueHandling.Include)]
        public int TraitsSlot { get; set; } = default!;
        /// <summary>
        /// 이 등급으로 승급 시 해금되는 슬롯에서 등장 가능한 traits_grade 목록 예: ["normal","general"], ["legend"] 빈 배열 []=해금되는 슬롯 없음
        /// </summary>
        [JsonProperty("unlock_slot_grades", NullValueHandling = NullValueHandling.Include)]
        public string UnlockSlotGrades { get; set; } = default!;
        /// <summary>
        /// 유물 강화 최대 단계 (이 등급 달성 시 해방되는 상한)
        /// </summary>
        [JsonProperty("relic_enhance_maximum", NullValueHandling = NullValueHandling.Include)]
        public int RelicEnhanceMaximum { get; set; } = default!;
    }
}
