// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SAscensionStat
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 장수 키 (s_character.key 참조) #key='default'은 모든 캐릭터 공통값 특정 캐릭터 행이 있으면 우선 적용, 없으면 'default' 행 사용 (key, grade) 조합 중복 금지
        /// </summary>
        [JsonProperty("character_key", NullValueHandling = NullValueHandling.Include)]
        public string CharacterKey { get; set; } = default!;
        /// <summary>
        /// 등급
        /// </summary>
        [JsonProperty("grade", NullValueHandling = NullValueHandling.Include)]
        public CharacterGrade Grade { get; set; } = default!;
        /// <summary>
        /// 승급 시 통솔 증가량
        /// </summary>
        [JsonProperty("ascension_leadership_delta", NullValueHandling = NullValueHandling.Include)]
        public int AscensionLeadershipDelta { get; set; } = default!;
        /// <summary>
        /// 승급 시 무력 증가량
        /// </summary>
        [JsonProperty("ascension_strength_delta", NullValueHandling = NullValueHandling.Include)]
        public int AscensionStrengthDelta { get; set; } = default!;
        /// <summary>
        /// 승급 시 지력 증가량
        /// </summary>
        [JsonProperty("ascension_intellect_delta", NullValueHandling = NullValueHandling.Include)]
        public int AscensionIntellectDelta { get; set; } = default!;
        /// <summary>
        /// 승급 시 정치 증가량
        /// </summary>
        [JsonProperty("ascension_politics_delta", NullValueHandling = NullValueHandling.Include)]
        public int AscensionPoliticsDelta { get; set; } = default!;
        /// <summary>
        /// 승급 시 매력 증가량
        /// </summary>
        [JsonProperty("ascension_charisma_delta", NullValueHandling = NullValueHandling.Include)]
        public int AscensionCharismaDelta { get; set; } = default!;
        /// <summary>
        /// 승급 시 공격력 증가량
        /// </summary>
        [JsonProperty("ascension_attack_power_delta", NullValueHandling = NullValueHandling.Include)]
        public int AscensionAttackPowerDelta { get; set; } = default!;
        /// <summary>
        /// 승급 시 방어력 증가량
        /// </summary>
        [JsonProperty("ascension_defence_delta", NullValueHandling = NullValueHandling.Include)]
        public int AscensionDefenceDelta { get; set; } = default!;
        /// <summary>
        /// 승급 시 체력 증가량
        /// </summary>
        [JsonProperty("ascension_health_max_delta", NullValueHandling = NullValueHandling.Include)]
        public int AscensionHealthMaxDelta { get; set; } = default!;
    }
}
