// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SBuilding
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 건물 고유 ID
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 요구 능력치
        /// </summary>
        [JsonProperty("stat_type_1", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.StatType StatType1 { get; set; } = default!;
        /// <summary>
        /// 요구 능력치
        /// </summary>
        [JsonProperty("stat_type_2", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.StatType StatType2 { get; set; } = default!;
        /// <summary>
        /// 최대 레벨
        /// </summary>
        [JsonProperty("max_level", NullValueHandling = NullValueHandling.Include)]
        public int MaxLevel { get; set; } = default!;
    }
}
