// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SBundle
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 아이템 논리 키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 패키지타입
        /// </summary>
        [JsonProperty("bundle_item_type", NullValueHandling = NullValueHandling.Include)]
        public BundleItemType BundleItemType { get; set; } = default!;
        /// <summary>
        /// 번들단계분류
        /// </summary>
        [JsonProperty("item_grade", NullValueHandling = NullValueHandling.Include)]
        public ItemGrade ItemGrade { get; set; } = default!;
        /// <summary>
        /// 지급 최소량 configuration_minimum~ configuration_maximum 사이 랜덤 값 지급
        /// </summary>
        [JsonProperty("configuration_minimum", NullValueHandling = NullValueHandling.Include)]
        public int ConfigurationMinimum { get; set; } = default!;
        /// <summary>
        /// 지급 최대량 configuration_minimum~ configuration_maximum 사이 랜덤 값 지급
        /// </summary>
        [JsonProperty("configuration_maximum", NullValueHandling = NullValueHandling.Include)]
        public int ConfigurationMaximum { get; set; } = default!;
        /// <summary>
        /// 주머니(pocket)의 고정 지급 대상 s_item.key 참조. 랜덤 상자(random_box)는 빈 문자열이며 후보는 s_randombox가 소유한다.
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;
    }
}
