// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SCharacter
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 캐릭터 고유 ID
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 소속 국가
        /// </summary>
        [JsonProperty("country", NullValueHandling = NullValueHandling.Include)]
        public Country Country { get; set; } = default!;
        /// <summary>
        /// 클래스
        /// </summary>
        [JsonProperty("character_class", NullValueHandling = NullValueHandling.Include)]
        public CharacterClass CharacterClass { get; set; } = default!;
        /// <summary>
        /// 캐릭터 기본 전투력
        /// </summary>
        [JsonProperty("combat_power_base", NullValueHandling = NullValueHandling.Include)]
        public int CombatPowerBase { get; set; } = default!;
        /// <summary>
        /// 통솔 기본값
        /// </summary>
        [JsonProperty("LEA", NullValueHandling = NullValueHandling.Include)]
        public int LEA { get; set; } = default!;
        /// <summary>
        /// 무력 기본값
        /// </summary>
        [JsonProperty("STR", NullValueHandling = NullValueHandling.Include)]
        public int STR { get; set; } = default!;
        /// <summary>
        /// 지력 기본값
        /// </summary>
        [JsonProperty("INT", NullValueHandling = NullValueHandling.Include)]
        public int INT { get; set; } = default!;
        /// <summary>
        /// 정치 기본값
        /// </summary>
        [JsonProperty("POL", NullValueHandling = NullValueHandling.Include)]
        public int POL { get; set; } = default!;
        /// <summary>
        /// 매력 기본값
        /// </summary>
        [JsonProperty("CHA", NullValueHandling = NullValueHandling.Include)]
        public int CHA { get; set; } = default!;
    }
}
