// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SDailyDungeonClassReward
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// s_daily_dungeon_boss.key 참조
        /// </summary>
        [JsonProperty("daily_dungeon_boss_key", NullValueHandling = NullValueHandling.Include)]
        public string DailyDungeonBossKey { get; set; } = default!;
        /// <summary>
        /// 등급 고유 ID
        /// </summary>
        [JsonProperty("dungeon_boss_grade", NullValueHandling = NullValueHandling.Include)]
        public DungeonBossGrade DungeonBossGrade { get; set; } = default!;
        /// <summary>
        /// s_item.key 참조
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;
        /// <summary>
        /// 지급 수량
        /// </summary>
        [JsonProperty("reward_item_amount", NullValueHandling = NullValueHandling.Include)]
        public int RewardItemAmount { get; set; } = default!;
    }
}
