// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SDailyDungeonGrade
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 보스 등급
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public DungeonBossGrade Key { get; set; } = default!;
        /// <summary>
        /// 체력 배율 (s_character_stat.health_max 기준, 1.0=그대로) 스탯 character_key
        /// </summary>
        [JsonProperty("hp_mul", NullValueHandling = NullValueHandling.Include)]
        public double HpMul { get; set; } = default!;
        /// <summary>
        /// 공격력 배율 (s_character_stat.attack_power 기준, 1.0=그대로) 스탯 character_key
        /// </summary>
        [JsonProperty("atk_mul", NullValueHandling = NullValueHandling.Include)]
        public double AtkMul { get; set; } = default!;
        /// <summary>
        /// 방어력 배율 (s_character_stat.defence 기준, 1.0=그대로) 스탯 character_key
        /// </summary>
        [JsonProperty("def_mul", NullValueHandling = NullValueHandling.Include)]
        public double DefMul { get; set; } = default!;
    }
}
