// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SDailyDungeonBoss
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 보스 고유 ID
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 등장 요일 (1=월, 2=화, 3=수, 4=목, 5=금, 6=토 일요일 자유선택은 서버 로직 처리)
        /// </summary>
        [JsonProperty("weekday", NullValueHandling = NullValueHandling.Include)]
        public int Weekday { get; set; } = default!;
        /// <summary>
        /// s_character.key 참조
        /// </summary>
        [JsonProperty("boss_key", NullValueHandling = NullValueHandling.Include)]
        public string BossKey { get; set; } = default!;
    }
}
