// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SEnemyStat
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 몬스터 고유 ID
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 공격력 기본값
        /// </summary>
        [JsonProperty("attack_power", NullValueHandling = NullValueHandling.Include)]
        public int AttackPower { get; set; } = default!;
        /// <summary>
        /// 방어력 기본값
        /// </summary>
        [JsonProperty("defence", NullValueHandling = NullValueHandling.Include)]
        public int Defence { get; set; } = default!;
        /// <summary>
        /// 공격속도 기본값
        /// </summary>
        [JsonProperty("attack_speed", NullValueHandling = NullValueHandling.Include)]
        public int AttackSpeed { get; set; } = default!;
        /// <summary>
        /// 체력 기본값
        /// </summary>
        [JsonProperty("health_max", NullValueHandling = NullValueHandling.Include)]
        public int HealthMax { get; set; } = default!;
        /// <summary>
        /// 이동속도 기본값
        /// </summary>
        [JsonProperty("move_speed", NullValueHandling = NullValueHandling.Include)]
        public int MoveSpeed { get; set; } = default!;
        /// <summary>
        /// 체력흡수 기본값
        /// </summary>
        [JsonProperty("life_steal", NullValueHandling = NullValueHandling.Include)]
        public int LifeSteal { get; set; } = default!;
        /// <summary>
        /// 치명타 확률 기본값
        /// </summary>
        [JsonProperty("critical_rate", NullValueHandling = NullValueHandling.Include)]
        public int CriticalRate { get; set; } = default!;
        /// <summary>
        /// 재사용 감소 기본값
        /// </summary>
        [JsonProperty("cooldown_rate", NullValueHandling = NullValueHandling.Include)]
        public int CooldownRate { get; set; } = default!;
        /// <summary>
        /// 치명타 위력 기본값
        /// </summary>
        [JsonProperty("critical_damage", NullValueHandling = NullValueHandling.Include)]
        public int CriticalDamage { get; set; } = default!;
    }
}
