// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SFarmEffect
    {
        /// <summary>
        /// 농지 레벨
        /// </summary>
        [JsonProperty("level", NullValueHandling = NullValueHandling.Include)]
        public int Level { get; set; } = default!;
        /// <summary>
        /// 초당 군량 획득량 (50/50 공식 base)
        /// </summary>
        [JsonProperty("rice_per_seconds_base", NullValueHandling = NullValueHandling.Include)]
        public double RicePerSecondsBase { get; set; } = default!;
        /// <summary>
        /// 군량 보유량 한도 (50/50 공식 base)
        /// </summary>
        [JsonProperty("rice_storage_base", NullValueHandling = NullValueHandling.Include)]
        public int RiceStorageBase { get; set; } = default!;
    }
}
