// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SFieldEnemy
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 챕터 번호
        /// </summary>
        [JsonProperty("chapter", NullValueHandling = NullValueHandling.Include)]
        public int Chapter { get; set; } = default!;
        /// <summary>
        /// 스테이지 번호
        /// </summary>
        [JsonProperty("stage", NullValueHandling = NullValueHandling.Include)]
        public int Stage { get; set; } = default!;
        /// <summary>
        /// 페이즈 번호
        /// </summary>
        [JsonProperty("phase", NullValueHandling = NullValueHandling.Include)]
        public int Phase { get; set; } = default!;
        /// <summary>
        /// 유저가 선택한 지역에 따라 등장하는 적 분기 처리 용도 빈칸 = null 1 = 위나라용
        /// </summary>
        [JsonProperty("region_type", NullValueHandling = NullValueHandling.Include)]
        public string RegionType { get; set; } = default!;
        /// <summary>
        /// 등장하는 NormalWarrior 수
        /// </summary>
        [JsonProperty("NormalWarrior", NullValueHandling = NullValueHandling.Include)]
        public int NormalWarrior { get; set; } = default!;
        /// <summary>
        /// 등장하는 NormalArcher 수
        /// </summary>
        [JsonProperty("NormalArcher", NullValueHandling = NullValueHandling.Include)]
        public int NormalArcher { get; set; } = default!;
        /// <summary>
        /// 등장하는 NormalStrategist 수
        /// </summary>
        [JsonProperty("NormalStrategist", NullValueHandling = NullValueHandling.Include)]
        public int NormalStrategist { get; set; } = default!;
        /// <summary>
        /// 보스 key s_character, s_enmey_stat 참조
        /// </summary>
        [JsonProperty("Boss_key", NullValueHandling = NullValueHandling.Include)]
        public string BossKey { get; set; } = default!;
        /// <summary>
        /// 적 소속 국가
        /// </summary>
        [JsonProperty("country_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.Country CountryType { get; set; } = default!;
    }
}
