// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SFieldStage
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 스테이지 인덱스 (1~100)
        /// </summary>
        [JsonProperty("stage_index", NullValueHandling = NullValueHandling.Include)]
        public int StageIndex { get; set; } = default!;
        /// <summary>
        /// 스테이지 시간석 계수
        /// </summary>
        [JsonProperty("time_stone_mul", NullValueHandling = NullValueHandling.Include)]
        public double TimeStoneMul { get; set; } = default!;
    }
}
