// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SFieldEnemy
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 챕터 번호
        /// </summary>
        [JsonProperty("chapter", NullValueHandling = NullValueHandling.Include)]
        public int Chapter { get; set; } = default!;
        /// <summary>
        /// 스테이지 번호
        /// </summary>
        [JsonProperty("stage", NullValueHandling = NullValueHandling.Include)]
        public int Stage { get; set; } = default!;
        /// <summary>
        /// 페이즈 번호
        /// </summary>
        [JsonProperty("phase", NullValueHandling = NullValueHandling.Include)]
        public int Phase { get; set; } = default!;
        /// <summary>
        /// 적 배치가 적용되는 시작 지역 빈칸 = 공통 기본 배치 wei = 위 지역 전용 배치 같은 챕터·스테이지·페이즈에서 유저 시작 지역과 일치하는 행이 있으면 우선 사용하고, 없으면 공통 행을 사용한다. 촉·오는 공통 행을 사용한다.
        /// </summary>
        [JsonProperty("region_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.RegionType? RegionType { get; set; } = default!;
        /// <summary>
        /// 등장하는 NormalWarrior 수
        /// </summary>
        [JsonProperty("normal_warrior_count", NullValueHandling = NullValueHandling.Include)]
        public int NormalWarriorCount { get; set; } = default!;
        /// <summary>
        /// 등장하는 NormalArcher 수
        /// </summary>
        [JsonProperty("normal_archer_count", NullValueHandling = NullValueHandling.Include)]
        public int NormalArcherCount { get; set; } = default!;
        /// <summary>
        /// 등장하는 NormalStrategist 수
        /// </summary>
        [JsonProperty("normal_strategist_count", NullValueHandling = NullValueHandling.Include)]
        public int NormalStrategistCount { get; set; } = default!;
        /// <summary>
        /// 보스 key s_character, s_enemy_stat 참조
        /// </summary>
        [JsonProperty("boss_key", NullValueHandling = NullValueHandling.Include)]
        public string BossKey { get; set; } = default!;
        /// <summary>
        /// 적 소속 국가
        /// </summary>
        [JsonProperty("country_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.Country CountryType { get; set; } = default!;
    }
}
