// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SFieldRewardPool
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 풀 구분 enum field_reward_pool_type 참조
        /// </summary>
        [JsonProperty("pool_key", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.FieldRewardPoolType PoolKey { get; set; } = default!;
        /// <summary>
        /// enum item_key 참조
        /// </summary>
        [JsonProperty("item_key", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ItemKey ItemKey { get; set; } = default!;
        /// <summary>
        /// 추첨 가중치 값이 낮을수록 좋은 항목이다 같은 등급으로 둘 항목에는 같은 값을 준다 최저 가중치가 여럿이면 그중 1건을 균등 확률로 고른다
        /// </summary>
        [JsonProperty("weight", NullValueHandling = NullValueHandling.Include)]
        public int Weight { get; set; } = default!;
        /// <summary>
        /// 이 줄이 등장하기 시작하는 난이도 (1~5) 난이도가 이 값 이상이면 풀에 포함된다 심연2 이상은 5로 보고 판정한다
        /// </summary>
        [JsonProperty("unlock_difficulty", NullValueHandling = NullValueHandling.Include)]
        public int UnlockDifficulty { get; set; } = default!;
        /// <summary>
        /// 이 줄이 당첨됐을 때의 기본 개수 난이도가 올라도 이 값은 변하지 않는다 난이도별로 개수를 다르게 주려면 줄을 따로 추가한다
        /// </summary>
        [JsonProperty("base_count", NullValueHandling = NullValueHandling.Include)]
        public int BaseCount { get; set; } = default!;
        /// <summary>
        /// 보상 개수가 증가하는 방식 (table_enum.field_reward_count_increase_type 참조) 0 = 재화 지급 = base_count × 난이도 보상 계수 × 스테이지 보상 계수 난이도 1부터 매 단계·매 스테이지 증가하므로 난이도별 줄을 두지 않는다 1 = 아이템 지급 = base_count × FIELD_REWARD_POOL_COUNT_INCREASE_MUL ^ max(난이도 인덱스 - 5, 0) 난이도 1~5는 배율이 1이므로 개수 성장은 난이도별 줄로 만든다 2 = 고정 지급 = base_count 난이도가 올라도 개수가 변하지 않는다
        /// </summary>
        [JsonProperty("count_increase_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.FieldRewardCountIncreaseType CountIncreaseType { get; set; } = default!;
    }
}
