// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SFieldRewardPool
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 풀 구분 kill_normal = 처치 보상(일반 적) kill_boss = 처치 보상(보스 적) idle = 방치 보상 그 외 = s_field_object.key
        /// </summary>
        [JsonProperty("pool_key", NullValueHandling = NullValueHandling.Include)]
        public string PoolKey { get; set; } = default!;
        /// <summary>
        /// 난이도 인덱스 (1~5) 심연2 이상은 5번 풀을 그대로 사용한다 상위 풀은 하위 풀의 항목을 모두 포함한다
        /// </summary>
        [JsonProperty("difficulty_index", NullValueHandling = NullValueHandling.Include)]
        public int DifficultyIndex { get; set; } = default!;
        /// <summary>
        /// 지급 아이템 (s_item.key 참조)
        /// </summary>
        [JsonProperty("item_key", NullValueHandling = NullValueHandling.Include)]
        public string ItemKey { get; set; } = default!;
        /// <summary>
        /// 추첨 가중치 값이 낮을수록 좋은 아이템이다 같은 풀 안에서 중복될 수 없다
        /// </summary>
        [JsonProperty("weight", NullValueHandling = NullValueHandling.Include)]
        public int Weight { get; set; } = default!;
        /// <summary>
        /// 지급이 확정됐을 때 지급할 개수
        /// </summary>
        [JsonProperty("base_count", NullValueHandling = NullValueHandling.Include)]
        public int BaseCount { get; set; } = default!;
        /// <summary>
        /// 개수 배율 적용 여부 (0/1) 재화 항목은 0으로 두고 재화별 보상 계수를 적용한다
        /// </summary>
        [JsonProperty("is_count_mul", NullValueHandling = NullValueHandling.Include)]
        public int IsCountMul { get; set; } = default!;
    }
}
