// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SFieldCurrency
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 재화 키 (s_item.key 참조, category=currency)
        /// </summary>
        [JsonProperty("item_key", NullValueHandling = NullValueHandling.Include)]
        public string ItemKey { get; set; } = default!;
        /// <summary>
        /// 난이도 증가율 난이도 1단계당 배수이며, 이 값 하나에서 난이도 보상 계수와 스테이지 보상 계수를 산출한다
        /// </summary>
        [JsonProperty("increase_mul_per_difficulty", NullValueHandling = NullValueHandling.Include)]
        public double IncreaseMulPerDifficulty { get; set; } = default!;
    }
}
