// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SFieldObject
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 오브젝트 고유 키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 페이즈 시작 시 등장 확률 (1=100%) 종류별 독립 판정
        /// </summary>
        [JsonProperty("spawn_rate", NullValueHandling = NullValueHandling.Include)]
        public double SpawnRate { get; set; } = default!;
        /// <summary>
        /// 등장 시점부터의 유지 시간 (초)
        /// </summary>
        [JsonProperty("duration_seconds", NullValueHandling = NullValueHandling.Include)]
        public int DurationSeconds { get; set; } = default!;
    }
}
