// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SFieldEnemyPlacement
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 스테이지 인덱스 (1~100) 0 = 전 스테이지 공통값. 개별 지정이 공통값보다 우선한다
        /// </summary>
        [JsonProperty("stage_index", NullValueHandling = NullValueHandling.Include)]
        public int StageIndex { get; set; } = default!;
        /// <summary>
        /// 페이즈 번호 (1~3)
        /// </summary>
        [JsonProperty("phase_number", NullValueHandling = NullValueHandling.Include)]
        public int PhaseNumber { get; set; } = default!;
        /// <summary>
        /// 적 구분 (table_enum.field_enemy_type 참조)
        /// </summary>
        [JsonProperty("enemy_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.FieldEnemyType EnemyType { get; set; } = default!;
        /// <summary>
        /// 적 개체 키 normal·boss_generic = s_enemy_stat.key boss_character = s_character.key
        /// </summary>
        [JsonProperty("enemy_key", NullValueHandling = NullValueHandling.Include)]
        public string EnemyKey { get; set; } = default!;
        /// <summary>
        /// 마리 수
        /// </summary>
        [JsonProperty("enemy_count", NullValueHandling = NullValueHandling.Include)]
        public int EnemyCount { get; set; } = default!;
    }
}
