// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SGateEffect
    {
        /// <summary>
        /// 성문 레벨
        /// </summary>
        [JsonProperty("level", NullValueHandling = NullValueHandling.Include)]
        public int Level { get; set; } = default!;
        /// <summary>
        /// NPC 유지 시간 (초, 능력치 무관)
        /// </summary>
        [JsonProperty("npc_duration_seconds", NullValueHandling = NullValueHandling.Include)]
        public int NpcDurationSeconds { get; set; } = default!;
    }
}
