// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SGrowth
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 성장 단계
        /// </summary>
        [JsonProperty("stage", NullValueHandling = NullValueHandling.Include)]
        public int Stage { get; set; } = default!;
        /// <summary>
        /// 필요 재료 종류
        /// </summary>
        [JsonProperty("growth_material_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.GrowthMaterialType GrowthMaterialType { get; set; } = default!;
        /// <summary>
        /// 필요 재료 수량
        /// </summary>
        [JsonProperty("material_count", NullValueHandling = NullValueHandling.Include)]
        public int MaterialCount { get; set; } = default!;
        /// <summary>
        /// 성공 확률 (백분율 1=100%)
        /// </summary>
        [JsonProperty("success_rate", NullValueHandling = NullValueHandling.Include)]
        public double SuccessRate { get; set; } = default!;
    }
}
