// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SGuideQuest
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 고유 문자열 키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 체인 순서
        /// </summary>
        [JsonProperty("sort_no", NullValueHandling = NullValueHandling.Include)]
        public int SortNo { get; set; } = default!;
        /// <summary>
        /// 등장 스테이지 (도달) 스테이지에 도달 하지 못하여 출력할 퀘스트가 없을 시에만 s_guide_quest_repeat 퀘스트를 진행한다.
        /// </summary>
        [JsonProperty("start_stage", NullValueHandling = NullValueHandling.Include)]
        public string StartStage { get; set; } = default!;
        /// <summary>
        /// 목표값 (횟수/개수)
        /// </summary>
        [JsonProperty("target_value", NullValueHandling = NullValueHandling.Include)]
        public int TargetValue { get; set; } = default!;
        /// <summary>
        /// 배너 조작 시 이동할 목적지 첫번째 [ none:-1, character:0, castle:1, dungeon:2, shop:3, gacha:4, story:5, raid:6, profile:7, tournament:8 ] 작성 규칙 장소, 세부장소, 세부장소2 세부장소2 규칙(영지) 1=admin 2=etc
        /// </summary>
        [JsonProperty("navigation", NullValueHandling = NullValueHandling.Include)]
        public string Navigation { get; set; } = default!;
        /// <summary>
        /// 개별 보상 아이템 key s_item.key 참조
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;
        /// <summary>
        /// 보상 수량
        /// </summary>
        [JsonProperty("reward_item_amount", NullValueHandling = NullValueHandling.Include)]
        public int RewardItemAmount { get; set; } = default!;
    }
}
