// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SGuideQuestRepeat
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 고유 문자열 키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 체인 순서
        /// </summary>
        [JsonProperty("sort_no", NullValueHandling = NullValueHandling.Include)]
        public int SortNo { get; set; } = default!;
        /// <summary>
        /// 해금 조건 퀘스트 s_guide_quest.key 참조
        /// </summary>
        [JsonProperty("open_guide_quest", NullValueHandling = NullValueHandling.Include)]
        public string OpenGuideQuest { get; set; } = default!;
        /// <summary>
        /// 목표값 (횟수/개수, 게이트=1)
        /// </summary>
        [JsonProperty("target_value", NullValueHandling = NullValueHandling.Include)]
        public int TargetValue { get; set; } = default!;
        /// <summary>
        /// 배너 조작 시 이동할 목적지 [ none:-1, character:0, castle:1, dungeon:2, shop:3, gacha:4, story:5, raid:6, profile:7, tournament:8 ] 작성 규칙 장소, 세부장소, 세부장소2 세부장소2 규칙(영지) 1=admin 2=etc
        /// </summary>
        [JsonProperty("navigation", NullValueHandling = NullValueHandling.Include)]
        public string Navigation { get; set; } = default!;
        /// <summary>
        /// 개별 보상 아이템 key s_item.key 참조
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;
        /// <summary>
        /// 보상 수량
        /// </summary>
        [JsonProperty("reward_count", NullValueHandling = NullValueHandling.Include)]
        public int RewardCount { get; set; } = default!;
    }
}
