// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SIntegrityDebuff
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 디버프 적용 건물 key (s_building.key 참조)
        /// </summary>
        [JsonProperty("building_key", NullValueHandling = NullValueHandling.Include)]
        public string BuildingKey { get; set; } = default!;
        /// <summary>
        /// 청렴도 미충족 시 적용할 디버프 종류
        /// </summary>
        [JsonProperty("debuff_type", NullValueHandling = NullValueHandling.Include)]
        public CastleDebuffType DebuffType { get; set; } = default!;
        /// <summary>
        /// 청렴도 충족률 0%일 때 보장되는 기본 효과 비율; 실제 효과=기본 효과×(minimum_rate+(1-minimum_rate)×청렴도 충족률)
        /// </summary>
        [JsonProperty("minimum_rate", NullValueHandling = NullValueHandling.Include)]
        public double MinimumRate { get; set; } = default!;
    }
}
