// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SItem
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 아이템 논리 키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 아이템 타입. bundle의 세부 종류는 s_bundle.bundle_item_type(pocket/random_box)으로 구분한다.
        /// </summary>
        [JsonProperty("category", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ItemType Category { get; set; } = default!;
        /// <summary>
        /// 아이템 상세 타입 리소스 분류를 위한 타입이다.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ItemDetailType Type { get; set; } = default!;
        /// <summary>
        /// 전용 영혼석 대상 s_character.key. 다른 아이템은 빈 문자열
        /// </summary>
        [JsonProperty("character_key", NullValueHandling = NullValueHandling.Include)]
        public string CharacterKey { get; set; } = default!;
        /// <summary>
        /// 클래스 영혼석 대상 table_enum.character_class member key. 다른 아이템은 빈 문자열
        /// </summary>
        [JsonProperty("character_class_key", NullValueHandling = NullValueHandling.Include)]
        public string CharacterClassKey { get; set; } = default!;
        /// <summary>
        /// 보물 완제품 또는 조각 대상 s_treasure.key. 다른 아이템은 빈 문자열
        /// </summary>
        [JsonProperty("treasure_key", NullValueHandling = NullValueHandling.Include)]
        public string TreasureKey { get; set; } = default!;
        /// <summary>
        /// 주머니 또는 랜덤박스 대상 s_bundle.key 참조 다른 아이템은 빈 문자열
        /// </summary>
        [JsonProperty("bundle_key", NullValueHandling = NullValueHandling.Include)]
        public string BundleKey { get; set; } = default!;
    }
}
