// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SMatch
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 인연 ID
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 소속
        /// </summary>
        [JsonProperty("country", NullValueHandling = NullValueHandling.Include)]
        public Country Country { get; set; } = default!;
        /// <summary>
        /// 구성원 1 (옵셔널, s_character.key 참조)
        /// </summary>
        [JsonProperty("member_1_character_key", NullValueHandling = NullValueHandling.Include)]
        public string Member1CharacterKey { get; set; } = default!;
        /// <summary>
        /// 구성원 2 (옵셔널)
        /// </summary>
        [JsonProperty("member_2_character_key", NullValueHandling = NullValueHandling.Include)]
        public string Member2CharacterKey { get; set; } = default!;
        /// <summary>
        /// 구성원 3 (옵셔널)
        /// </summary>
        [JsonProperty("member_3_character_key", NullValueHandling = NullValueHandling.Include)]
        public string Member3CharacterKey { get; set; } = default!;
        /// <summary>
        /// 구성원 4 (옵셔널)
        /// </summary>
        [JsonProperty("member_4_character_key", NullValueHandling = NullValueHandling.Include)]
        public string Member4CharacterKey { get; set; } = default!;
        /// <summary>
        /// 구성원 5 (옵셔널)
        /// </summary>
        [JsonProperty("member_5_character_key", NullValueHandling = NullValueHandling.Include)]
        public string Member5CharacterKey { get; set; } = default!;
        /// <summary>
        /// 구성원 6 (옵셔널, 최대 6명)
        /// </summary>
        [JsonProperty("member_6_character_key", NullValueHandling = NullValueHandling.Include)]
        public string Member6CharacterKey { get; set; } = default!;
        /// <summary>
        /// 효과 base JSON (노말 기준) 예: {"attack_speed_rate":2} key=스탯 이름, value=노말 기준 수치 여러 스탯 동시 가능 최종값 = effect[stat] × effect_grade[등급]
        /// </summary>
        [JsonProperty("effect", NullValueHandling = NullValueHandling.Include)]
        public string Effect { get; set; } = default!;
        /// <summary>
        /// 등급별 배율 JSON 예: {"normal":1,"elite":1.1,"general":1.3,"hero":1.6,"legend":2} 노말 기준 배율 최종값 = effect[stat] x effect_grade[grade]
        /// </summary>
        [JsonProperty("effect_grade_multiplier", NullValueHandling = NullValueHandling.Include)]
        public string EffectGradeMultiplier { get; set; } = default!;
    }
}
