// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SMerchantEffect
    {
        /// <summary>
        /// 행상 레벨
        /// </summary>
        [JsonProperty("level", NullValueHandling = NullValueHandling.Include)]
        public int Level { get; set; } = default!;
        /// <summary>
        /// 지력 충족률 0% 기준 기본 할인율; 실제 할인율=discount_rate_base×(1+지력 충족률)
        /// </summary>
        [JsonProperty("discount_rate_base", NullValueHandling = NullValueHandling.Include)]
        public double DiscountRateBase { get; set; } = default!;
        /// <summary>
        /// 높은 등급 등장 확률 (충족률 100% 별도 공식, placeholder)
        /// </summary>
        [JsonProperty("grade_up_rate", NullValueHandling = NullValueHandling.Include)]
        public double GradeUpRate { get; set; } = default!;
        /// <summary>
        /// 행상 레벨별 판매 item 수; 능력치와 무관
        /// </summary>
        [JsonProperty("item_count", NullValueHandling = NullValueHandling.Include)]
        public int ItemCount { get; set; } = default!;
    }
}
