// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SNpc
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// NPC ID
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 등장 조건
        /// </summary>
        [JsonProperty("spawn_trigger", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.SpawnTrigger SpawnTrigger { get; set; } = default!;
        /// <summary>
        /// 소멸 시간(초); 0=상시, -1=s_gate_effect.npc_duration_seconds 연동, 양수=고정 시간
        /// </summary>
        [JsonProperty("despawn_seconds", NullValueHandling = NullValueHandling.Include)]
        public int DespawnSeconds { get; set; } = default!;
        /// <summary>
        /// NPC 제거 후 다음 등장 판정 가능 시점까지 최소 cooldown(초); 0=미적용
        /// </summary>
        [JsonProperty("respawn_cooldown_min_seconds", NullValueHandling = NullValueHandling.Include)]
        public int RespawnCooldownMinSeconds { get; set; } = default!;
        /// <summary>
        /// NPC 제거 후 다음 등장 판정 가능 시점까지 최대 cooldown(초); minimum~maximum 범위에서 1회 랜덤 결정
        /// </summary>
        [JsonProperty("respawn_cooldown_max_seconds", NullValueHandling = NullValueHandling.Include)]
        public int RespawnCooldownMaxSeconds { get; set; } = default!;
    }
}
