// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SOfficeEffect
    {
        /// <summary>
        /// 관아 레벨
        /// </summary>
        [JsonProperty("level", NullValueHandling = NullValueHandling.Include)]
        public int Level { get; set; } = default!;
        /// <summary>
        /// 서비스 날짜 1일당 파견 시작 가능 횟수
        /// </summary>
        [JsonProperty("mission_count_per_day", NullValueHandling = NullValueHandling.Include)]
        public int MissionCountPerDay { get; set; } = default!;
        /// <summary>
        /// 청렴도 100% 기준 일반 파견 기본 등장 확률; 실제 일반=1-실제 명장-실제 전설
        /// </summary>
        [JsonProperty("normal_rate", NullValueHandling = NullValueHandling.Include)]
        public double NormalRate { get; set; } = default!;
        /// <summary>
        /// 청렴도 100% 기준 명장 파견 기본 등장 확률; 실제=기본 확률×청렴도 보정계수
        /// </summary>
        [JsonProperty("general_rate", NullValueHandling = NullValueHandling.Include)]
        public double GeneralRate { get; set; } = default!;
        /// <summary>
        /// 청렴도 100% 기준 전설 파견 기본 등장 확률; 실제=기본 확률×청렴도 보정계수
        /// </summary>
        [JsonProperty("legend_rate", NullValueHandling = NullValueHandling.Include)]
        public double LegendRate { get; set; } = default!;
    }
}
