// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SOfficeMissionGrade
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 파견 등급
        /// </summary>
        [JsonProperty("mission_grade", NullValueHandling = NullValueHandling.Include)]
        public MissionGrade MissionGrade { get; set; } = default!;
        /// <summary>
        /// 파견 기본 소요 시간(초)
        /// </summary>
        [JsonProperty("duration_seconds", NullValueHandling = NullValueHandling.Include)]
        public int DurationSeconds { get; set; } = default!;
        /// <summary>
        /// 파견 보상 수령 확정 시 관아에 지급하는 경험치
        /// </summary>
        [JsonProperty("office_xp_reward", NullValueHandling = NullValueHandling.Include)]
        public int OfficeXpReward { get; set; } = default!;
        /// <summary>
        /// 보상 달성률 100%에 필요한 무장 능력치 합
        /// </summary>
        [JsonProperty("req_stat_value", NullValueHandling = NullValueHandling.Include)]
        public int ReqStatValue { get; set; } = default!;
    }
}
