// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SOfficeLevel
    {
        /// <summary>
        /// 관아 레벨
        /// </summary>
        [JsonProperty("level", NullValueHandling = NullValueHandling.Include)]
        public int Level { get; set; } = default!;
        /// <summary>
        /// 직전 레벨에서 해당 레벨 도달에 필요한 파견 경험치
        /// </summary>
        [JsonProperty("req_xp", NullValueHandling = NullValueHandling.Include)]
        public int ReqXp { get; set; } = default!;
    }
}
