// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SPalaceEffect
    {
        /// <summary>
        /// 궁성 레벨
        /// </summary>
        [JsonProperty("level", NullValueHandling = NullValueHandling.Include)]
        public int Level { get; set; } = default!;
        /// <summary>
        /// 궁성 레벨별 시간석 1개 기본 단축 시간(초); 매력 충족률 보정 없음
        /// </summary>
        [JsonProperty("save_seconds_per_time_stone", NullValueHandling = NullValueHandling.Include)]
        public int SaveSecondsPerTimeStone { get; set; } = default!;
        /// <summary>
        /// 궁성 레벨별 광고 1회 기본 단축 시간(초); 매력 충족률 보정 없음
        /// </summary>
        [JsonProperty("save_seconds_per_ad", NullValueHandling = NullValueHandling.Include)]
        public int SaveSecondsPerAd { get; set; } = default!;
    }
}
