// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SParameter
    {
        /// <summary>
        /// 파라미터 키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 값 타입 1=number 2=string type=3: JSON array/object
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Include)]
        public int Type { get; set; } = default!;
        /// <summary>
        /// 실제 값 단일값 또는 JSON 문자열 확률/배율: 1=100%
        /// </summary>
        [JsonProperty("value", NullValueHandling = NullValueHandling.Include)]
        public string Value { get; set; } = default!;
    }
}
