// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SPassQuest
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 임무 종류
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.QuestType Key { get; set; } = default!;
        /// <summary>
        /// 일일/시즌 분류 타입
        /// </summary>
        [JsonProperty("date_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.QuestDateType DateType { get; set; } = default!;
        /// <summary>
        /// 임무 목표값 (횟수)
        /// </summary>
        [JsonProperty("target_value", NullValueHandling = NullValueHandling.Include)]
        public int TargetValue { get; set; } = default!;
        /// <summary>
        /// 획득 경험치
        /// </summary>
        [JsonProperty("exp", NullValueHandling = NullValueHandling.Include)]
        public int Exp { get; set; } = default!;
        /// <summary>
        /// 캐릭터 랜덤 설정 1 = 랜덤
        /// </summary>
        [JsonProperty("is_character", NullValueHandling = NullValueHandling.Include)]
        public int IsCharacter { get; set; } = default!;
        /// <summary>
        /// 국가 랜덤 설정 1 = 랜덤
        /// </summary>
        [JsonProperty("is_country", NullValueHandling = NullValueHandling.Include)]
        public int IsCountry { get; set; } = default!;
        /// <summary>
        /// 클래스 랜덤 설정 1 = 랜덤
        /// </summary>
        [JsonProperty("is_class", NullValueHandling = NullValueHandling.Include)]
        public int IsClass { get; set; } = default!;
    }
}
