// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SPass
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 패스 시즌 논리 키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 유료 트랙을 여는 상품. s_shop_product.key 참조
        /// </summary>
        [JsonProperty("shop_product_key", NullValueHandling = NullValueHandling.Include)]
        public string ShopProductKey { get; set; } = default!;
        /// <summary>
        /// 최대 단계
        /// </summary>
        [JsonProperty("max_level", NullValueHandling = NullValueHandling.Include)]
        public int MaxLevel { get; set; } = default!;
        /// <summary>
        /// 시즌 시작 일시 (YYYY-MM-DD HH:MM:SS)
        /// </summary>
        [JsonProperty("season_start_at", NullValueHandling = NullValueHandling.Include)]
        public string SeasonStartAt { get; set; } = default!;
        /// <summary>
        /// 시즌 종료 일시 (YYYY-MM-DD HH:MM:SS)
        /// </summary>
        [JsonProperty("season_end_at", NullValueHandling = NullValueHandling.Include)]
        public string SeasonEndAt { get; set; } = default!;
        /// <summary>
        /// 활성화 여부 (0=비활성, 1=활성)
        /// </summary>
        [JsonProperty("is_active", NullValueHandling = NullValueHandling.Include)]
        public int IsActive { get; set; } = default!;
    }
}
