// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SPassReward
    {
        /// <summary>
        /// 패스 레벨
        /// </summary>
        [JsonProperty("level", NullValueHandling = NullValueHandling.Include)]
        public int Level { get; set; } = default!;
        /// <summary>
        /// enum item_key 참조
        /// </summary>
        [JsonProperty("reward_key", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ItemKey RewardKey { get; set; } = default!;
        /// <summary>
        /// 지급 개수
        /// </summary>
        [JsonProperty("reward_count", NullValueHandling = NullValueHandling.Include)]
        public int RewardCount { get; set; } = default!;
        /// <summary>
        /// enum item_key 참조
        /// </summary>
        [JsonProperty("paid_reward_key", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ItemKey PaidRewardKey { get; set; } = default!;
        /// <summary>
        /// 지급 개수
        /// </summary>
        [JsonProperty("paid_reward_count", NullValueHandling = NullValueHandling.Include)]
        public int PaidRewardCount { get; set; } = default!;
        /// <summary>
        /// 요구 경험치
        /// </summary>
        [JsonProperty("exp", NullValueHandling = NullValueHandling.Include)]
        public int Exp { get; set; } = default!;
    }
}
