// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SPosition
    {
        /// <summary>
        /// 직책 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 서버·기획에서 사용하는 불변 직책 key
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 직책 분류 (table_enum.position_category 참조)
        /// </summary>
        [JsonProperty("position_category", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.PositionCategory PositionCategory { get; set; } = default!;
        /// <summary>
        /// 직책 장착 시 적용할 전투 능력치 JSON
        /// </summary>
        [JsonProperty("effect", NullValueHandling = NullValueHandling.Include)]
        public string Effect { get; set; } = default!;
        /// <summary>
        /// 해금 조건 종류 (table_enum.position_unlock_condition_type 참조) 조건 판정 로직은 서버가 소유하며 지원하지 않는 종류는 실패 처리
        /// </summary>
        [JsonProperty("unlock_condition_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.PositionUnlockConditionType UnlockConditionType { get; set; } = default!;
        /// <summary>
        /// 해금 판정 기준값 character_grade_owned 계열은 조건 등급을 만족해야 하는 무장 인원 수, level/count 계열은 최소 레벨·누적 횟수 세부 등급·대상·조합은 s_position.key별 서버 규칙이 소유하며 none은 0
        /// </summary>
        [JsonProperty("unlock_condition_value", NullValueHandling = NullValueHandling.Include)]
        public int UnlockConditionValue { get; set; } = default!;
        /// <summary>
        /// 장착 조건 종류 (table_enum.position_equip_condition_type 참조)
        /// </summary>
        [JsonProperty("equip_condition_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.PositionEquipConditionType EquipConditionType { get; set; } = default!;
        /// <summary>
        /// 장착 최소 기준값 character_grade는 table_enum.character_grade 값, character_growth_stage는 s_growth.stage
        /// </summary>
        [JsonProperty("equip_condition_value", NullValueHandling = NullValueHandling.Include)]
        public int EquipConditionValue { get; set; } = default!;
    }
}
