// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SQuestReward
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 일일/주간 분류 타입
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Include)]
        public QuestDateType Type { get; set; } = default!;
        /// <summary>
        /// 보상 배치값 (횟수) 해당 수치만큼 임무 달성 시 보상 수령 가능
        /// </summary>
        [JsonProperty("target_value", NullValueHandling = NullValueHandling.Include)]
        public int TargetValue { get; set; } = default!;
        /// <summary>
        /// 개별 보상 아이템 key s_item.key 참조
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;
        /// <summary>
        /// 보상 수량
        /// </summary>
        [JsonProperty("reward_count", NullValueHandling = NullValueHandling.Include)]
        public int RewardCount { get; set; } = default!;
    }
}
