// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SQuestList
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 임무 종류
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.QuestType Key { get; set; } = default!;
        /// <summary>
        /// 일일/주간 분류 타입
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Include)]
        public string Type { get; set; } = default!;
        /// <summary>
        /// 임무 목표값 (횟수)
        /// </summary>
        [JsonProperty("target_value", NullValueHandling = NullValueHandling.Include)]
        public int TargetValue { get; set; } = default!;
        /// <summary>
        /// 개별 보상 아이템 key s_item.key 참조
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;
        /// <summary>
        /// 보상 수량
        /// </summary>
        [JsonProperty("reward_count", NullValueHandling = NullValueHandling.Include)]
        public int RewardCount { get; set; } = default!;
        /// <summary>
        /// 배너 조작 시 이동할 목적지 첫번째 [ none:-1, character:0, castle:1, dungeon:2, shop:3, gacha:4, story:5, raid:6, profile:7, tournament:8 inventory:9 ] 작성 규칙 장소, 세부장소, 세부장소2 세부장소2 규칙(영지) 1=admin 2=etc
        /// </summary>
        [JsonProperty("navigation", NullValueHandling = NullValueHandling.Include)]
        public string Navigation { get; set; } = default!;
    }
}
