// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SRaidReward
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 랭킹 ID
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 구간 타입
        /// </summary>
        [JsonProperty("rank_type", NullValueHandling = NullValueHandling.Include)]
        public RaidRankType RankType { get; set; } = default!;
        /// <summary>
        /// 최솟값 (rank=정확한 순위, percent=초과 기준 %)
        /// </summary>
        [JsonProperty("min_value", NullValueHandling = NullValueHandling.Include)]
        public double MinValue { get; set; } = default!;
        /// <summary>
        /// 최댓값 (rank=정확한 순위, percent=이하 기준 %)
        /// </summary>
        [JsonProperty("max_value", NullValueHandling = NullValueHandling.Include)]
        public double MaxValue { get; set; } = default!;
        /// <summary>
        /// 구간 표시명
        /// </summary>
        [JsonProperty("rank_label", NullValueHandling = NullValueHandling.Include)]
        public string RankLabel { get; set; } = default!;
        /// <summary>
        /// 일반등급 기준배율
        /// </summary>
        [JsonProperty("mul_normal", NullValueHandling = NullValueHandling.Include)]
        public double MulNormal { get; set; } = default!;
        /// <summary>
        /// 난세등급 기준배율
        /// </summary>
        [JsonProperty("mul_elite", NullValueHandling = NullValueHandling.Include)]
        public double MulElite { get; set; } = default!;
        /// <summary>
        /// 극한등급 기준배율
        /// </summary>
        [JsonProperty("mul_general", NullValueHandling = NullValueHandling.Include)]
        public double MulGeneral { get; set; } = default!;
        /// <summary>
        /// 지옥등급 기준배율
        /// </summary>
        [JsonProperty("mul_hero", NullValueHandling = NullValueHandling.Include)]
        public double MulHero { get; set; } = default!;
        /// <summary>
        /// 심연등급 기준배율
        /// </summary>
        [JsonProperty("mul_legend", NullValueHandling = NullValueHandling.Include)]
        public double MulLegend { get; set; } = default!;
    }
}
