// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SRaidBossStat
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// s_character.key 참조 보스 캐릭터 키 #character_key='default'은 모든 보스 공통값 특정 캐릭터 행이 있으면 우선 적용, 없으면 'default' 행 사용
        /// </summary>
        [JsonProperty("character_key", NullValueHandling = NullValueHandling.Include)]
        public string CharacterKey { get; set; } = default!;
        /// <summary>
        /// 시즌 번호
        /// </summary>
        [JsonProperty("season_no", NullValueHandling = NullValueHandling.Include)]
        public int SeasonNo { get; set; } = default!;
        /// <summary>
        /// 체력 배율 (s_monster.health_max_base 기준 1.0=그대로)
        /// </summary>
        [JsonProperty("hp_mul", NullValueHandling = NullValueHandling.Include)]
        public double HpMul { get; set; } = default!;
        /// <summary>
        /// 공격력 배율 (s_monster.attack_power_base 기준 1.0=그대로)
        /// </summary>
        [JsonProperty("atk_mul", NullValueHandling = NullValueHandling.Include)]
        public double AtkMul { get; set; } = default!;
        /// <summary>
        /// 방어력 배율 (s_monster.defence_base 기준 1.0=그대로)
        /// </summary>
        [JsonProperty("def_mul", NullValueHandling = NullValueHandling.Include)]
        public double DefMul { get; set; } = default!;
    }
}
