// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SRandombox
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 랜덤 상자 key
        /// </summary>
        [JsonProperty("bundle_key", NullValueHandling = NullValueHandling.Include)]
        public string BundleKey { get; set; } = default!;
        /// <summary>
        /// 랜덤 상자 구성 item key (s_item.key 참조)
        /// </summary>
        [JsonProperty("item_key", NullValueHandling = NullValueHandling.Include)]
        public string ItemKey { get; set; } = default!;
        /// <summary>
        /// 가중치
        /// </summary>
        [JsonProperty("weight", NullValueHandling = NullValueHandling.Include)]
        public int Weight { get; set; } = default!;
    }
}
