// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SRegion
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 지역 고유 키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 대표 장수 idx (s_character.idx 참조)
        /// </summary>
        [JsonProperty("representative_character_id", NullValueHandling = NullValueHandling.Include)]
        public int RepresentativeCharacterId { get; set; } = default!;
        /// <summary>
        /// 시작 장수 key 목록 (쉼표 구분, s_character.key 참조)
        /// </summary>
        [JsonProperty("starter_character_keys", NullValueHandling = NullValueHandling.Include)]
        public string StarterCharacterKeys { get; set; } = default!;
        /// <summary>
        /// 상성 우위 대상 지역 key (s_region.key 참조)
        /// </summary>
        [JsonProperty("counter_region_key", NullValueHandling = NullValueHandling.Include)]
        public string CounterRegionKey { get; set; } = default!;
        /// <summary>
        /// 활성 여부
        /// </summary>
        [JsonProperty("is_active", NullValueHandling = NullValueHandling.Include)]
        public int IsActive { get; set; } = default!;
        /// <summary>
        /// 클라이언트 RegionType 숫자 값 (초기 선택은 wei/shu/wu만 허용)
        /// </summary>
        [JsonProperty("region_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.RegionType RegionType { get; set; } = default!;
    }
}
