// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SRelicEnhance
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 강화 단계 (1~100)
        /// </summary>
        [JsonProperty("stage", NullValueHandling = NullValueHandling.Include)]
        public int Stage { get; set; } = default!;
        /// <summary>
        /// 요구 시간석 수
        /// </summary>
        [JsonProperty("time_stone_required", NullValueHandling = NullValueHandling.Include)]
        public int TimeStoneRequired { get; set; } = default!;
        /// <summary>
        /// 효과 배율 (s_relic.effect 기준) 최종값 = s_relic.effect[stat] x effect_multiplier 예: 1.5면 base의 1.5배
        /// </summary>
        [JsonProperty("effect_multiplier", NullValueHandling = NullValueHandling.Include)]
        public double EffectMultiplier { get; set; } = default!;
        /// <summary>
        /// 클래스 공유 효과 배율 (s_relic.class_share_effect 기준) 최종값 = s_relic.class_share_effect[stat] x class_share_effect_multiplier 본인 효과 배율(effect_multiplier)과 별개 곡선
        /// </summary>
        [JsonProperty("class_share_effect_multiplier", NullValueHandling = NullValueHandling.Include)]
        public double ClassShareEffectMultiplier { get; set; } = default!;
    }
}
