// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SRelic
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 유물 논리키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 장수 키 (s_character.key 참조)
        /// </summary>
        [JsonProperty("character_key", NullValueHandling = NullValueHandling.Include)]
        public string CharacterKey { get; set; } = default!;
        /// <summary>
        /// 유물 이름
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Include)]
        public string Name { get; set; } = default!;
        /// <summary>
        /// 효과 JSON ({"stat_key": value} 형식) 합연산 곱연산 미정
        /// </summary>
        [JsonProperty("effect", NullValueHandling = NullValueHandling.Include)]
        public string Effect { get; set; } = default!;
        /// <summary>
        /// 같은 클래스 장수 전체에게 주는 효과 JSON ({"stat_key": value} 형식) 대상 클래스 = character_key 장수의 클래스 보유한 같은 클래스 장수 전원에게 적용 (유물 주인 본인 포함) 같은 클래스 유물이 여러 개면 전부 합산 최종값 = class_share_effect[stat] x s_relic_enhance.class_share_effect_multiplier
        /// </summary>
        [JsonProperty("class_share_effect", NullValueHandling = NullValueHandling.Include)]
        public string ClassShareEffect { get; set; } = default!;
    }
}
