// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SShop
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 상점 논리 키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 탭 표시 순서 (작을수록 앞)
        /// </summary>
        [JsonProperty("display_order", NullValueHandling = NullValueHandling.Include)]
        public int DisplayOrder { get; set; } = default!;
        /// <summary>
        /// 활성화 여부 (0=비활성, 1=활성) 비활성 상점은 전 유저에게 탭이 표시되지 않는다 유저별 콘텐츠 해금과는 별개인 전역 스위치
        /// </summary>
        [JsonProperty("is_active", NullValueHandling = NullValueHandling.Include)]
        public int IsActive { get; set; } = default!;
        /// <summary>
        /// 클라이언트 API에 사용하는 콘텐츠 상점 타입
        /// </summary>
        [JsonProperty("shop_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ContentShopType ShopType { get; set; } = default!;
    }
}
