// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SShopProduct
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 상품 논리 키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 클라이언트 API에 사용하는 상점 탭 타입
        /// </summary>
        [JsonProperty("shop_category_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ShopCategoryType ShopCategoryType { get; set; } = default!;
        /// <summary>
        /// 상품 타입 (single=단일, package=패키지, pass=패스)
        /// </summary>
        [JsonProperty("product_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ShopProductType ProductType { get; set; } = default!;
        /// <summary>
        /// 결제 재화 타입 (cash=현금 인앱결제)
        /// </summary>
        [JsonProperty("pay_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.PayType PayType { get; set; } = default!;
        /// <summary>
        /// 가격 게임 재화 결제일 때만 사용한다. 현금 결제는 0이며 실제 금액은 스토어 콘솔이 관리한다
        /// </summary>
        [JsonProperty("price", NullValueHandling = NullValueHandling.Include)]
        public int Price { get; set; } = default!;
        /// <summary>
        /// 지급 아이템. item.s_item.key 참조
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;
        /// <summary>
        /// 지급 수량
        /// </summary>
        [JsonProperty("reward_count", NullValueHandling = NullValueHandling.Include)]
        public int RewardCount { get; set; } = default!;
        /// <summary>
        /// 현금 결제용 스토어 상품 ID 게임 재화 결제는 빈 값
        /// </summary>
        [JsonProperty("store_product_key", NullValueHandling = NullValueHandling.Include)]
        public string StoreProductKey { get; set; } = default!;
        /// <summary>
        /// 구매 한도 (0=무한)
        /// </summary>
        [JsonProperty("buy_limit", NullValueHandling = NullValueHandling.Include)]
        public int BuyLimit { get; set; } = default!;
        /// <summary>
        /// 한도 초기화 주기 (daily=일일, weekly=주간, season=시즌, permanent=초기화 없음)
        /// </summary>
        [JsonProperty("limit_reset_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.LimitResetType LimitResetType { get; set; } = default!;
        /// <summary>
        /// 진열 순서 (작을수록 앞)
        /// </summary>
        [JsonProperty("display_order", NullValueHandling = NullValueHandling.Include)]
        public int DisplayOrder { get; set; } = default!;
        /// <summary>
        /// 활성화 여부 (0=비활성, 1=활성) 비활성 상품은 진열되지 않고 구매도 되지 않는다
        /// </summary>
        [JsonProperty("is_active", NullValueHandling = NullValueHandling.Include)]
        public int IsActive { get; set; } = default!;
    }
}
