// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SShopDailyPool
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 상품 지급 item key (s_item.key 참조)
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;
        /// <summary>
        /// 상품 등급 진열 추첨에 사용한다 (등급별 확률은 s_shop_daily_grade_rate 참조) 보따리·랜덤 상자는 이 등급으로 지급 수량이 정해진다
        /// </summary>
        [JsonProperty("grade", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ItemGrade Grade { get; set; } = default!;
        /// <summary>
        /// 지급 수량
        /// </summary>
        [JsonProperty("reward_count", NullValueHandling = NullValueHandling.Include)]
        public int RewardCount { get; set; } = default!;
        /// <summary>
        /// 결제 재화 타입
        /// </summary>
        [JsonProperty("pay_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.PayType PayType { get; set; } = default!;
        /// <summary>
        /// 가격
        /// </summary>
        [JsonProperty("price", NullValueHandling = NullValueHandling.Include)]
        public int Price { get; set; } = default!;
        /// <summary>
        /// 한도 초기화 주기 (daily=일일, weekly=주간, season=시즌, permanent=초기화 없음)
        /// </summary>
        [JsonProperty("limit_reset_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.LimitResetType LimitResetType { get; set; } = default!;
        /// <summary>
        /// 구매 한도 (-1=무한)
        /// </summary>
        [JsonProperty("buy_limit", NullValueHandling = NullValueHandling.Include)]
        public int BuyLimit { get; set; } = default!;
        /// <summary>
        /// 진열 순서 (작을수록 앞)
        /// </summary>
        [JsonProperty("display_order", NullValueHandling = NullValueHandling.Include)]
        public int DisplayOrder { get; set; } = default!;
        /// <summary>
        /// 활성화 여부 (0=비활성, 1=활성) 비활성 상품은 진열 추첨 후보에서 제외된다
        /// </summary>
        [JsonProperty("is_active", NullValueHandling = NullValueHandling.Include)]
        public int IsActive { get; set; } = default!;
    }
}
