// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SShopRaid
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 상품 지급 item key (s_item.key 참조)
        /// </summary>
        [JsonProperty("reward_item_key", NullValueHandling = NullValueHandling.Include)]
        public string RewardItemKey { get; set; } = default!;
        /// <summary>
        /// 상품 등급 보따리·랜덤 상자는 s_bundle.item_grade와 일치해야 한다. 실제 지급 수량은 해당 번들의 s_bundle.configuration_minimum/maximum 설정을 사용한다 고정 카탈로그라 진열 추첨에는 사용하지 않는다
        /// </summary>
        [JsonProperty("grade", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.ItemGrade Grade { get; set; } = default!;
        /// <summary>
        /// 지급 수량
        /// </summary>
        [JsonProperty("reward_count", NullValueHandling = NullValueHandling.Include)]
        public int RewardCount { get; set; } = default!;
        /// <summary>
        /// 결제 재화 타입
        /// </summary>
        [JsonProperty("pay_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.PayType PayType { get; set; } = default!;
        /// <summary>
        /// 가격
        /// </summary>
        [JsonProperty("price", NullValueHandling = NullValueHandling.Include)]
        public int Price { get; set; } = default!;
        /// <summary>
        /// 한도 초기화 주기 (daily=일일, weekly=주간, season=시즌, permanent=초기화 없음)
        /// </summary>
        [JsonProperty("limit_reset_type", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.LimitResetType LimitResetType { get; set; } = default!;
        /// <summary>
        /// 구매 한도 (-1=무한)
        /// </summary>
        [JsonProperty("buy_limit", NullValueHandling = NullValueHandling.Include)]
        public int BuyLimit { get; set; } = default!;
        /// <summary>
        /// 진열 순서 (작을수록 앞)
        /// </summary>
        [JsonProperty("display_order", NullValueHandling = NullValueHandling.Include)]
        public int DisplayOrder { get; set; } = default!;
        /// <summary>
        /// 활성화 여부 (0=비활성, 1=활성) 비활성 상품은 진열되지 않고 구매도 되지 않는다
        /// </summary>
        [JsonProperty("is_active", NullValueHandling = NullValueHandling.Include)]
        public int IsActive { get; set; } = default!;
    }
}
