// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SShopDailyGradeRate
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// s_shop.id 참조 랜덤 진열 상점만 해당
        /// </summary>
        [JsonProperty("shop_id", NullValueHandling = NullValueHandling.Include)]
        public string ShopId { get; set; } = default!;
        /// <summary>
        /// 상품 등급
        /// </summary>
        [JsonProperty("grade", NullValueHandling = NullValueHandling.Include)]
        public ItemGrade Grade { get; set; } = default!;
        /// <summary>
        /// 등급이 뽑힐 확률 (1=100%) 같은 상점 안에서 합계가 1.0이 돼야 한다
        /// </summary>
        [JsonProperty("appear_rate", NullValueHandling = NullValueHandling.Include)]
        public double AppearRate { get; set; } = default!;
    }
}
