// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SSkill
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 스킬 고유 ID
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 스킬을 쓰는 개체 인물 = s_character.key 일반 몬스터 = s_enemy_stat.key
        /// </summary>
        [JsonProperty("owner_key", NullValueHandling = NullValueHandling.Include)]
        public string OwnerKey { get; set; } = default!;
        /// <summary>
        /// 어느 쪽으로 쓰이는 스킬인지 playable = 유저가 편성해 쓰는 스킬, 개체당 1개 enemy = 적으로 등장할 때만 쓰는 스킬, 여러 개 가능 both = 양쪽에서 같은 스킬을 씀
        /// </summary>
        [JsonProperty("usage_type", NullValueHandling = NullValueHandling.Include)]
        public string UsageType { get; set; } = default!;
        /// <summary>
        /// 이 스킬을 쓸 수 있는 형태 제한 빈칸 = 제한 없음 · 일반 몬스터처럼 형태 구분이 없는 적 · 두 형태가 모두 쓰는 보스 스킬 basic = 기본 보스만 사용 jin = 진 보스만 사용 usage_type이 playable이면 항상 빈칸
        /// </summary>
        [JsonProperty("boss_type", NullValueHandling = NullValueHandling.Include)]
        public string BossType { get; set; } = default!;
        /// <summary>
        /// 시전 형태 team = 편성된 무장 전체 self_area = 시전자 주변 target_area = 지정한 범위 ground_area = 지정한 위치에 설치 line_forward = 전방 직선 dash_path = 돌진 경로 single_target = 적 하나 지정
        /// </summary>
        [JsonProperty("cast_type", NullValueHandling = NullValueHandling.Include)]
        public string CastType { get; set; } = default!;
        /// <summary>
        /// 시전할 수 있는 거리 0 = 거리 제한 없음
        /// </summary>
        [JsonProperty("range_value", NullValueHandling = NullValueHandling.Include)]
        public int RangeValue { get; set; } = default!;
        /// <summary>
        /// 재사용 대기 시간
        /// </summary>
        [JsonProperty("cooldown_seconds", NullValueHandling = NullValueHandling.Include)]
        public double CooldownSeconds { get; set; } = default!;
        /// <summary>
        /// 스킬 자체가 유지되는 시간 0 = 즉시 끝남
        /// </summary>
        [JsonProperty("duration_seconds", NullValueHandling = NullValueHandling.Include)]
        public double DurationSeconds { get; set; } = default!;
        /// <summary>
        /// 다음 적에게 튕기는 횟수 0 = 튕기지 않음
        /// </summary>
        [JsonProperty("chain_count", NullValueHandling = NullValueHandling.Include)]
        public int ChainCount { get; set; } = default!;
        /// <summary>
        /// AUTO 사용 시 조준 규칙 적 스킬은 늘 자동이므로 항상 적용된다 self = 조준 없음 enemy_nearest = 가장 가까운 적 enemy_dense = 적이 가장 많이 겹치는 지점 enemy_boss_first = 보스 우선, 없으면 가장 가까운 적
        /// </summary>
        [JsonProperty("auto_target_type", NullValueHandling = NullValueHandling.Include)]
        public string AutoTargetType { get; set; } = default!;
        /// <summary>
        /// 시전자 체력이 이 비율 이상일 때만 발동 자기 체력을 깎는 스킬의 자멸 방지용 적 스킬은 늘 자동이므로 항상 적용된다 1 = 100% 0 = 조건 없음
        /// </summary>
        [JsonProperty("auto_cast_min_health_rate", NullValueHandling = NullValueHandling.Include)]
        public double AutoCastMinHealthRate { get; set; } = default!;
    }
}
