// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SSkillEffect
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 어느 스킬의 효과인지 s_skill.key 참조
        /// </summary>
        [JsonProperty("skill_key", NullValueHandling = NullValueHandling.Include)]
        public string SkillKey { get; set; } = default!;
        /// <summary>
        /// 적용 순서 skill_key와 묶어 고유
        /// </summary>
        [JsonProperty("effect_order", NullValueHandling = NullValueHandling.Include)]
        public int EffectOrder { get; set; } = default!;
        /// <summary>
        /// 효과를 받는 대상 self = 시전자 ally = 범위 안의 아군 ally_all = 편성된 무장 전체 enemy = 적
        /// </summary>
        [JsonProperty("target_type", NullValueHandling = NullValueHandling.Include)]
        public string TargetType { get; set; } = default!;
        /// <summary>
        /// 효과 종류 damage = 즉시 피해 damage_over_time = 시간당 피해 heal = 체력 회복 stat_change = 능력치 증감 crowd_control = 상태이상 cooldown_reduce = 재사용 대기 단축
        /// </summary>
        [JsonProperty("effect_type", NullValueHandling = NullValueHandling.Include)]
        public string EffectType { get; set; } = default!;
        /// <summary>
        /// 바뀌는 능력치 stat_change일 때만 사용 attack_power / defence / attack_speed / health_max / move_speed / life_steal / critical_rate / cooldown_rate / critical_damage / boss_damage
        /// </summary>
        [JsonProperty("battle_stat_type", NullValueHandling = NullValueHandling.Include)]
        public string BattleStatType { get; set; } = default!;
        /// <summary>
        /// 상태이상 종류 stun = 기절 airborne = 공중에 띄움 pull = 끌어당김 knockback = 넉백 shock = 감전 silence = 침묵 burn = 화상
        /// </summary>
        [JsonProperty("crowd_control_type", NullValueHandling = NullValueHandling.Include)]
        public string CrowdControlType { get; set; } = default!;
        /// <summary>
        /// 공격력에 곱하는 배수 피해 = 공격력 × 이 값 0 = 사용 안 함
        /// </summary>
        [JsonProperty("attack_power_mul", NullValueHandling = NullValueHandling.Include)]
        public double AttackPowerMul { get; set; } = default!;
        /// <summary>
        /// 증감 비율 1 = 100% 음수 = 감소 heal일 때는 대상 최대 체력 대비 회복 비율 0 = 사용 안 함
        /// </summary>
        [JsonProperty("effect_rate", NullValueHandling = NullValueHandling.Include)]
        public double EffectRate { get; set; } = default!;
        /// <summary>
        /// 고정 수치 0 = 사용 안 함
        /// </summary>
        [JsonProperty("effect_value", NullValueHandling = NullValueHandling.Include)]
        public int EffectValue { get; set; } = default!;
        /// <summary>
        /// 이 효과가 미치는 범위 0 = 범위 없음
        /// </summary>
        [JsonProperty("area_value", NullValueHandling = NullValueHandling.Include)]
        public int AreaValue { get; set; } = default!;
        /// <summary>
        /// 효과가 지속되는 시간 0 = 즉시 끝남
        /// </summary>
        [JsonProperty("duration_seconds", NullValueHandling = NullValueHandling.Include)]
        public double DurationSeconds { get; set; } = default!;
        /// <summary>
        /// 지속 피해 적용 간격(초) 0 = 사용 안 함
        /// </summary>
        [JsonProperty("interval_seconds", NullValueHandling = NullValueHandling.Include)]
        public double IntervalSeconds { get; set; } = default!;
    }
}
