// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SStoryNode
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 노드 고유 키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 노드 타입
        /// </summary>
        [JsonProperty("node_type", NullValueHandling = NullValueHandling.Include)]
        public StoryNodeType NodeType { get; set; } = default!;
        /// <summary>
        /// 연도
        /// </summary>
        [JsonProperty("year", NullValueHandling = NullValueHandling.Include)]
        public int Year { get; set; } = default!;
        /// <summary>
        /// 해금 조건 챕터 키 (s_chapter.chapter_key 참조)
        /// </summary>
        [JsonProperty("chapter_key", NullValueHandling = NullValueHandling.Include)]
        public int ChapterKey { get; set; } = default!;
        /// <summary>
        /// 해금 조건 스테이지 키 (s_chapter.stage_key 참조)
        /// </summary>
        [JsonProperty("stage_key", NullValueHandling = NullValueHandling.Include)]
        public int StageKey { get; set; } = default!;
        /// <summary>
        /// 조건부 해금 여부 (1=특정 선택 조건 필요)
        /// </summary>
        [JsonProperty("is_conditional", NullValueHandling = NullValueHandling.Include)]
        public int IsConditional { get; set; } = default!;
        /// <summary>
        /// IF 스토리 포함 여부 (1=포함)
        /// </summary>
        [JsonProperty("has_if_story", NullValueHandling = NullValueHandling.Include)]
        public int HasIfStory { get; set; } = default!;
        /// <summary>
        /// 클리어 보상 재화 타입
        /// </summary>
        [JsonProperty("reward_currency_type", NullValueHandling = NullValueHandling.Include)]
        public RewardCurrencyType RewardCurrencyType { get; set; } = default!;
        /// <summary>
        /// 클리어 보상 재화 값
        /// </summary>
        [JsonProperty("reward_currency_amount", NullValueHandling = NullValueHandling.Include)]
        public int RewardCurrencyAmount { get; set; } = default!;
        /// <summary>
        /// 획득 장수 키 (s_character.key 참조) 0=미지급
        /// </summary>
        [JsonProperty("reward_character", NullValueHandling = NullValueHandling.Include)]
        public string RewardCharacter { get; set; } = default!;
        /// <summary>
        /// 조건부 획득 선택지 번호  (0=노드 클리어 시 무조건 지급)
        /// </summary>
        [JsonProperty("required_choice_seq", NullValueHandling = NullValueHandling.Include)]
        public int RequiredChoiceSeq { get; set; } = default!;
        /// <summary>
        /// 활성화 여부 (0=비활성, 1=활성)
        /// </summary>
        [JsonProperty("is_active", NullValueHandling = NullValueHandling.Include)]
        public int IsActive { get; set; } = default!;
        /// <summary>
        /// 표시 순서 중복일 경우 같은 위치 내 1개만 표시
        /// </summary>
        [JsonProperty("order_num", NullValueHandling = NullValueHandling.Include)]
        public int OrderNum { get; set; } = default!;
        /// <summary>
        /// IF 스토리 발동 노드 키 (if_story 타입 전용, s_story_node.node_key 참조)
        /// </summary>
        [JsonProperty("next_node_key", NullValueHandling = NullValueHandling.Include)]
        public string NextNodeKey { get; set; } = default!;
    }
}
