// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class SStoryNodeUnlock
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 해금 대상 노드 키
        /// </summary>
        [JsonProperty("node_key", NullValueHandling = NullValueHandling.Include)]
        public string NodeKey { get; set; } = default!;
        /// <summary>
        /// 조건 기준 노드 키
        /// </summary>
        [JsonProperty("source_node_key", NullValueHandling = NullValueHandling.Include)]
        public string SourceNodeKey { get; set; } = default!;
        /// <summary>
        /// 선택지 번호
        /// </summary>
        [JsonProperty("required_choice_seq", NullValueHandling = NullValueHandling.Include)]
        public int RequiredChoiceSeq { get; set; } = default!;
    }
}
