// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class STournamentScore
    {
        /// <summary>
        /// 순번
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 문자 키
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Include)]
        public string Id { get; set; } = default!;
        /// <summary>
        /// 승리 시 증감
        /// </summary>
        [JsonProperty("win_score", NullValueHandling = NullValueHandling.Include)]
        public int WinScore { get; set; } = default!;
        /// <summary>
        /// 패배 시 증감
        /// </summary>
        [JsonProperty("lose_score", NullValueHandling = NullValueHandling.Include)]
        public int LoseScore { get; set; } = default!;
    }
}
