// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class STournamentTier
    {
        /// <summary>
        /// 순번(자동증가)
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 문자 키
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Include)]
        public string Id { get; set; } = default!;
        /// <summary>
        /// 점수 하한(이상)
        /// </summary>
        [JsonProperty("score_min", NullValueHandling = NullValueHandling.Include)]
        public int ScoreMin { get; set; } = default!;
        /// <summary>
        /// 순위 상한(누적 top N). -1=상한 없음
        /// </summary>
        [JsonProperty("rank_limit", NullValueHandling = NullValueHandling.Include)]
        public int RankLimit { get; set; } = default!;
        /// <summary>
        /// 소프트 리셋 시 다음 시즌 시작 점수
        /// </summary>
        [JsonProperty("soft_reset_score", NullValueHandling = NullValueHandling.Include)]
        public int SoftResetScore { get; set; } = default!;
    }
}
