// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class STraitsPool
    {
        /// <summary>
        /// 특성 고유 번호
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 특성 고유 이름 (문자 키) 다른 테이블에서 특성을 가리킬 때 이 값을 사용
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 특성 등급
        /// </summary>
        [JsonProperty("traits_grade", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.TraitsGrade TraitsGrade { get; set; } = default!;
        /// <summary>
        /// 특성별 등장 가중치 뽑힐 확률 = 자기 weight ÷ 전체 weight 합계 합계는 고정값이 아니며, 특성이 추가·삭제되면 각 확률은 자동으로 조정됨 0 = 등장하지 않음
        /// </summary>
        [JsonProperty("weight", NullValueHandling = NullValueHandling.Include)]
        public int Weight { get; set; } = default!;
    }
}
