// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class STraitsValuePool
    {
        /// <summary>
        /// 특성 고유 번호
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 특성 key
        /// </summary>
        [JsonProperty("traits_pool_key", NullValueHandling = NullValueHandling.Include)]
        public string TraitsPoolKey { get; set; } = default!;
        /// <summary>
        /// 수치 값 값이 여러 개일 때는 쉼표로 구분 (예: 1,200,3) 왼쪽부터 #traits_name의 {0},{1},{2} 순서에 대응
        /// </summary>
        [JsonProperty("traits_value", NullValueHandling = NullValueHandling.Include)]
        public string TraitsValue { get; set; } = default!;
        /// <summary>
        /// 등급
        /// </summary>
        [JsonProperty("traits_value_grade", NullValueHandling = NullValueHandling.Include)]
        public global::ThreeKingdoms.Shared.Enums.TraitsValueGrade TraitsValueGrade { get; set; } = default!;
        /// <summary>
        /// 수치별 등장 확률 같은 고유 key의 rate 합이 1 등급별 합계 normal : 50% elite : 25% general : 15% hero : 7% legend : 3%
        /// </summary>
        [JsonProperty("grade_rate", NullValueHandling = NullValueHandling.Include)]
        public double GradeRate { get; set; } = default!;
    }
}
