// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Table
{
    public sealed class STreasure
    {
        /// <summary>
        /// 고유 ID
        /// </summary>
        [JsonProperty("idx", NullValueHandling = NullValueHandling.Include)]
        public int Idx { get; set; } = default!;
        /// <summary>
        /// 보물 논리키
        /// </summary>
        [JsonProperty("key", NullValueHandling = NullValueHandling.Include)]
        public string Key { get; set; } = default!;
        /// <summary>
        /// 효과 JSON ({"stat_key": value, ...})
        /// </summary>
        [JsonProperty("effect", NullValueHandling = NullValueHandling.Include)]
        public string Effect { get; set; } = default!;
        /// <summary>
        /// 합성 필요 조각 수
        /// </summary>
        [JsonProperty("pieces_required", NullValueHandling = NullValueHandling.Include)]
        public int PiecesRequired { get; set; } = default!;
    }
}
