// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Constants
{
    public static class ApiCodes
    {
        public const string SUCCESS = "SUCCESS";
        /// <summary>
        /// Firebase ID Token의 유효 시간이 만료됐다.
        /// </summary>
        public const string AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED";
        /// <summary>
        /// Firebase ID Token이 없거나 검증할 수 없는 값이다.
        /// </summary>
        public const string AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID";
        /// <summary>
        /// 해당 건물은 현재 무장 배치를 지원하지 않는다.
        /// </summary>
        public const string CASTLE_BUILDING_ASSIGNMENT_DISABLED = "CASTLE_BUILDING_ASSIGNMENT_DISABLED";
        /// <summary>
        /// 건물이 이미 기획 최대 레벨이다.
        /// </summary>
        public const string CASTLE_BUILDING_MAX_LEVEL = "CASTLE_BUILDING_MAX_LEVEL";
        /// <summary>
        /// 요청한 무장 수가 현재 건물의 배치 슬롯 수를 초과한다.
        /// </summary>
        public const string CASTLE_BUILDING_SLOT_FULL = "CASTLE_BUILDING_SLOT_FULL";
        /// <summary>
        /// 오늘 건물 증축 광고 단축 상한에 도달했다.
        /// </summary>
        public const string CASTLE_BUILDING_UPGRADE_AD_LIMIT_REACHED = "CASTLE_BUILDING_UPGRADE_AD_LIMIT_REACHED";
        /// <summary>
        /// 해당 건물이 이미 증축 중이다.
        /// </summary>
        public const string CASTLE_BUILDING_UPGRADE_IN_PROGRESS = "CASTLE_BUILDING_UPGRADE_IN_PROGRESS";
        /// <summary>
        /// 요청한 증축 단축에 필요한 시간석이 부족하다.
        /// </summary>
        public const string CASTLE_BUILDING_UPGRADE_NOT_ENOUGH_TIME_STONE = "CASTLE_BUILDING_UPGRADE_NOT_ENOUGH_TIME_STONE";
        /// <summary>
        /// 단축할 진행 중 증축이 없다.
        /// </summary>
        public const string CASTLE_BUILDING_UPGRADE_NOT_FOUND = "CASTLE_BUILDING_UPGRADE_NOT_FOUND";
        /// <summary>
        /// 궁성 또는 다른 건물 레벨 선행조건이 부족하다.
        /// </summary>
        public const string CASTLE_BUILDING_UPGRADE_PREREQUISITE = "CASTLE_BUILDING_UPGRADE_PREREQUISITE";
        /// <summary>
        /// 목표 레벨 증축을 시작할 배치 능력치가 부족하다.
        /// </summary>
        public const string CASTLE_BUILDING_UPGRADE_REQUIREMENTS_NOT_MET = "CASTLE_BUILDING_UPGRADE_REQUIREMENTS_NOT_MET";
        /// <summary>
        /// 배치 요청에 보유하지 않은 무장이 포함되어 있다.
        /// </summary>
        public const string CASTLE_CHARACTER_NOT_OWNED = "CASTLE_CHARACTER_NOT_OWNED";
        /// <summary>
        /// 무결성 보정과 정수 절삭 후 수령할 생산물이 없다.
        /// </summary>
        public const string CASTLE_NOTHING_TO_COLLECT = "CASTLE_NOTHING_TO_COLLECT";
        /// <summary>
        /// 최초 영지 sync가 완료되지 않아 영지 변경을 처리할 수 없다.
        /// </summary>
        public const string CASTLE_NOT_ACTIVATED = "CASTLE_NOT_ACTIVATED";
        /// <summary>
        /// 미보유 또는 다른 파견 중인 무장이 포함됐다.
        /// </summary>
        public const string CASTLE_OFFICE_CHARACTER_UNAVAILABLE = "CASTLE_OFFICE_CHARACTER_UNAVAILABLE";
        /// <summary>
        /// 서버 완료 시각에 아직 도달하지 않았다.
        /// </summary>
        public const string CASTLE_OFFICE_NOT_COMPLETED = "CASTLE_OFFICE_NOT_COMPLETED";
        /// <summary>
        /// 보상 수령 가능한 오늘의 파견 횟수가 부족하다.
        /// </summary>
        public const string CASTLE_OFFICE_NO_ENTRIES = "CASTLE_OFFICE_NO_ENTRIES";
        /// <summary>
        /// 이미 사용·갱신됐거나 현재 목록에 없는 파견 offer다.
        /// </summary>
        public const string CASTLE_OFFICE_OFFER_UNAVAILABLE = "CASTLE_OFFICE_OFFER_UNAVAILABLE";
        /// <summary>
        /// 파견 목록 갱신 군량이 부족하다.
        /// </summary>
        public const string CASTLE_OFFICE_REFRESH_NOT_ENOUGH_RICE = "CASTLE_OFFICE_REFRESH_NOT_ENOUGH_RICE";
        /// <summary>
        /// 이미 수령했거나 현재 사용자에게 없는 파견 회차다.
        /// </summary>
        public const string CASTLE_OFFICE_RUN_UNAVAILABLE = "CASTLE_OFFICE_RUN_UNAVAILABLE";
        /// <summary>
        /// 마지막 조회 뒤 다른 영지 상태가 확정되어 요청 revision이 오래됐다.
        /// </summary>
        public const string CASTLE_STATE_CHANGED = "CASTLE_STATE_CHANGED";
        /// <summary>
        /// 전용·동일 클래스·공용 영혼석의 합계가 승급 비용보다 부족하다.
        /// </summary>
        public const string CHARACTER_ASCENSION_NOT_ENOUGH_MATERIAL = "CHARACTER_ASCENSION_NOT_ENOUGH_MATERIAL";
        /// <summary>
        /// 현재 등급보다 높은 도달 등급으로만 승급할 수 있다.
        /// </summary>
        public const string CHARACTER_ASCENSION_TARGET_GRADE_INVALID = "CHARACTER_ASCENSION_TARGET_GRADE_INVALID";
        /// <summary>
        /// 요청한 무장이 이미 최대 성장 단계다.
        /// </summary>
        public const string CHARACTER_GROWTH_MAX_STAGE = "CHARACTER_GROWTH_MAX_STAGE";
        /// <summary>
        /// 요청한 무장을 현재 사용자가 보유하지 않았다.
        /// </summary>
        public const string CHARACTER_NOT_OWNED = "CHARACTER_NOT_OWNED";
        /// <summary>
        /// 직책 해금 조건을 아직 충족하지 않았다.
        /// </summary>
        public const string CHARACTER_POSITION_LOCKED = "CHARACTER_POSITION_LOCKED";
        /// <summary>
        /// 해금 판정에 필요한 실제 진행 기록을 아직 확인할 수 없다.
        /// </summary>
        public const string CHARACTER_POSITION_PROGRESS_UNAVAILABLE = "CHARACTER_POSITION_PROGRESS_UNAVAILABLE";
        /// <summary>
        /// 대상 무장이 직책의 장착 조건을 충족하지 않았다.
        /// </summary>
        public const string CHARACTER_POSITION_REQUIREMENTS_NOT_MET = "CHARACTER_POSITION_REQUIREMENTS_NOT_MET";
        /// <summary>
        /// 목표 유물 단계까지 강화할 시간석이 부족하다.
        /// </summary>
        public const string CHARACTER_RELIC_NOT_ENOUGH_TIME_STONE = "CHARACTER_RELIC_NOT_ENOUGH_TIME_STONE";
        /// <summary>
        /// 목표 유물 단계가 현재 단계 이하이거나 무장 등급 상한을 넘는다.
        /// </summary>
        public const string CHARACTER_RELIC_TARGET_STAGE_INVALID = "CHARACTER_RELIC_TARGET_STAGE_INVALID";
        /// <summary>
        /// 재추첨할 수 있는 특성 슬롯이 모두 잠겼다.
        /// </summary>
        public const string CHARACTER_TRAITS_ALL_LOCKED = "CHARACTER_TRAITS_ALL_LOCKED";
        /// <summary>
        /// 해당 무장 등급에서 열리지 않은 특성 슬롯이다.
        /// </summary>
        public const string CHARACTER_TRAIT_SLOT_NOT_OPEN = "CHARACTER_TRAIT_SLOT_NOT_OPEN";
        /// <summary>
        /// 보물 장착 가능 개수를 초과했다.
        /// </summary>
        public const string CHARACTER_TREASURE_EQUIPPED_LIMIT = "CHARACTER_TREASURE_EQUIPPED_LIMIT";
        /// <summary>
        /// 장착 목록에 보유하지 않은 보물이 포함됐다.
        /// </summary>
        public const string CHARACTER_TREASURE_NOT_OWNED = "CHARACTER_TREASURE_NOT_OWNED";
        /// <summary>
        /// 서버 점검 정책으로 현재 로그인이 제한된다.
        /// </summary>
        public const string COMMON_MAINTENANCE = "COMMON_MAINTENANCE";
        /// <summary>
        /// 필수 서버 설정이 없거나 허용된 형식과 다르다.
        /// </summary>
        public const string CONFIG_INVALID = "CONFIG_INVALID";
        /// <summary>
        /// 해당 초기화 주기의 상품 구매 한도에 도달했다.
        /// </summary>
        public const string CONTENT_SHOP_BUY_LIMIT_REACHED = "CONTENT_SHOP_BUY_LIMIT_REACHED";
        /// <summary>
        /// 현재 서버 범위에서 구매할 수 없는 상점이다.
        /// </summary>
        public const string CONTENT_SHOP_NOT_AVAILABLE = "CONTENT_SHOP_NOT_AVAILABLE";
        /// <summary>
        /// 현재 결제 재화가 총 가격보다 부족하다.
        /// </summary>
        public const string CONTENT_SHOP_NOT_ENOUGH_CURRENCY = "CONTENT_SHOP_NOT_ENOUGH_CURRENCY";
        /// <summary>
        /// 비활성 또는 현재 진열에 없는 상품이다.
        /// </summary>
        public const string CONTENT_SHOP_PRODUCT_NOT_AVAILABLE = "CONTENT_SHOP_PRODUCT_NOT_AVAILABLE";
        /// <summary>
        /// 오늘 광고 완료 상한에 도달했다.
        /// </summary>
        public const string DAILY_DUNGEON_AD_LIMIT_REACHED = "DAILY_DUNGEON_AD_LIMIT_REACHED";
        /// <summary>
        /// 해당 보스는 오늘 입장·토벌할 수 없다.
        /// </summary>
        public const string DAILY_DUNGEON_BOSS_UNAVAILABLE = "DAILY_DUNGEON_BOSS_UNAVAILABLE";
        /// <summary>
        /// 이미 정산했거나 새 입장으로 대체된 도전이다.
        /// </summary>
        public const string DAILY_DUNGEON_ENTRY_NOT_ACTIVE = "DAILY_DUNGEON_ENTRY_NOT_ACTIVE";
        /// <summary>
        /// 공유하는 입장·토벌 횟수가 부족하다.
        /// </summary>
        public const string DAILY_DUNGEON_NO_ENTRIES = "DAILY_DUNGEON_NO_ENTRIES";
        /// <summary>
        /// 해당 보스의 일반 이상 처치 기록이 필요하다.
        /// </summary>
        public const string DAILY_DUNGEON_RECORD_REQUIRED = "DAILY_DUNGEON_RECORD_REQUIRED";
        /// <summary>
        /// MySQL 연결이 끊겼거나 연결할 수 없어 요청을 처리하지 못했다.
        /// </summary>
        public const string DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE";
        /// <summary>
        /// 다른 사용자가 이미 사용 중인 닉네임이다.
        /// </summary>
        public const string FAIL_NICKNAME_DUPLICATE = "FAIL_NICKNAME_DUPLICATE";
        /// <summary>
        /// 유료 닉네임 변경에 필요한 시간석이 부족하다.
        /// </summary>
        public const string FAIL_NICKNAME_NOT_ENOUGH_CURRENCY = "FAIL_NICKNAME_NOT_ENOUGH_CURRENCY";
        /// <summary>
        /// 무장 성장에 필요한 군량이 부족하다.
        /// </summary>
        public const string FAIL_NOT_ENOUGH_RICE = "FAIL_NOT_ENOUGH_RICE";
        /// <summary>
        /// 초기 지역 선택 또는 최초 로비 초기화가 끝나지 않아 수령할 회차가 없다.
        /// </summary>
        public const string GUIDE_QUEST_NOT_ISSUED = "GUIDE_QUEST_NOT_ISSUED";
        /// <summary>
        /// 요청한 회차가 이미 수령됐거나 현재 발행 회차와 다르다.
        /// </summary>
        public const string GUIDE_QUEST_STATE_CHANGED = "GUIDE_QUEST_STATE_CHANGED";
        /// <summary>
        /// 분류되지 않은 서버 내부 처리 오류가 발생했다.
        /// </summary>
        public const string INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
        /// <summary>
        /// api-secret-key가 없거나 서버 설정과 일치하지 않는다.
        /// </summary>
        public const string INVALID_API_KEY = "INVALID_API_KEY";
        /// <summary>
        /// 요청 body 또는 header 형식이 API 계약과 다르다.
        /// </summary>
        public const string INVALID_REQUEST = "INVALID_REQUEST";
        /// <summary>
        /// uid와 user-session-key 조합이 현재 활성 세션이 아니다.
        /// </summary>
        public const string INVALID_SESSION = "INVALID_SESSION";
        /// <summary>
        /// DEV 테스트 로그인의 test_uid가 양수 정수가 아니다.
        /// </summary>
        public const string INVALID_TEST_UID = "INVALID_TEST_UID";
        /// <summary>
        /// 열려는 주머니·랜덤박스 stack 수량이 부족하다.
        /// </summary>
        public const string ITEM_CONTAINER_NOT_ENOUGH = "ITEM_CONTAINER_NOT_ENOUGH";
        /// <summary>
        /// 닉네임에 허용하지 않는 제어문자가 포함되어 있다.
        /// </summary>
        public const string NICKNAME_INVALID_CHARACTER = "NICKNAME_INVALID_CHARACTER";
        /// <summary>
        /// trim한 닉네임 길이가 2~16자 범위를 벗어난다.
        /// </summary>
        public const string NICKNAME_INVALID_LENGTH = "NICKNAME_INVALID_LENGTH";
        /// <summary>
        /// 요청 Accept header가 JSON 응답을 허용하지 않는다.
        /// </summary>
        public const string NOT_ACCEPTABLE = "NOT_ACCEPTABLE";
        /// <summary>
        /// 요청 body가 서버의 허용 크기를 초과했다.
        /// </summary>
        public const string PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE";
        /// <summary>
        /// Firebase 등 외부 provider 호출을 현재 완료할 수 없다.
        /// </summary>
        public const string PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE";
        /// <summary>
        /// 로그인 요청 횟수가 IP별 제한을 초과했다.
        /// </summary>
        public const string RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED";
        /// <summary>
        /// Valkey 세션·action lock 기능을 현재 사용할 수 없다.
        /// </summary>
        public const string REDIS_UNAVAILABLE = "REDIS_UNAVAILABLE";
        /// <summary>
        /// region이 Wei(0)·Shu(1)·Wu(2) 중 활성 s_region에 대응하는 값이 아니다.
        /// </summary>
        public const string REGION_INVALID = "REGION_INVALID";
        /// <summary>
        /// 완료된 x-request-id를 다른 요청 내용에 다시 사용했다.
        /// </summary>
        public const string REQUEST_ID_REUSED = "REQUEST_ID_REUSED";
        /// <summary>
        /// action lock이 적용된 동일 사용자 요청(현재 초기 지역 선택)이 아직 처리 중이다.
        /// </summary>
        public const string REQUEST_IN_PROGRESS = "REQUEST_IN_PROGRESS";
        /// <summary>
        /// 요청한 method와 path에 대응하는 API가 없다.
        /// </summary>
        public const string ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND";
        /// <summary>
        /// scheduler job 실행이 실패했다.
        /// </summary>
        public const string SCHEDULER_JOB_FAILED = "SCHEDULER_JOB_FAILED";
        /// <summary>
        /// 더 최근 로그인이나 세션 발급으로 현재 세션이 교체됐다.
        /// </summary>
        public const string SESSION_SUPERSEDED = "SESSION_SUPERSEDED";
        /// <summary>
        /// x-table-version이 현재 서버 테이블 버전과 다르다.
        /// </summary>
        public const string TABLE_VERSION_MISMATCH = "TABLE_VERSION_MISMATCH";
        /// <summary>
        /// 오늘 광고 완료 상한에 도달했다.
        /// </summary>
        public const string TOURNAMENT_AD_LIMIT_REACHED = "TOURNAMENT_AD_LIMIT_REACHED";
        /// <summary>
        /// 중단·대체·만료된 전투다.
        /// </summary>
        public const string TOURNAMENT_BATTLE_NOT_ACTIVE = "TOURNAMENT_BATTLE_NOT_ACTIVE";
        /// <summary>
        /// 날짜 또는 후보 버전이 달라 다시 조회해야 한다.
        /// </summary>
        public const string TOURNAMENT_CANDIDATE_STALE = "TOURNAMENT_CANDIDATE_STALE";
        /// <summary>
        /// 공격 편성을 먼저 저장해야 한다.
        /// </summary>
        public const string TOURNAMENT_FORMATION_REQUIRED = "TOURNAMENT_FORMATION_REQUIRED";
        /// <summary>
        /// 남은 도전 횟수가 없다.
        /// </summary>
        public const string TOURNAMENT_NO_ENTRIES = "TOURNAMENT_NO_ENTRIES";
        /// <summary>
        /// 본인의 유효한 미사용 방어 손실 이력이 아니다.
        /// </summary>
        public const string TOURNAMENT_REVENGE_UNAVAILABLE = "TOURNAMENT_REVENGE_UNAVAILABLE";
        /// <summary>
        /// 입장 차단 또는 결과 마감 시각을 지났다.
        /// </summary>
        public const string TOURNAMENT_SEASON_CLOSED = "TOURNAMENT_SEASON_CLOSED";
        /// <summary>
        /// 시즌 최종화 또는 초기 준비가 진행 중이다.
        /// </summary>
        public const string TOURNAMENT_SEASON_NOT_READY = "TOURNAMENT_SEASON_NOT_READY";
        /// <summary>
        /// 유효한 상대 방어 편성이 없다.
        /// </summary>
        public const string TOURNAMENT_TARGET_UNAVAILABLE = "TOURNAMENT_TARGET_UNAVAILABLE";
        /// <summary>
        /// 요청 Content-Type이 application/x-msgpack이라 현재 지원하지 않는다.
        /// </summary>
        public const string UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE";
        /// <summary>
        /// 계정 삭제가 이미 예약되어 있다.
        /// </summary>
        public const string USER_ACCOUNT_DELETION_IN_PROGRESS = "USER_ACCOUNT_DELETION_IN_PROGRESS";
        /// <summary>
        /// 취소할 계정 삭제 예약이 없다.
        /// </summary>
        public const string USER_ACCOUNT_DELETION_NOT_IN_PROGRESS = "USER_ACCOUNT_DELETION_NOT_IN_PROGRESS";
        /// <summary>
        /// 계정 상태 또는 현재 정지 정책으로 로그인이 제한된다.
        /// </summary>
        public const string USER_SUSPENDED = "USER_SUSPENDED";
    }
}
