// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 계정의 현재 이용 가능 상태.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AccountState
    {
        /// <summary>
        /// 정상 이용 가능
        /// </summary>
        [EnumMember(Value = "ACTIVE")]
        Active = 0,
        /// <summary>
        /// 기간이 있는 일시 정지
        /// </summary>
        [EnumMember(Value = "TEMPORARY_SUSPENDED")]
        TemporarySuspended = 1,
        /// <summary>
        /// 영구 이용 정지
        /// </summary>
        [EnumMember(Value = "PERMANENT_SUSPENDED")]
        PermanentSuspended = 2,
        /// <summary>
        /// 삭제 완료
        /// </summary>
        [EnumMember(Value = "DELETED")]
        Deleted = 3,
    }
}
