// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 승급 재료 타입
    /// </summary>
    public enum AscensionMaterialType
    {
        /// <summary>
        /// 공용 영혼석
        /// </summary>
        PublicSoulStone = 0,
        /// <summary>
        /// 클래스 영혼석
        /// </summary>
        ClassSoulStone = 1,
        /// <summary>
        /// 장수 영혼석
        /// </summary>
        DedicatedSoulStone = 2,
    }
}
