// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 보스 타입
    /// </summary>
    public enum BossType
    {
        /// <summary>
        /// 기본
        /// </summary>
        Basic = 0,
        /// <summary>
        /// 진
        /// </summary>
        Jin = 1,
    }
}
