// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 보스 등급
    /// </summary>
    public enum BossGrade
    {
        /// <summary>
        /// 일반
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 정예
        /// </summary>
        Elite = 1,
        /// <summary>
        /// 명장
        /// </summary>
        General = 2,
        /// <summary>
        /// 영웅
        /// </summary>
        Hero = 3,
        /// <summary>
        /// 전설
        /// </summary>
        Legend = 4,
    }
}
