// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 번들 아이템 타입
    /// </summary>
    public enum BundleItemType
    {
        /// <summary>
        /// 주머니
        /// </summary>
        Pocket = 0,
        /// <summary>
        /// 랜덤 상자
        /// </summary>
        RandomBox = 1,
    }
}
