// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 영지 디버프 타입
    /// </summary>
    public enum CastleDebuffType
    {
        /// <summary>
        /// 시간 단축 효율 감소 (궁성)
        /// </summary>
        DebuffTimeReduceEfficiency = 0,
        /// <summary>
        /// 획득량 감소 수령 시점 (시장/농지)
        /// </summary>
        DebuffIncomeRate = 1,
        /// <summary>
        /// 아이템 할인율 감소 (행상)
        /// </summary>
        DebuffDiscountRate = 2,
        /// <summary>
        /// 높은 등급 임무 등장 확률 감소 (관아)
        /// </summary>
        DebuffHighGradeMissionRate = 3,
    }
}
