// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 영지 건물 증축의 현재 진행 상태.
    /// </summary>
    public enum CastleBuildingUpgradeStatus
    {
        /// <summary>
        /// 시간 경과 중
        /// </summary>
        Running = 0,
        /// <summary>
        /// 선행 조건 미충족으로 일시 정지
        /// </summary>
        Paused = 1,
    }
}
