// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 캐릭터 클래스
    /// </summary>
    public enum CharacterClass
    {
        /// <summary>
        /// 지휘관
        /// </summary>
        Commander = 0,
        /// <summary>
        /// 용장
        /// </summary>
        Champion = 1,
        /// <summary>
        /// 선봉장
        /// </summary>
        Vanguard = 2,
        /// <summary>
        /// 추격자
        /// </summary>
        Chaser = 3,
        /// <summary>
        /// 궁장
        /// </summary>
        Archer = 4,
        /// <summary>
        /// 책사
        /// </summary>
        Strategist = 5,
    }
}
