// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 무장 성장 한 번의 최종 판정.
    /// </summary>
    public enum CharacterGrowthResult
    {
        /// <summary>
        /// 확률 성공
        /// </summary>
        Success = 0,
        /// <summary>
        /// 실패
        /// </summary>
        Fail = 1,
        /// <summary>
        /// 누적 성장 포인트 보장 성공
        /// </summary>
        GuaranteedSuccess = 2,
    }
}
