// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 직책의 해금·진행 가능 상태.
    /// </summary>
    public enum CharacterPositionStatus
    {
        /// <summary>
        /// 해금 완료
        /// </summary>
        Unlocked = 0,
        /// <summary>
        /// 해금 조건 미충족
        /// </summary>
        Locked = 1,
        /// <summary>
        /// 진행 기록 연결 전이라 판정 불가
        /// </summary>
        Unavailable = 2,
    }
}
