// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CombatStatKey
    {
        [EnumMember(Value = "attack_power")]
        AttackPower = 0,
        [EnumMember(Value = "defence")]
        Defence = 1,
        [EnumMember(Value = "health_max")]
        HealthMax = 2,
        [EnumMember(Value = "attack_speed")]
        AttackSpeed = 3,
        [EnumMember(Value = "move_speed")]
        MoveSpeed = 4,
        [EnumMember(Value = "critical_rate")]
        CriticalRate = 5,
        [EnumMember(Value = "critical_damage")]
        CriticalDamage = 6,
        [EnumMember(Value = "cooldown_rate")]
        CooldownRate = 7,
        [EnumMember(Value = "life_steal")]
        LifeSteal = 8,
        [EnumMember(Value = "boss_damage")]
        BossDamage = 9,
    }
}
