// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 콘텐츠 상점 타입 (s_shop.shop_type 및 API)
    /// </summary>
    public enum ContentShopType
    {
        /// <summary>
        /// 일일 상점
        /// </summary>
        Daily = 1,
        /// <summary>
        /// 레이드 상점
        /// </summary>
        Raid = 2,
        /// <summary>
        /// 토너먼트 상점
        /// </summary>
        Tournament = 3,
    }
}
