// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 무장·매치 소속 국가 분류 (초기 지역 선택 API용 아님)
    /// </summary>
    public enum Country
    {
        /// <summary>
        /// 위
        /// </summary>
        Wei = 0,
        /// <summary>
        /// 촉
        /// </summary>
        Shu = 1,
        /// <summary>
        /// 오
        /// </summary>
        Wu = 2,
        /// <summary>
        /// 군
        /// </summary>
        Force = 3,
        /// <summary>
        /// 다중 국가(s_match 전용)
        /// </summary>
        Mixed = 4,
        /// <summary>
        /// 추후 생성될 국가분류
        /// </summary>
        Etc = 5,
    }
}
