// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 던전 보스 등급
    /// </summary>
    public enum DungeonBossGrade
    {
        /// <summary>
        /// 일반
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 난세
        /// </summary>
        Elite = 1,
        /// <summary>
        /// 극한
        /// </summary>
        General = 2,
        /// <summary>
        /// 지옥
        /// </summary>
        Hero = 3,
        /// <summary>
        /// 심연
        /// </summary>
        Legend = 4,
    }
}
