// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 적 국가
    /// </summary>
    public enum EnemyCountry
    {
        /// <summary>
        /// 위
        /// </summary>
        Wei = 0,
        /// <summary>
        /// 촉
        /// </summary>
        Shu = 1,
        /// <summary>
        /// 오
        /// </summary>
        Wu = 2,
        /// <summary>
        /// 군
        /// </summary>
        Force = 3,
        /// <summary>
        /// 황건적
        /// </summary>
        YellowTurbans = 4,
        /// <summary>
        /// 고대
        /// </summary>
        Ancient = 5,
    }
}
