// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 계정 생성 및 로그인에 사용한 인증 방식.
    /// </summary>
    public enum GameClientLoginType
    {
        /// <summary>
        /// Firebase anonymous 인증. 소셜 연동 목록에는 포함하지 않는다.
        /// </summary>
        GuestLogin = 1,
        /// <summary>
        /// Google 계정 로그인
        /// </summary>
        GoogleLogin = 2,
        /// <summary>
        /// Facebook 계정 로그인
        /// </summary>
        FacebookLogin = 3,
        /// <summary>
        /// Apple 계정 로그인
        /// </summary>
        AppleLogin = 4,
    }
}
