// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 성장 재료 타입
    /// </summary>
    public enum GrowthMaterialType
    {
        /// <summary>
        /// 군량
        /// </summary>
        Rice = 0,
        /// <summary>
        /// 금화
        /// </summary>
        Gold = 1,
    }
}
