// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 서버가 발행한 가이드 퀘스트 종류.
    /// </summary>
    public enum GuideQuestKind
    {
        /// <summary>
        /// 최초 진행 학습 퀘스트
        /// </summary>
        Learning = 0,
        /// <summary>
        /// 반복 퀘스트
        /// </summary>
        Repeat = 1,
    }
}
