// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 아이템 상세 타입
    /// </summary>
    public enum ItemDetailType
    {
        /// <summary>
        /// 군량
        /// </summary>
        Rice = 0,
        /// <summary>
        /// 금화
        /// </summary>
        Gold = 1,
        /// <summary>
        /// 시간석
        /// </summary>
        TimeStone = 2,
        /// <summary>
        /// 군량 주머니
        /// </summary>
        PocketRice = 3,
        /// <summary>
        /// 금화 주머니
        /// </summary>
        PocketGold = 4,
        /// <summary>
        /// 시간석 주머니
        /// </summary>
        PocketTimeStone = 5,
        /// <summary>
        /// 클래스 영혼석 랜덤박스
        /// </summary>
        RandomBoxClassSoulStone = 6,
        /// <summary>
        /// 전용 영혼석 랜덤박스
        /// </summary>
        RandomBoxDedicatedSoulStone = 7,
        /// <summary>
        /// 보물 조각 랜덤박스
        /// </summary>
        RandomBoxTreasurePieceRandomBox = 8,
        /// <summary>
        /// 일반 연회권
        /// </summary>
        TicketGachaNormal = 9,
        /// <summary>
        /// 고급 연회권
        /// </summary>
        TicketGachaPremium = 10,
        /// <summary>
        /// 레이드 포인트
        /// </summary>
        PointRaid = 11,
        /// <summary>
        /// 토너먼트 포인트
        /// </summary>
        PointTournament = 12,
        /// <summary>
        /// 공용 영혼석
        /// </summary>
        SoulStonePublic = 13,
        /// <summary>
        /// 전용 영혼석
        /// </summary>
        SoulStoneDedicated = 14,
        /// <summary>
        /// 클래스 영혼석
        /// </summary>
        SoulStoneClass = 15,
        /// <summary>
        /// 보물 마일리지
        /// </summary>
        TreasureMileage = 16,
        /// <summary>
        /// 보물 조각
        /// </summary>
        TreasurePiece = 17,
        /// <summary>
        /// 보물
        /// </summary>
        Treasure = 18,
        /// <summary>
        /// 토너먼트 티켓
        /// </summary>
        TicketTournament = 19,
    }
}
