// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 아이템 등급
    /// </summary>
    public enum ItemGrade
    {
        /// <summary>
        /// 일반
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 고급
        /// </summary>
        Elite = 1,
        /// <summary>
        /// 희귀
        /// </summary>
        General = 2,
        /// <summary>
        /// 명품
        /// </summary>
        Hero = 3,
        /// <summary>
        /// 국보
        /// </summary>
        Legend = 4,
    }
}
