// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 아이템 타입
    /// </summary>
    public enum ItemType
    {
        /// <summary>
        /// 재화
        /// </summary>
        Currency = 0,
        /// <summary>
        /// 영혼석
        /// </summary>
        SoulStone = 1,
        /// <summary>
        /// 번들 (주머니·랜덤 상자)
        /// </summary>
        Bundle = 2,
        /// <summary>
        /// 아이템
        /// </summary>
        Item = 4,
        /// <summary>
        /// 보물 파편
        /// </summary>
        TreasurePiece = 5,
        /// <summary>
        /// 연회권
        /// </summary>
        GachaTicket = 6,
        /// <summary>
        /// 보물
        /// </summary>
        Treasure = 7,
        /// <summary>
        /// 입장권
        /// </summary>
        ContentsTicket = 8,
    }
}
