// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 구매한도 초기화 주기
    /// </summary>
    public enum LimitResetType
    {
        /// <summary>
        /// 일일 (빈칸일 때 기본값)
        /// </summary>
        Daily = 0,
        /// <summary>
        /// 주간
        /// </summary>
        Weekly = 1,
        /// <summary>
        /// 시즌
        /// </summary>
        Season = 2,
        /// <summary>
        /// 영구 (초기화 없음)
        /// </summary>
        Permanent = 3,
    }
}
