// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 네비게이션
    /// </summary>
    public enum Navigation
    {
        /// <summary>
        /// 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 장수관리
        /// </summary>
        Character = 0,
        /// <summary>
        /// 영지
        /// </summary>
        Castle = 1,
        /// <summary>
        /// 요일던전
        /// </summary>
        Dungeon = 2,
        /// <summary>
        /// 상점
        /// </summary>
        Shop = 3,
        /// <summary>
        /// 연회
        /// </summary>
        Gacha = 4,
        /// <summary>
        /// 스토리모드
        /// </summary>
        Story = 5,
        /// <summary>
        /// 레이드
        /// </summary>
        Raid = 6,
        /// <summary>
        /// 프로필
        /// </summary>
        Profile = 7,
        /// <summary>
        /// 토너먼트
        /// </summary>
        Tournament = 8,
        /// <summary>
        /// 인벤토리
        /// </summary>
        Inventory = 9,
    }
}
