// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 로그인 메타데이터에 기록하는 클라이언트 실행 플랫폼.
    /// </summary>
    public enum OsType
    {
        /// <summary>
        /// Android 앱
        /// </summary>
        Aos = 1,
        /// <summary>
        /// iOS 앱
        /// </summary>
        Ios = 2,
        /// <summary>
        /// APK 배포 앱
        /// </summary>
        Apk = 3,
        /// <summary>
        /// Unity WebGL 클라이언트
        /// </summary>
        Webgl = 4,
        /// <summary>
        /// 일반 웹 클라이언트
        /// </summary>
        Web = 5,
    }
}
