// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 상점 상품 결제에 사용하는 재화 종류
    /// </summary>
    public enum PayType
    {
        /// <summary>
        /// 군량 결제
        /// </summary>
        Rice = 0,
        /// <summary>
        /// 무료 금화 결제
        /// </summary>
        FreeGold = 1,
        /// <summary>
        /// 유료 금화 결제
        /// </summary>
        PaidGold = 2,
        /// <summary>
        /// 레이드 포인트 결제
        /// </summary>
        RaidPoint = 3,
        /// <summary>
        /// 토너먼트 포인트 결제
        /// </summary>
        TournamentPoint = 4,
    }
}
