// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 직책 분류
    /// </summary>
    public enum PositionCategory
    {
        /// <summary>
        /// 수장
        /// </summary>
        Leader = 0,
        /// <summary>
        /// 관직
        /// </summary>
        Rank = 1,
        /// <summary>
        /// 칭호
        /// </summary>
        Title = 2,
    }
}
