// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 직책 장착 조건 종류
    /// </summary>
    public enum PositionEquipConditionType
    {
        /// <summary>
        /// 무장 등급
        /// </summary>
        CharacterGrade = 0,
        /// <summary>
        /// 무장 성장 단계
        /// </summary>
        CharacterGrowthStage = 1,
    }
}
