// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 직책 해금 조건 종류
    /// </summary>
    public enum PositionUnlockConditionType
    {
        /// <summary>
        /// 해금 조건 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 모든 무장 클래스마다 전설 등급 무장을 설정 인원 이상 보유
        /// </summary>
        AllCharacterClassGradeOwned = 0,
        /// <summary>
        /// 책사 외 전설 등급 무장을 설정 인원 이상 보유
        /// </summary>
        NonStrategistCharacterGradeOwned = 1,
        /// <summary>
        /// 책사 클래스에서 직책별 고정 등급 이상 무장을 설정 인원 이상 보유
        /// </summary>
        StrategistCharacterGradeOwned = 2,
        /// <summary>
        /// 궁성 레벨이 설정값 이상
        /// </summary>
        PalaceLevelReached = 3,
        /// <summary>
        /// 관아 레벨이 설정값 이상
        /// </summary>
        OfficeLevelReached = 4,
        /// <summary>
        /// 레이드 누적 참여 횟수가 설정값 이상
        /// </summary>
        RaidPlayCountReached = 5,
        /// <summary>
        /// 요일던전 누적 참여 횟수가 설정값 이상
        /// </summary>
        DailyDungeonPlayCountReached = 6,
        /// <summary>
        /// 토너먼트 누적 참여 횟수가 설정값 이상
        /// </summary>
        TournamentPlayCountReached = 7,
        /// <summary>
        /// 적 누적 처치 횟수가 설정값 이상
        /// </summary>
        EnemyKillCountReached = 8,
        /// <summary>
        /// 스킬 누적 사용 횟수가 설정값 이상
        /// </summary>
        SkillUseCountReached = 9,
        /// <summary>
        /// 지휘관 클래스의 정예 등급 무장을 설정 인원 이상 보유
        /// </summary>
        CommanderCharacterGradeOwned = 10,
        /// <summary>
        /// 용장 클래스의 정예 등급 무장을 설정 인원 이상 보유
        /// </summary>
        ChampionCharacterGradeOwned = 11,
        /// <summary>
        /// 선봉장 클래스의 정예 등급 무장을 설정 인원 이상 보유
        /// </summary>
        VanguardCharacterGradeOwned = 12,
        /// <summary>
        /// 추격자 클래스의 정예 등급 무장을 설정 인원 이상 보유
        /// </summary>
        ChaserCharacterGradeOwned = 13,
        /// <summary>
        /// 궁장 클래스의 정예 등급 무장을 설정 인원 이상 보유
        /// </summary>
        ArcherCharacterGradeOwned = 14,
    }
}
