// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 퀘스트 기간 타입
    /// </summary>
    public enum QuestDateType
    {
        /// <summary>
        /// 일일
        /// </summary>
        Daily = 0,
        /// <summary>
        /// 주간
        /// </summary>
        Weekly = 1,
    }
}
