// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 미션 타입
    /// </summary>
    public enum QuestType
    {
        /// <summary>
        /// 로그인
        /// </summary>
        Login = 0,
        /// <summary>
        /// 적 처치하기
        /// </summary>
        EnemyKill = 1,
        /// <summary>
        /// 토너먼트 참여하기
        /// </summary>
        TournamentPlay = 2,
        /// <summary>
        /// 레이드 참여하기
        /// </summary>
        RaidPlay = 3,
        /// <summary>
        /// 연회 진행하기
        /// </summary>
        GachaProceed = 4,
        /// <summary>
        /// 군량 수확하기
        /// </summary>
        RiceClaim = 5,
        /// <summary>
        /// 금화 수확하기
        /// </summary>
        GoldClaim = 6,
        /// <summary>
        /// 관아 파견하기
        /// </summary>
        OfficeDispatch = 7,
        /// <summary>
        /// 요일 던전 플레이하기
        /// </summary>
        DailyDungeonPlay = 8,
        /// <summary>
        /// 스테이지 보스 처치하기
        /// </summary>
        StageBossKill = 9,
        /// <summary>
        /// 광고 시청하기
        /// </summary>
        AdsWatch = 10,
        /// <summary>
        /// 상품 구매하기
        /// </summary>
        ItemBuy = 11,
        /// <summary>
        /// 아이템 사용하기
        /// </summary>
        ItemUse = 12,
    }
}
