// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 레이드 구간 타입
    /// </summary>
    public enum RaidRankType
    {
        /// <summary>
        /// 정확한 순위 구간
        /// </summary>
        Rank = 0,
        /// <summary>
        /// 상위 백분위 구간
        /// </summary>
        Percent = 1,
    }
}
