// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 레이드 랭킹 티어 타입
    /// </summary>
    public enum RaidRankTierType
    {
        /// <summary>
        /// 정확한 순위
        /// </summary>
        Rank = 0,
        /// <summary>
        /// 퍼센타일 구간
        /// </summary>
        Percent = 1,
    }
}
