// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 게임 시작 지역 (클라이언트 RegionType과 숫자 일치)
    /// </summary>
    public enum RegionType
    {
        /// <summary>
        /// 미선택 (API body에서는 허용하지 않고 DB는 null 사용)
        /// </summary>
        None = -1,
        /// <summary>
        /// 위 지역
        /// </summary>
        Wei = 0,
        /// <summary>
        /// 촉 지역
        /// </summary>
        Shu = 1,
        /// <summary>
        /// 오 지역
        /// </summary>
        Wu = 2,
        /// <summary>
        /// 기타 지역 (초기 선택 API 불가)
        /// </summary>
        Etc = 3,
        /// <summary>
        /// 클라이언트 UI 범위 sentinel (초기 선택 API 불가)
        /// </summary>
        Max = 4,
        /// <summary>
        /// 역사 분류 (초기 선택 API 불가)
        /// </summary>
        Historical = 5,
    }
}
