// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 스토리 보상 재화 타입
    /// </summary>
    public enum RewardCurrencyType
    {
        /// <summary>
        /// 재화 보상 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 금화
        /// </summary>
        Gold = 0,
    }
}
