// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 등장 트리거
    /// </summary>
    public enum SpawnTrigger
    {
        /// <summary>
        /// 상시 등장
        /// </summary>
        Always = 0,
        /// <summary>
        /// 성문 무력 요구치 미달
        /// </summary>
        GateStrengthLack = 1,
    }
}
