// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 영지 능력치 타입
    /// </summary>
    public enum StatType
    {
        /// <summary>
        /// 없음
        /// </summary>
        None = -1,
        /// <summary>
        /// 통솔
        /// </summary>
        Leadership = 0,
        /// <summary>
        /// 무력
        /// </summary>
        Strength = 1,
        /// <summary>
        /// 지력
        /// </summary>
        Intellect = 2,
        /// <summary>
        /// 정치
        /// </summary>
        Politics = 3,
        /// <summary>
        /// 매력
        /// </summary>
        Charisma = 4,
    }
}
