// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 스토리 노드 타입
    /// </summary>
    public enum StoryNodeType
    {
        /// <summary>
        /// 스토리
        /// </summary>
        Story = 0,
        /// <summary>
        /// 장수 획득
        /// </summary>
        Character = 1,
        /// <summary>
        /// 복합
        /// </summary>
        StoryCharacter = 2,
        /// <summary>
        /// IF 스토리
        /// </summary>
        IfStory = 3,
    }
}
