// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 이용 정지 이력에 기록하는 정지 종류.
    /// </summary>
    public enum SuspendedType
    {
        /// <summary>
        /// 기간이 있는 일시 정지
        /// </summary>
        TemporarySuspended = 2,
        /// <summary>
        /// 영구 이용 정지
        /// </summary>
        PermanentSuspended = 3,
    }
}
