// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 토너먼트 전투 이력의 현재 상태.
    /// </summary>
    public enum TournamentBattleStatus
    {
        /// <summary>
        /// 진행 중
        /// </summary>
        Active = 0,
        /// <summary>
        /// 정산 완료
        /// </summary>
        Completed = 1,
        /// <summary>
        /// 새 전투 시작으로 포기됨
        /// </summary>
        Abandoned = 2,
        /// <summary>
        /// 제한시간 만료
        /// </summary>
        Expired = 3,
    }
}
