// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 토너먼트 전투의 클라이언트 보고·서버 확정 결과.
    /// </summary>
    public enum TournamentBattleResult
    {
        /// <summary>
        /// 승리
        /// </summary>
        Win = 0,
        /// <summary>
        /// 패배
        /// </summary>
        Lose = 1,
    }
}
