// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 토너먼트 시즌의 현재 API 이용 가능 상태.
    /// </summary>
    public enum TournamentAvailabilityStatus
    {
        /// <summary>
        /// 토너먼트 이용 가능
        /// </summary>
        Open = 0,
        /// <summary>
        /// 시즌 준비 중
        /// </summary>
        Preparing = 1,
    }
}
