// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 특성 등급
    /// </summary>
    public enum TraitsGrade
    {
        /// <summary>
        /// 일반
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 명장
        /// </summary>
        General = 1,
        /// <summary>
        /// 전설
        /// </summary>
        Legend = 2,
    }
}
