// Generated by threekingz-server. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThreeKingdoms.Shared.Enums;
using ThreeKingdoms.Shared.Types;

namespace ThreeKingdoms.Shared.Enums
{
    /// <summary>
    /// 사용자에게 귀속되는 재화 종류 (실제 저장 위치는 각 member 설명 참조)
    /// </summary>
    public enum UserAssetType
    {
        /// <summary>
        /// 군량 (user_asset.rice)
        /// </summary>
        Rice = 0,
        /// <summary>
        /// 무료 금화 (향후 금화 분리 구조에서 사용)
        /// </summary>
        FreeGold = 1,
        /// <summary>
        /// 유료 금화 (향후 금화 분리 구조에서 사용)
        /// </summary>
        PaidGold = 2,
        /// <summary>
        /// 레이드 포인트 (user_asset.raid_point)
        /// </summary>
        RaidPoint = 3,
        /// <summary>
        /// 토너먼트 시즌 포인트 (user_tournament_season.point_amount, 시즌 초기화)
        /// </summary>
        TournamentPoint = 4,
        /// <summary>
        /// 시간석 (user_asset.time_stone)
        /// </summary>
        TimeStone = 5,
    }
}
